tocco/tocco-client

config/_base.js
packages/tocco-test-util/.npmignore
packages/tocco-test-util/README.md
packages/tocco-test-util/package.json
packages/tocco-test-util/src/IntlStub/IntlStub.js
packages/tocco-test-util/src/IntlStub/index.js
packages/tocco-test-util/src/main.js

A new package which provides the most needed mocks for writing tests.

feat(tocco-test-util): add new package tocco-test-util

---

packages/tocco-ui-showcase/src/uiComponentsTree.js
packages/tocco-ui/src/SearchBox/SearchBox.js
packages/tocco-ui/src/SearchBox/SearchBox.spec.js
packages/tocco-ui/src/SearchBox/example.js
packages/tocco-ui/src/SearchBox/index.js

Add new component `SearchBox`. The html structure of the component has been adopted from the bootstrap page (http://getbootstrap.com/components/#input-groups-buttons).

Pr/entity browser/search component

---

packages/entity-browser/src/components/EntityBrowser/EntityBrowser.js
packages/entity-browser/src/containers/EntityBrowserContainer.js
packages/entity-browser/src/dev/fetchMocks.js
packages/entity-browser/src/dev/recordFactory.js
packages/entity-browser/src/modules/entityBrowser/reducer.js
packages/entity-browser/src/modules/entityBrowser/sagas.js
packages/login/src/modules/sagas.js

- improve method generate fetch url
- omit empty parameters
- sort parameters by key in order to allow more cache hits
(reverse proxy)

feat(entity-browser): implement ordering of table

---

packages/entity-browser/package.json
packages/entity-browser/src/appFactory.js
packages/entity-browser/src/dev/input.json
packages/entity-browser/src/modules/entityBrowser/actions.js
packages/entity-browser/src/modules/entityBrowser/reducer.js

- add limit and formBase as new input parameter
- generic input validation (can eventually be extracted later for other packages)

feat(entity-browser): enhance input parameters

---

packages/entity-browser/src/dev/fetchMocks.js
packages/entity-browser/src/modules/entityBrowser/reducer.js
packages/entity-browser/src/modules/entityBrowser/reducer.spec.js
packages/entity-browser/src/modules/entityBrowser/sagas.js
packages/entity-browser/src/modules/entityBrowser/sagas.spec.js

Add missing handling for custom search- and list-forms.

Pr/entity browser/form base

---

README.md

- add tocco-ui development hint
- add enzyme to test libs list

docs(tocco-client): readme

---

packages/tocco-ui-showcase/src/uiComponentsTree.js
packages/tocco-ui/src/EditableValue/EditableValue.js
packages/tocco-ui/src/EditableValue/EditableValue.spec.js
packages/tocco-ui/src/EditableValue/example.js
packages/tocco-ui/src/EditableValue/index.js
packages/tocco-ui/src/EditableValue/styles.scss
packages/tocco-ui/src/EditableValue/typeEditorFactory.js
packages/tocco-ui/src/EditableValue/typeEditorFactory.spec.js
packages/tocco-ui/src/EditableValue/typeEditors/MultiSelect.js
packages/tocco-ui/src/EditableValue/typeEditors/StringEdit.js
packages/tocco-ui/src/EditableValue/typeEditors/StringEdit.spec.js
packages/tocco-ui/src/main.js

- basic implementation for type string and multi-select
- tests
- integrate in showcase

feat(tocco-ui): add EditableValue component

---

build/webpack.config.js

- to fix tocco-ui-showcase relativ path

chore: change output public path

---

.eslintignore
package.json
plopfile.js
templates/action/creator.js
templates/component/index.js
templates/component/stateful.js
templates/component/stateless.js
templates/component/tests.js

- add generator for react component generation
- add generator for redux action generation

chore: introduce plop

---

packages/tocco-ui/src/FormattedValue/FormattedValue.js
packages/tocco-ui/src/FormattedValue/example.js
packages/tocco-ui/src/FormattedValue/typeFormatterProvider.js
packages/tocco-ui/src/FormattedValue/typeFormatters/PercentFormatter.js

- add percent type with example
- add virtual types: identifier, postcode, ipaddress, html, datamaount,
version
- better missing type message
- Dynamic PropType

feat(tocco-ui): better FormattedValue types

---

packages/entity-browser/src/components/SearchForm/SearchForm.js
packages/entity-browser/src/components/SearchForm/SearchForm.spec.js
packages/entity-browser/src/containers/SearchFormContainer.js
packages/entity-browser/src/dev/input.json
packages/entity-browser/src/modules/searchForm/actions.js
packages/entity-browser/src/modules/searchForm/reducer.js
packages/entity-browser/src/modules/searchForm/reducer.spec.js
packages/entity-browser/src/util/input.js

Add the possibility to preset search field values and also to set them hidden if desired

Pr/entity browser/search form default values

---

packages/tocco-theme/src/ToccoTheme/tocco/webpack-environment-development.scss
packages/tocco-theme/src/ToccoTheme/variable/bootstrap-variable.scss

- change dev border-size
- primary color to tocco red

refactor(tocco-theme): dev styling

---

packages/entity-browser/src/modules/detailView/actions.js
packages/entity-browser/src/modules/detailView/sagas.spec.js

- otherwise infrequent errors could occur on travis

test(entity-browser): fix time sensitive saga  test

---

.eslintrc
bin/githooks/msg-validation.js
packages/entity-browser/src/dev/fetchMockHelpers.js
packages/entity-browser/src/util/input.js
packages/login/src/appFactory.js
packages/login/src/modules/sagas.js
packages/merge/src/modules/wizard/sagas.js
packages/tocco-ui-showcase/package.json
packages/tocco-ui-showcase/src/components/ShowCaseApp.js
packages/tocco-ui/src/Button/example.js
packages/tocco-ui/src/EditableValue/example.js
packages/tocco-ui/src/EditableValue/typeEditorFactory.js
packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
packages/tocco-ui/src/FormattedValue/example.js
packages/tocco-ui/src/FormattedValue/typeFormatterProvider.js
packages/tocco-ui/src/FormattedValue/typeFormatters/DateFormatter.js
packages/tocco-ui/src/FormattedValue/typeFormatters/DateTimeFormatter.js
packages/tocco-ui/src/LayoutBox/example.js
packages/tocco-ui/src/LoadMask/example.js
packages/tocco-ui/src/Pagination/example.js
packages/tocco-ui/src/SearchBox/example.js
packages/tocco-ui/src/Table/example.js
packages/tocco-util/src/appFactory/appFactory.js
packages/tocco-util/src/consoleLogger/consoleLogger.js
packages/tocco-util/src/consoleLogger/index.js
packages/tocco-util/src/errorLogging/handlers/consoleHandler.js
packages/tocco-util/src/errorLogging/sagas.js
packages/tocco-util/src/externalEvents/externalEvents.js
packages/tocco-util/src/utilFetchMocks/log.js

- add console logger util
- fix occurrence in various places
- add eslint disable where needed

chore: introduce eslint rule no-console

---

build/webpack.config.js
packages/tocco-ui/package.json
packages/tocco-ui/src/main.js
packages/tocco-util/src/appFactory/appFactory.js
server/index.html
server/standalone.html

- copy all scss files to dist folder. Not only from components folder
- add dummy main.js for tocco-ui package to be deployable to npm
- wrap all packages in tocco-ui-theme class

chore: stying adjustments

---

packages/entity-browser/package.json
packages/login/package.json
packages/merge/package.json
packages/tocco-ui/src/main.js
packages/tocco-util/package.json

- tocco-ui package was updated therefore the dependencies in other packages need to require the new version.
- Add ^ in tocco-uti package.json to require newest minor release

chore: update tocco-ui dependencies

---

packages/entity-browser/src/components/FormField/formFieldUtil.js
packages/entity-browser/src/components/FormField/formFieldUtil.spec.js
packages/entity-browser/src/dev/rest-responses/form_user_search.json
packages/tocco-ui/src/EditableValue/example.js
packages/tocco-ui/src/EditableValue/typeEditorFactory.js
packages/tocco-ui/src/EditableValue/typeEditors/DateRangeEdit.js
packages/tocco-ui/src/EditableValue/typeEditors/DateRangeEdit.spec.js

- Uses `DateAbstract` to render a range date picker.
- Is mapped to EditableValue component type `date-range`

feat(tocco-ui): Introduce DateRangeEdit component

---

packages/entity-browser/src/components/FormField/fieldFactory.js
packages/entity-browser/src/components/FormField/fieldTypeFactories/subGrid.js
packages/entity-browser/src/components/FormField/fieldTypeFactories/subGrid.spec.js
packages/entity-browser/src/dev/rest-responses/form_user_detail.json
packages/entity-browser/src/routes/detail/components/SubGrid/SubGrid.js
packages/entity-browser/src/routes/detail/components/SubGrid/SubGrid.specs.js

- pass some props to component
- fetch-mock and component mapping cleanups

sub-grid improvements

---

packages/entity-browser/src/dev/rest-responses/model_user.json
packages/entity-browser/src/routes/detail/components/SubGrid/SubGrid.js
packages/entity-browser/src/routes/detail/containers/SubGridContainer.js
packages/entity-browser/src/util/api/entities.js
packages/entity-browser/src/util/api/entities.spec.js
packages/entity-browser/src/util/detailView/fromFieldFactories/subGrid.js
packages/entity-browser/src/util/detailView/fromFieldFactories/subGrid.spec.js

- modify model transformer to not ignore new rest field 'reverseRelationName'

feat(entity-browser): pass relation input to subgrid

---

packages/entity-browser/src/main.js
packages/entity-list/src/main.js
packages/login/src/main.js
packages/merge/src/main.js
packages/tocco-util/src/appFactory/appFactory.js
packages/tocco-util/src/intl/intl.js
packages/tocco-util/src/intl/intl.spec.js

- refactor appFactory to pass additional modules. therefore change signature
to append optional inputs
- join textresource modules in a regex expression and add to fetch call

refactor(tocco-util): support multiple text resources modules

---

packages/entity-browser/package.json

- 0.3.1 was released but never committed

chore(entity-browser): bump version to 0.3.1

---

packages/tocco-theme/src/ToccoTheme/vendor-extension/bootstrap/icon-list.scss

this commit is related with https://git.tocco.ch/#/c/23827

style(tocco-theme): indent and variablize icon-list

---

package.json
packages/login/src/main.js
packages/merge/src/main.js
yarn.lock

chore: misc fixes

---

packages/entity-detail/README.md
packages/entity-detail/src/components/SubGrid/SubGrid.js
packages/entity-detail/src/containers/SubGridContainer.js

Event payload:
- `id`: id of the clicked record
- `gridName`: name of the sub grid
- `relationName`: name of the sub grid relation

feat(entity-detail): Introduce external event `onSubGridRowClick`

---

packages/entity-list/src/components/ListView/ListView.js

refactor(entity-list): remove border on table list

---

.travis.yml

- run saucelabs test only on nightly build
- add new packages to cache

chore: travis improvements

---

packages/tocco-util/README.md

docs(tocco-util): fix typos

---

packages/entity-detail/src/util/api/entities.js
packages/entity-detail/src/util/api/entities.spec.js

Older functions `request` and `getRequest` which return a promise are
deprecated - the new sagas should be used.

refactor(entity-detail): Use new REST request sagas

---

packages/tocco-util/src/form/ReduxFormFieldAdapter.js

- since this code was moved to util, the name of the text-resource should be adjusted

refactor(tocco-util): change resource name

---

packages/entity-list/src/modules/searchForm/sagas.js
packages/entity-list/src/util/searchFormValidation.js
packages/tocco-util/src/form/formBuilder.js
packages/tocco-util/src/mockData/data/user_search_form.json

- preselectedSearchFields should no be validated if there status is
hidden since the field is not present in the form and therefore the
type is unknown.

fix(entity-list): search form validation fix

---

packages/login/src/dev/fetchMocks.js
packages/login/src/main.js
packages/login/src/modules/passwordUpdate/password/sagas.js
packages/login/src/modules/passwordUpdate/validationRules/sagas.js
packages/login/src/modules/passwordUpdate/validationRules/sagas.spec.js
packages/tocco-util/src/appFactory/appFactory.js

- this is necessary to ensure rest api returns localized validation rules
if the user is not logged in

refactor(login): add locale parameter to validate request

---

packages/tocco-theme/package.json
packages/tocco-theme/src/ToccoTheme/vendor-extension/react-select/scss/components.scss
packages/tocco-theme/src/ToccoTheme/vendor-extension/react-select/scss/control.scss
packages/tocco-theme/src/ToccoTheme/vendor-extension/react-select/scss/default.scss
packages/tocco-theme/src/ToccoTheme/vendor-extension/react-select/scss/menu.scss
packages/tocco-theme/src/ToccoTheme/vendor-extension/react-select/scss/mixins.scss
packages/tocco-theme/src/ToccoTheme/vendor-extension/react-select/scss/multi.scss
packages/tocco-theme/src/ToccoTheme/vendor-extension/react-select/scss/select.scss
packages/tocco-theme/src/ToccoTheme/vendor-extension/react-select/scss/spinner.scss
packages/tocco-theme/src/ToccoTheme/vendor-extension/react-select/third-party-integration.scss

- i couldn't find a solution to integrate react-select style nicely.
as a workaround i just copied all sass files from react-select/sass

refactor(tocco-theme): workaround select styling

---

packages/scheduler/src/components/FullCalendar/FullCalendar.js
packages/scheduler/src/components/FullCalendar/FullCalendar.scss

- replace remove icon and move it to left side
- make resource area less wider

refactor(scheduler): style resource area

---

packages/tocco-theme/package.json

chore: publish

---

packages/tocco-ui/src/Button/Button.js
packages/tocco-ui/src/Button/Button.scss
packages/tocco-ui/src/Button/Button.spec.js
packages/tocco-ui/src/Button/example.js

- show pending icon even if no icon is set on button
- use fontawesome instead of own css for spinning animation
- show label/icon combinations im example

refactor(tocco-ui): button pending fix

---

packages/entity-browser/src/routes/entity-browser/components/EntityBrowser/EntityBrowser.js
packages/tocco-theme/src/ToccoTheme/vendor-extension/toastr/third-party-integration.scss
packages/tocco-ui-showcase/src/toccoUtilExamples/notifier/example.js
packages/tocco-util/src/actions/modules/sagas.spec.js
packages/tocco-util/src/notifier/components/Notifier.js
packages/tocco-util/src/notifier/components/Notifier.spec.js
packages/tocco-util/src/notifier/components/TitleMessage.js
packages/tocco-util/src/notifier/components/TitleMessage.spec.js
packages/tocco-util/src/notifier/index.js
packages/tocco-util/src/notifier/modules/actions.js
packages/tocco-util/src/notifier/modules/modalComponents/ModalContent.js
packages/tocco-util/src/notifier/modules/modalComponents/ModalContent.scss
packages/tocco-util/src/notifier/modules/modalComponents/ModalContent.spec.js
packages/tocco-util/src/notifier/modules/modalComponents/ModalDisplay.js
packages/tocco-util/src/notifier/modules/modalComponents/ModalDisplayContainer.js
packages/tocco-util/src/notifier/modules/modalComponents/reducer.js
packages/tocco-util/src/notifier/modules/modalComponents/reducer.spec.js
packages/tocco-util/src/notifier/modules/sagas.js
packages/tocco-util/src/notifier/modules/sagas.spec.js
packages/tocco-util/src/notifier/notificationActionFactory.js
packages/tocco-util/src/notifier/notificationActionFactory.spec.js
packages/tocco-util/src/notifier/notifier.js
packages/tocco-util/src/notifier/notifier.spec.js

- add ModalComponent notification
- Encapsulate toastr in Notifier component
- add examples for showcase
- general refactoring of notifier

feat(tocco-util): enhance notifier

---

packages/tocco-util/src/notifier/components/TitleMessage.js
packages/tocco-util/src/notifier/components/TitleMessage.spec.js

- e.g. to display <FormattedMessage> (react-intl) with values

refactor(tocco-util): notifier allow nodes as title and messages

---

packages/entity-detail/src/dev/fetchMockHelpers.js
packages/entity-detail/src/dev/fetchMocks.js
packages/entity-detail/src/util/api/documents.js
packages/tocco-ui/src/Preview/Figure.js
packages/tocco-ui/src/Preview/Preview.js
packages/tocco-ui/src/Preview/Preview.scss
packages/tocco-ui/src/Preview/Preview.spec.js
packages/tocco-ui/src/Preview/example.js
packages/tocco-ui/src/Upload/Upload.js
packages/tocco-ui/src/Upload/Upload.scss
packages/tocco-ui/src/Upload/UploadProgress.js
packages/tocco-ui/src/Upload/View.js
packages/tocco-util/src/mockData/mockData.js
packages/tocco-util/src/mockData/upload.js

- support files that are no images for upload and preview
- styling

feat(tocco-ui): upload improvements

---

packages/tocco-util/src/actions/components/Action.js
packages/tocco-util/src/actions/components/ActionGroup.js
packages/tocco-util/src/actions/components/GroupElement.js
packages/tocco-util/src/actions/components/SingleAction.js
packages/tocco-util/src/actions/components/SingleAction.spec.js
packages/tocco-util/src/actions/components/selectionHelper.js
packages/tocco-util/src/actions/components/selectionHelper.spec.js
packages/tocco-util/src/mockData/data/textResources.json
packages/tocco-util/src/mockData/data/user_detail_form.json
packages/tocco-util/src/mockData/data/user_list_form.json

- consider minSelection and maxSelection attribute on action definition
and disable action if selection count is not in range

feat(tocco-util): action selection range

---

build/webpack.config.js
package.json
packages/entity-browser/package.json
packages/entity-detail/package.json
packages/entity-list/package.json
packages/login/package.json
packages/merge/package.json
packages/resource-scheduler/package.json
packages/scheduler/package.json
packages/simple-form/package.json
packages/tocco-theme/package.json
packages/tocco-ui-showcase/package.json
packages/tocco-ui/package.json
plop/templates/package/package.json
yarn.lock

- with a hash, the chunks are unique named with each build and can therefore
be cached correctly.
- move clean of dist folder to webpack build

chore: add hash to dist chunks

---

server/standalone.html

- there is no unminified production file of react-dom

fix: correct react url in standalone.html

---

package.json
packages/resource-scheduler/package.json
packages/resource-scheduler/src/dev/fetchMockHelper.js
packages/resource-scheduler/src/dev/fetchMocks.js
packages/scheduler/package.json
packages/scheduler/src/components/Conflict/Conflict.js
packages/scheduler/src/components/Conflict/Conflict.spec.js
packages/scheduler/src/components/Conflict/index.js
packages/scheduler/src/components/Conflict/utils.js
packages/scheduler/src/components/FullCalendar/FullCalendar.js
packages/scheduler/src/components/FullCalendar/FullCalendar.scss
packages/scheduler/src/components/FullCalendar/FullCalendar.specs.js
packages/scheduler/src/components/Scheduler/utils.js
packages/scheduler/src/dev/textResources.json
packages/tocco-theme/package.json
packages/tocco-util/src/form/formBuilder.js

- Show border on existing conflicts
- Show localized text in event popover for existing and resolved conflicts
- Add mock data
- Load scheduler mock in resource-scheduler

Resource-Scheduler: Show Conflicts

---

packages/resource-scheduler/src/components/ResourceScheduler/ResourceScheduler.js
packages/resource-scheduler/src/components/SearchPanel/SearchPanel.js
packages/resource-scheduler/src/components/SearchPanel/SearchPanel.scss
packages/resource-scheduler/src/components/SearchPanel/SearchPanel.specs.js
packages/resource-scheduler/src/dev/data/calendarTypes.json

- adjust propTypes
- enhance mock data

feat(resource-scheduler): display color for each calendar type

---

.travis.yml

- wait longer than 10 minutes without output
- set concurrency to 1
- remove flow

chore: optimize travis lerna bootstrap

---

packages/tocco-ui/src/Icon/Icon.js
packages/tocco-ui/src/Icon/Icon.spec.js
packages/tocco-ui/src/Icon/example.js

- allow to pass unicode charcter as prop
- export StyledIcon

feat(tocco-ui): display unicode character as Icon

---

packages/entity-list/src/modules/list/sagas.js
packages/entity-list/src/modules/list/sagas.spec.js

- build count url with exactly the same base params as entity fetch

search filter count fix

---

packages/tocco-ui/src/Link/Link.js
packages/tocco-ui/src/Link/Link.spec.js
packages/tocco-ui/src/Link/StyledLink.js
packages/tocco-ui/src/Link/example.js

- show complete url as title on Link if required

style(tocco-ui): set typography for Link

---

packages/tocco-theme/src/ToccoTheme/DefaultTheme.js
packages/tocco-ui-showcase/src/uiComponentsTree.js
packages/tocco-ui/src/Icon/Icon.js
packages/tocco-ui/src/Icon/Icon.spec.js
packages/tocco-ui/src/SignalList/SignalList.js
packages/tocco-ui/src/SignalList/SignalList.spec.js
packages/tocco-ui/src/SignalList/SignalListItem.js
packages/tocco-ui/src/SignalList/SignalListItem.spec.js
packages/tocco-ui/src/SignalList/StyledSignalList.js
packages/tocco-ui/src/SignalList/StyledSignalListItem.js
packages/tocco-ui/src/SignalList/example.js
packages/tocco-ui/src/SignalList/index.js
packages/tocco-ui/src/utilStyles/assertObjectValuesMatchOtherObjectKeys.js
packages/tocco-ui/src/utilStyles/assertObjectValuesMatchOtherObjectKeys.spec.js
packages/tocco-ui/src/utilStyles/index.js
packages/tocco-ui/src/utilStyles/stylingConstants.js

- signalize conditions by icon, color and label in a list
- define singal colors
- define styling conditions
- utilize typographic components for SignalList

feat(tocco-ui): establish SignalList

---

packages/tocco-util/src/form/formBuilder.js

- otherwise fields with a dot (.) in name are not resolved properly.

refactor(tocco-util): transformField name before checking value

---

packages/tocco-ui/src/Button/Button.js
packages/tocco-ui/src/Button/Button.spec.js
packages/tocco-ui/src/Button/example.js

- add test and example
- clean up button test and remove irrelevant theme tags

refactor(tocco-ui): add child property to button

---

packages/tocco-util/src/mockData/data/my_session_only_detail_form.json
packages/tocco-util/src/mockData/data/my_session_only_model.json
packages/tocco-util/src/mockData/data/user_detail_form.json
packages/tocco-util/src/mockData/entities.js
packages/tocco-util/src/mockData/forms.js

- Support of query parameter (IN)
- add get for small form
- add form base to remote field

feat(tocco-util): improve mockData

---

package.json
server/standalone.html
server/static/package.json
server/static/yarn.lock

chore: update react to 16.4.2

---

packages/tocco-ui/src/Button/Button.spec.js
packages/tocco-ui/src/ButtonLink/ButtonLink.spec.js
packages/tocco-ui/src/Pagination/Pagination.spec.js

revise tocco-ui components according input from https://github.com/tocco/tocco-client/pull/480

refactor(tocco-ui): remove for tests irrelevant ThemeProvider

---

packages/resource-scheduler/package.json
packages/resource-scheduler/yarn.lock

refactor(resource-scheduler): update split pane package

---

.travis.yml
packages/tocco-ui/src/EditableValue/typeEditors/PhoneEdit.js
packages/tocco-ui/src/EditableValue/typeEditors/PhoneEdit.spec.js
packages/tocco-ui/src/FormattedValue/typeFormatters/PhoneFormatter.js
packages/tocco-ui/src/FormattedValue/typeFormatters/PhoneFormatter.spec.js

Load libphonenumber-js async to reduce bundle size in initial loading

feat(tocco-ui): load libphonenumber-js async

---

README.md

- remove saucelabs
- add read the docs

chore: update readme badges

---

packages/login/README.md
packages/login/src/dev/login_input.json
packages/login/src/main.js
packages/login/src/modules/passwordRequest/actions.js
packages/login/src/modules/passwordRequest/index.js
packages/login/src/modules/passwordRequest/reducer.js
packages/login/src/modules/passwordRequest/sagas.js
packages/login/src/modules/passwordRequest/sagas.spec.js
packages/login/src/modules/reducers.js

If passwordRequest parameter is provided the PasswordRequestContainer
is rendered and set with the content of passwordRequest.

feat(login): add request password parameter

---

packages/login/src/components/LoginForm/LoginForm.js
packages/login/src/components/LoginForm/LoginForm.spec.js

set focus on empty LoginForm input if username is provided

feat(tocco-ui): focus empty LoginForm input

---

packages/entity-list/src/util/formattedValueFactory.js

- this needs to be adjusted due to paths refactoring. PR: #602

fix(entity-list): use path with id fallback in formattedValueFactory

---

package.json
packages/app-extensions/src/errorLogging/README.md
packages/app-extensions/src/errorLogging/errorLogging.stories.js
packages/app-extensions/src/errorLogging/handlerRegistry.js
packages/app-extensions/src/errorLogging/handlers/notifierHandler.js
packages/app-extensions/src/errorLogging/sagas.spec.js
packages/app-extensions/src/notifier/README.md
packages/app-extensions/src/notifier/notifier.stories.js
storybook/addons.js
yarn.lock

https://tocco.github.io/tocco-client/pr_util-stories

Util stories

---

packages/login/src/components/LoginForm/LoginForm.js
packages/login/src/components/PasswordRequest/PasswordRequest.js
packages/login/src/components/PasswordRequest/PasswordRequest.spec.js
packages/login/src/components/PasswordRequest/StyledPasswordRequest.js
packages/login/src/components/TwoStepLoginForm/StyledTwoStepLoginForm.js
packages/login/src/components/TwoStepLoginForm/TwoStepLoginForm.js
packages/login/src/components/TwoStepLoginForm/TwoStepLoginForm.spec.js
packages/login/src/components/passwordUpdate/PasswordUpdateDialog/PasswordUpdateDialog.js
packages/login/src/components/passwordUpdate/PasswordUpdateDialog/StyledPasswordUpdateDialog.js

- stretch buttons to fill row
- remove obsolete wrappers
- use component Typography

feat(login): stretch buttons and ensure typo

---

packages/app-extensions/src/actions/components/ReportSettings.spec.js
packages/app-extensions/src/actions/utils/report.spec.js
packages/entity-browser/src/routes/detail/components/EntityDetail/EntityDetail.spec.js
packages/entity-list/src/components/EntityList/EntityList.specs.js
packages/resource-scheduler/src/components/ResourceScheduler/ResourceScheduler.spec.js
packages/resource-scheduler/src/components/SearchPanel/SearchPanel.spec.js
packages/scheduler/src/components/FullCalendar/FullCalendar.js
packages/scheduler/src/components/FullCalendar/FullCalendar.spec.js
packages/scheduler/src/components/NavigationFullCalendar/NavigationFullCalendar.spec.js
packages/scheduler/src/components/Scheduler/Scheduler.spec.js
packages/sso-login/src/components/LoginBox/LoginBox.spec.js
packages/sso-login/src/components/ProviderButton/ProviderButton.spec.js
packages/sso-login/src/utils/popUp.spec.js
packages/sso-login/src/utils/providers.spec.js

fix: rename specs files to spec

---

packages/app-extensions/src/form/formDefinition.js
packages/app-extensions/src/form/formDefinition.spec.js
packages/app-extensions/src/form/index.js
packages/entity-detail/src/modules/entityDetail/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.spec.js
packages/entity-detail/src/util/api/entities.js

- location field has mapped fields (e.g. city) that needs to be added to paths array
as well.
- rename functions for consistent naming

refactor(app-extensions): form parser add location fields to paths

---

packages/tocco-ui/src/Button/Button.stories.js
packages/tocco-ui/src/Button/StyledButton.js
packages/tocco-ui/src/utilStyles/declareInteractionColors.js

- do not change color on hover
- show cursor not-allowed on hover
- add knobs to button showcase
- remove obsolete buttons from showcase

style(tocco-ui): enhance visualization of disabled state for button

---

packages/tocco-ui/src/EditableValue/typeEditors/PhoneEdit.js

- fix bug where an incorrect input (e.g. a letter) triggered an onChange call with an incorrect value
- fix initial undefined display value to avoid react controlled warning.
- update requestAnimationFrame bind to new react refs api
- disallow input if phonelib is not yet loaded
- cleanup default country state

fix(tocco-ui): resolve various PhoneEdit problems

---

README.md
package.json
packages/tocco-ui/README.md
packages/tocco-util/README.md
scripts/release-package.sh

- documentation is moved to read the docs
- fix storybook badge

docs: remove readme documentation

---

packages/app-extensions/src/formField/editableValueFactory.js
packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
packages/tocco-ui/src/EditableValue/typeEditors/StyledDateAbstract.js

- replace es5 with es6 functions in DateAbstract Component
- fix editable value coordinate valueOverwriter

fix(tocco-ui): hide DateAbstract delete Button

---

packages/app-extensions/src/form/ReduxFormFieldAdapter.js
packages/app-extensions/src/formData/FormDataContainer.js
packages/app-extensions/src/formData/FormDataContainer.spec.js
packages/app-extensions/src/formData/locations/sagas.spec.js
packages/app-extensions/src/formField/editableValueFactory.js
packages/app-extensions/src/formField/editableValueFactory.spec.js
packages/app-extensions/src/formField/formField.js
packages/app-extensions/src/formField/formattedValueFactory.js
packages/app-extensions/src/formField/formattedValueFactory.spec.js
packages/app-extensions/src/formField/typeEditable/coordinate.js
packages/app-extensions/src/formField/typeEditable/document.js
packages/app-extensions/src/formField/typeEditable/duration.js
packages/app-extensions/src/formField/typeEditable/index.js
packages/app-extensions/src/formField/typeEditable/integer.js
packages/app-extensions/src/formField/typeEditable/location.js
packages/app-extensions/src/formField/typeEditable/number.js
packages/app-extensions/src/formField/typeEditable/phone.js
packages/app-extensions/src/formField/typeEditable/remote.js
packages/app-extensions/src/formField/typeEditable/searchFilter.js
packages/app-extensions/src/formField/typeEditable/select.js
packages/tocco-ui/src/EditableValue/EditableValue.js
packages/tocco-ui/src/EditableValue/typeEditorFactory.js
packages/tocco-ui/src/EditableValue/typeEditorFactory.spec.js

- selective state mapping for each editable value type to reduce rerendering
- introduce type specific formData mapper,  options setter, value modifier and events modifier
- cleanup form building api

refactor(app-extension): optimize form building

---

packages/tocco-ui/src/EditableValue/EditableValue.stories.js
packages/tocco-ui/src/Select/Select.stories.js

- add knob to toggle readOnly
- order props alphabetically

refactor(tocco-ui): extend story of EditableValue

---

packages/tocco-ui/src/EditableValue/typeEditors/MultiSelect.js
packages/tocco-ui/src/EditableValue/typeEditors/SingleSelect.js
packages/tocco-ui/src/Select/Select.js
packages/tocco-ui/src/Upload/StyledUploadInput.js
packages/tocco-ui/src/Upload/UploadInput.js

- add openMenuOnClick prop to SingleSelect/MultiSelect
- add readOnly prop to Select story
- add readOnly prop and styles to UploadInput

fix(tocco-ui): add Select and Upload usability fixes

---

packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js

- add tests to location, phone, url

feat(tocco-ui): add hide links on readOnly

---

package.json
scripts/helpers.sh
yarn.lock

- improve changelog script to lookup dev dependencies of a package and
collect changelog messages of them as well.

chore: changelog script sub-packages support

---

packages/entity-list/src/modules/list/sagas.js
packages/entity-list/src/modules/list/sagas.spec.js

Changelog: Remote advanced search list row selection bug fix

fix(entity-list): fix row click selection

---

packages/tocco-ui/src/StatedValue/StatedValue.js
packages/tocco-ui/src/StatedValue/StatedValue.stories.js
packages/tocco-ui/src/StatedValue/StyledStatedValue.js

- StatedValue can contain conten which is edtiable, temporary uneditable or never editable.
- visualize temporary state by lighter colors
- visualize mutuables by border
- visualize immutables by borderless

feat(tocco-ui): emphasize if StatedValue contains uneditable

---

packages/app-extensions/src/formData/FormDataContainer.js
packages/app-extensions/src/formData/values/actions.js
packages/app-extensions/src/formData/values/sagas.js
packages/app-extensions/src/formData/values/sagas.spec.js
packages/app-extensions/src/formField/editableValueFactory.js
packages/app-extensions/src/formField/editableValueFactory.spec.js
packages/app-extensions/src/formField/formField.js
packages/app-extensions/src/formField/typeEditable/index.js
packages/app-extensions/src/formField/typeEditable/location.js
packages/entity-detail/src/components/DetailForm/DetailForm.js
packages/entity-detail/src/components/DetailForm/DetailForm.spec.js
packages/entity-detail/src/containers/DetailFormContainer.js
packages/entity-detail/src/modules/entityDetail/actions.js
packages/entity-detail/src/modules/entityDetail/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.spec.js

- Move from value field. This allows to get formDatas in
FormField as well

refactor(app-extensions): move type handler to formField

---

packages/tocco-ui/src/FormattedValue/typeFormatters/DocumentCompactFormatter.js

- Same as with reports or Document add download query param

fix(tocco-ui): fix download for DocumentCompactFormatter

---

packages/entity-browser/src/routes/detail/components/EntityDetail/EntityDetail.js
packages/entity-detail/src/components/DetailForm/DetailForm.js
packages/entity-list/src/components/SearchForm/SearchForm.js

- add selectors to DetailForm and SearchForm

feat(entity-browser): add cypress selectors to entity-browser

---

packages/app-extensions/src/formField/defaultMapping.js
packages/app-extensions/src/formField/typeEditable/index.js
packages/app-extensions/src/formField/typeEditable/moneyamount.js
packages/tocco-ui/src/EditableValue/EditableValue.stories.js
packages/tocco-ui/src/EditableValue/typeEditors/NumberEdit.js
packages/tocco-ui/src/EditableValue/typeEditors/NumberEdit.spec.js

- add typeEditable moneyamount
- map moneyamount to type moneyamount in editableValueFactory

refactor(tocco-ui): set 2 decimalpoints to money component

---

packages/tocco-ui/src/Panel/PanelBody.js

refactor(tocco-ui): fix panel resize calculations

---

packages/app-extensions/src/formField/typeEditable/moneyamount.js

refactor(app-extensions): set fixedDecimalScale to boolean

---

packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js

refactor(tocco-ui): set altInput after flatpickr is loaded

---

packages/tocco-ui/src/Panel/Panel.js
packages/tocco-ui/src/Panel/Panel.stories.js
packages/tocco-ui/src/Panel/PanelGroup.js
packages/tocco-ui/src/Panel/StyledPanelBody.js
packages/tocco-ui/src/Panel/StyledPanelGroup.js
packages/tocco-ui/src/Panel/index.js

- group panels to ensure that only one is open at the same time
- define a panel which is initially opened
Refs: WEB-120

feat(tocco-ui): establish PanelGroup

---

packages/app-extensions/src/form/reduxForm.js
packages/app-extensions/src/form/reduxForm.spec.js

- reduceInitialValue makes sure there are only the relevant
attributes in formValues so redux-form's dirty selector can compare
actual changes
Refs: TOCDEV-468

feat(entity-detail): add reduceInitialValue method

---

packages/sso-login/README.md
packages/sso-login/src/components/LoginBox/LoginBox.js
packages/sso-login/src/components/LoginBox/LoginBox.spec.js
packages/sso-login/src/components/ProviderButton/ProviderButton.js
packages/sso-login/src/containers/LoginBoxContainer.js
packages/sso-login/src/dev/input.json
packages/sso-login/src/utils/loginWindow.js

add possibility to pass an optional "autoLogin" parameter. if this parameter
is set, the login process is automatically started as soon as the providers
are loaded.

feat(sso-login): add automatic initialisation of login windows

---

packages/tocco-ui/src/Button/StyledButton.js
packages/tocco-ui/src/Upload/StyledUploadProgress.js

Changelog: center icon of button

refactor(tocco-ui): center icon of button

---

packages/app-extensions/src/formData/searchFilters/sagas.js
packages/resource-scheduler/changelog.md
packages/resource-scheduler/package.json

- there was a mismatch between fetch (fields) and the value extraction (paths)
Changelog: Fix filter bug
Refs: TOCDEV-980

fix(app-extensions): filter bug, retrieve unique_id with paths

---

packages/resource-scheduler/src/containers/SchedulerAppContainer.js
packages/resource-scheduler/src/modules/resourceScheduler/actions.js
packages/resource-scheduler/src/modules/resourceScheduler/reducer.js
packages/scheduler/README.md
packages/scheduler/src/components/FullCalendar/FullCalendar.js
packages/scheduler/src/components/FullCalendar/FullCalendar.spec.js
packages/scheduler/src/components/FullCalendar/StyledFullCalendar.js
packages/scheduler/src/components/Scheduler/Scheduler.js
packages/scheduler/src/containers/SchedulerContainer.js
packages/scheduler/src/main.js
packages/scheduler/src/modules/scheduler/actions.js
packages/scheduler/src/modules/scheduler/sagas.js
packages/scheduler/src/modules/scheduler/sagas.spec.js

- Replace buttons with checkboxes to match list
Changelog: Add deselect all button
Refs: TOCDEV-983

feat(resource-scheduler): add deselect all button

---

packages/scheduler/package.json
packages/scheduler/src/components/FullCalendar/FullCalendar.js
packages/scheduler/src/components/FullCalendar/FullCalendar.spec.js
packages/scheduler/src/components/FullCalendar/StyledFullCalendar.js
packages/scheduler/src/components/NavigationFullCalendar/NavigationFullCalendar.js
packages/scheduler/yarn.lock

Changelog: Update fullcalendar

refactor(scheduler): update fullcalendar

---

packages/app-extensions/src/formData/relationEntities/sagas.js

- the value must be the same and needs the model field
Refs: TOCDEV-468

refactor(app-extension): select fields show undo changes not as dirty

---

packages/scheduler/package.json
packages/scheduler/src/components/FullCalendar/FullCalendar.js
packages/scheduler/src/components/FullCalendar/StyledFullCalendar.js
packages/scheduler/src/components/NavigationFullCalendar/NavigationFullCalendar.js
packages/scheduler/src/utils/time.js
packages/scheduler/src/utils/time.spec.js
packages/scheduler/yarn.lock

- add custom views with custom date formatters
- make font size smaller
- fix resizing by adding plugin
- add min and max time (6-23:00)

refactor(scheduler): ui adjustments

---

packages/entity-list/src/components/PaginationPanel/PaginationPanel.js
packages/entity-list/src/components/PaginationPanel/StyledPaginationPanel.js

Refs: TOCDEV-975
Changelog: Pagination positioning to the right

refactor(list): pagination positioning to the right

---

packages/admin/src/routes/entities/components/CreateView/CreateViewContainer.js
packages/admin/src/routes/entities/components/DetailView/DetaiViewContainer.js
packages/admin/src/routes/entities/components/EditView/EditViewContainer.js
packages/admin/src/routes/entities/components/ListView/ListView.js
packages/admin/src/routes/entities/components/ListView/ListViewContainer.js
packages/admin/src/routes/entities/components/RelationsView/RelationViewContainer.js
packages/admin/src/routes/entities/modules/path/actions.js
packages/admin/src/routes/entities/modules/path/reducer.js
packages/admin/src/routes/entities/modules/path/sagas.js

refactor(admin): fix bug where currentViewInfos initially was outdated

---

packages/app-extensions/src/actions/actionComponentTypes.js
packages/app-extensions/src/actions/components/Action.js
packages/app-extensions/src/actions/components/Action.spec.js

- first primitive support without visual effects

refactor(app-extensions): action-bar support

---

packages/login/src/components/LoginForm/LoginForm.js
packages/login/src/components/PasswordRequest/PasswordRequest.js
packages/login/src/components/StyledLoginForm.js
packages/login/src/components/TwoStepLoginForm/TwoStepLoginForm.js
packages/login/src/components/passwordUpdate/PasswordUpdateDialog/PasswordUpdateDialog.js
packages/login/src/components/passwordUpdate/PasswordUpdateDialog/PasswordUpdateDialog.spec.js

Refs: TOCDEV-1075
Changelog: Style Login

refactor(login): style missing buttons

---

packages/admin/src/routes/entities/components/RelationsView/StyledComponents.js

Refs: TOCDEV-1167
Changelog: style relations view

refactor(admin): style relations view

---

packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
packages/entity-list/src/components/AdminSearchForm/AdminSearchFormContainer.js
packages/entity-list/src/components/AdminSearchForm/StyedComponents.js
packages/entity-list/src/components/BasicSearchForm/BasicSearchForm.js
packages/entity-list/src/components/BasicSearchForm/BasicSearchForm.spec.js
packages/entity-list/src/modules/searchForm/sagas.js
packages/entity-list/src/modules/searchForm/sagas.spec.js

- replace reset button in admin search form
Changelog: Rearrange search form buttons
Refs: TOCDEV-1282

refactor(entity-list): rearrange search form buttons

---

packages/admin/src/routes/entities/components/RelationsView/StyledComponents.js

refactor(admin): fix icon sizing in relation box

---

packages/entity-list/src/components/AdminSearchForm/StyedComponents.js

refactor(entity-list): remove box sizing reset

---

packages/entity-list/src/modules/list/sagas.js
packages/entity-list/src/modules/list/sagas.spec.js

- if form nas no explicit sorting, a default sorting is used.
- refactoring tests
Refs: TOCDEV-1143

refactor(entity-list): fallback sorting last_updated

---

packages/resource-scheduler/src/components/ResourceScheduler/ResourceScheduler.js

refactor(resource-scheduler): adjust max height

---

packages/tocco-ui/src/Layout/StyledLayoutBox.js

Refs: TOCDEV-1467
Changelog: adjust responive behavior of layout box in detail view

refactor(tocco-ui): adjust column width rendition of layout

---

packages/admin/src/routes/entities/components/RelationsView/StyledComponents.js

Refs: TOCDEV-1565
Changelog: add hover color to relations buttons

refactor(admin): add hover color to relations buttons

---

packages/tocco-ui/src/FormattedValue/typeFormatters/HtmlFormatter.js

Refs: TOCDEV-1525
Changelog: style display expression in debitoren table

refactor(tocco-ui): remove backgroundcolor in display expressions

---

packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
packages/entity-list/src/components/AdminSearchForm/StyedComponents.js
packages/entity-list/src/components/SearchFilterList/SearchFilterList.js

- add expand button
Refs: TOCDEV-1341
Changelog: Adjust search-filter size automatically

refactor(admin): adjust search-filter size automatically

---

packages/entity-list/src/components/SelectionController/StyledSelectionController.js

refactor(entity-list): harmonize button spacing and hover

---

packages/entity-list/src/components/SearchFilterList/SearchFilterList.js

Refs: TOCDEV-1559
Changelog: crop search filter text with ellipsis

refactor(entity-list): crop search filter text accordingly

---

server/main.js

If a /nice2/* request reaches the dev server because it wasn't mocked,
it's probably better to let the Nice2 instance (which is probably
running on http://localhost:8080) answer the request, instead of
returning the index.html.

chore: pipe some requests through to Nice2 instance in dev server

---

packages/tocco-ui/src/Menu/StyledMenuStack.js
packages/tocco-ui/src/utilStyles/interactiveStyling.js

Refs: TOCDEV-1562
Changelog: style button dropdown list

refactor(tocco-ui): style button dropdown list

---

packages/app-extensions/src/rest/helpers.js
packages/entity-browser/src/dev/input-no-mock.json
packages/entity-list/src/modules/list/actions.js
packages/entity-list/src/modules/list/reducer.js
packages/entity-list/src/modules/list/reducer.spec.js
packages/entity-list/src/modules/list/sagas.js
packages/entity-list/src/modules/list/sagas.spec.js
packages/entity-list/src/util/api/forms.js
packages/entity-list/src/util/api/forms.spec.js
packages/tocco-util/src/mockData/data/user_list_small_form.json

Refs: TOCDEV-1545
Changelog: Constriction handling

feat(entity-list): extract constriction from form and pass along

---

packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.spec.js
server/index.html
server/main.js
server/static/nice_legacy_actions_setup.js

Now the sources are loaded when the legacy action handler is invoked
for the first time. As each file depends on the prior file we have
to load them sequentially.

refactor(app-extensions): load legacy action sources async when needed

---

packages/admin/src/components/Login/Login.js

Refs: TOCDEV-1600
Changelog: minimize login form dimensions

refactor(admin): harmonize spacing

---

package.json
packages/admin/src/components/Login/Login.js
packages/admin/src/components/Login/LoginContainer.js
packages/admin/src/main.js
packages/admin/src/modules/session/actions.js
packages/admin/src/modules/session/reducer.js
packages/admin/src/modules/session/sagas.js
yarn.lock

- add sso-login response handler
- only show sso if module is installed
Refs: TOCDEV-1246

feat(admin): fully integrate sso login

---

packages/admin/src/components/Navigation/Navigation.js

Refs: TOCDEV-1281
Changelog: Arrow navigation

feat(admin): add arrow key navigation support to Navigation

---

packages/tocco-ui/src/StatedValue/StyledStatedValue.js

Refs: TOCDEV-1602
Changelog: harmonize stateted value box padding

refactor(tocco-ui): harmonize stateted value box padding

---

packages/tocco-ui/src/EditableValue/EditableValue.stories.js
packages/tocco-ui/src/EditableValue/typeEditors/NumberEdit.js
packages/tocco-ui/src/EditableValue/typeEditors/NumberEdit.spec.js

- allow definition of suffix and prefix
- debounce component

feat(tocco-ui): expand NumberEdit

---

packages/tocco-ui/src/StatedValue/StyledStatedValue.js

refactor(tocco-ui): harmonize styled stated value spacing

---

package.json
packages/tocco-ui/src/Panel/PanelBody.js
packages/tocco-ui/src/Panel/StyledPanelBody.js
packages/tocco-ui/src/Panel/index.js
yarn.lock

- remove dom observer and resize handler
- introduce animation lib
- fix nice 2 compatibility bug (TOCDEV-1323)
Refs: TOCDEV-1323
Changelog: Panel animation refactoring

refactor(tocco-ui): change panel animation

---

packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js

feat(app-extension): support action properties in legacy actions

---

packages/tocco-ui/src/FormattedValue/typeFormatters/HtmlFormatter.js

Refs: TOCDEV-1645
Changeole: reset nice2 default expression alignment

refactor(tocco-ui): reset nice2 padding

---

packages/admin/src/components/Admin/Admin.js
packages/admin/src/components/Admin/StyledComponents.js
packages/tocco-ui/src/BurgerButton/BurgerButton.js
packages/tocco-ui/src/BurgerButton/BurgerButton.stories.js
packages/tocco-ui/src/BurgerButton/index.js
packages/tocco-ui/src/index.js

- use in Admin
Changelog: Animate burger icon

feat(tocco-ui): introduce animated burger icon

---

packages/tocco-ui/package.json
packages/tocco-ui/src/Popover/Popover.js
packages/tocco-ui/src/Popover/Popover.stories.js
packages/tocco-ui/yarn.lock

- update react popper
Refs: TOCDEV-1145

refactor(tocco-ui): disable popover outside body

---

packages/admin/src/components/Login/Login.js

refactor(admin): align sso message in center

---

packages/app-extensions/src/actions/components/ReportSettings.js
packages/app-extensions/src/actions/components/StyledReportSettings.js
packages/app-extensions/src/formData/advancedSearch/AdvancedSearch.js
packages/app-extensions/src/formData/advancedSearch/StyledAdvancedSearch.js
packages/app-extensions/src/notifier/components/StyledNotifier.js
packages/app-extensions/src/notifier/components/TitleMessage.js
packages/app-extensions/src/notifier/components/TitleMessage.spec.js
packages/app-extensions/src/notifier/modules/modalComponents/StyledModalContent.js

Refs: TOCDEV-1335
Changelog: improve modal ux

refactor(app-extensions): improve modal ux

---

packages/tocco-theme/src/ToccoTheme/defaultTheme.js

Refs: TOCDEV-1630
Changelog: adapt success color for better readability

refactor(tocco-theme): adapt success color for readability

---

packages/app-extensions/src/notifier/components/TitleMessage.js
packages/app-extensions/src/notifier/modules/modalComponents/ModalButtons.js
packages/app-extensions/src/notifier/modules/modalComponents/StyledModalContent.js

refactor(app-extensions): fix modal positioning and harmonize spacing

---

packages/tocco-ui/src/SearchBox/StyledSearchBox.js

refactor(tocco-ui): harmonize search box spacing

---

packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.spec.js

Refs: TOCDEV-1696
Changelog: Small date component improvements

refactor(tocco-ui): dont call onChange if nothing changed

---

packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
packages/tocco-ui/src/EditableValue/typeEditors/StyledDateAbstract.js
packages/tocco-ui/src/Range/Range.js
packages/tocco-ui/src/Range/StyledRange.js

Refs: TOCDEV-1729
Changelog: improve range style

refactor(tocco-ui): improve range style

---

packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.spec.js

- The notifier that is used in the legacy actions setup allows to
register a callback that is called whenever a notification should
be displayed.
- Depends on https://git.tocco.ch/c/nice2/+/36601
Refs: TOCDEV-1698

feat(app-extensions): Use new client notifications in legacy actions

---

packages/scheduler/src/components/FullCalendar/FullCalendar.js
packages/scheduler/src/components/NavigationFullCalendar/NavigationFullCalendar.js

Refs: TOCDEV-951
Changelog: Add simplified week view

refactor(scheduler): add second week view

---

packages/login/src/modules/sagas.js

- due to refactoring those two parameters were ignored
Changelog: Fix two-factor authentication bug

fix(login): send two factor params to backend

---

packages/app-extensions/src/formData/searchFilters/sagas.js
packages/app-extensions/src/formData/searchFilters/sagas.spec.js
packages/app-extensions/src/formData/searchFilters/utils.js
packages/app-extensions/src/formData/searchFilters/utils.spec.js

* check for url in tests as well

feat(app-extensions): use new search filter endpoint

---

packages/entity-list/src/components/SearchFilterList/SearchFilterList.js

refactor(entity-list): re-add hover effect

---

packages/login/src/components/StyledLoginForm.js
packages/login/src/components/TwoStepLoginForm/StyledTwoStepLoginForm.js
packages/login/src/components/passwordUpdate/PasswordUpdateDialog/StyledPasswordUpdateDialog.js

refactor(login): correct button span width

---

packages/admin/src/routes/entities/components/RelationsView/RelationsView.js
packages/admin/src/routes/entities/components/RelationsView/StyledComponents.js

Refs: TOCDEV-1884
Changelog: harmonize icon spacing in preview box

refactor(admin): harmonize icon spacing

---

packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json

add file icons that may be used for different report types

---

packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.spec.js

The actions could be fixed by including the CKEDITOR (wysiwyg editor).
Refs: TOCDEV-1900

fix(app-extensions): fix mail and correspondence legacy actions

---

packages/admin/src/routes/dashboard/components/Dashboard/Dashboard.js

Refs: TOCDEV-1467
Changelog: make welcome screen responsive

refactor(admin): make welcome screen responsive

---

packages/tocco-util/src/tqlBuilder/tqlBuilder.js
packages/tocco-util/src/tqlBuilder/tqlBuilder.spec.js

fix(entity-list): fix fulltext search

---

packages/resource-scheduler/src/components/SearchPanel/SearchPanel.js

refactor(resource-scheduler): hide actions in search

---

packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.spec.js

Depends on change in backend: https://git.tocco.ch/c/nice2/+/36935
Refs: TOCDEV-1798

feat(app-extensions): support multiple filters for legacy actions

---

packages/app-extensions/src/notifier/components/StyledNotifier.js

refactor(app-extensions): reduce z-index of modal

---

packages/app-extensions/src/notifier/components/TitleMessage.js
packages/app-extensions/src/notifier/modules/modalComponents/ModalContent.js
packages/app-extensions/src/notifier/modules/modalComponents/ModalDisplay.js
packages/app-extensions/src/notifier/modules/modalComponents/StyledModalContent.js

refactor(app-extensions): resolve visual overlapping of components

---

packages/entity-list/src/components/Table/StyledTable.js

Refs: TOCDEV-1731
Changelog: adjust table padding and table heading hover

refactor(entity-list): adjust table padding and th hover

---

packages/entity-list/src/components/EntityList/StyledComponents.js

Refs: TOCDEV-2038
Changelog: slim down left panel width in entity list view

refactor(entity-list): change left panel width

---

packages/entity-list/src/components/AdminSearchForm/StyedComponents.js
packages/entity-list/src/components/Table/StyledTable.js

Refs: TOCDEV-1581
Changelog: mitigate unwanted legacy action loading effects

refactor(entity-list): mitigate unwanted legacy action loading effects

---

packages/app-extensions/src/notifier/components/StyledNotifier.js

Refs: TOCDEV-2088
Changelog: harmonize notification spacing

refactor(app-extensions): harmonize notification spacing

---

packages/entity-list/src/components/ListView/ListView.js
packages/entity-list/src/util/api/forms.js

do not display reverse relation when showing entity-list as subtable

---

package.json
packages/tocco-ui/package.json
packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
yarn.lock

- Add legacy icons to support nice display expressions (white listing of used icons)
- Update font awesome
Refs: TOCDEV-921
Changelog: Add legacy icons

refactor(tocco-ui): icons update

---

packages/tocco-ui/src/FormattedValue/typeFormatters/DescriptionFormatter.js

Refs: TOCDEV-2076
Changelog: harmonize question icon size/spacing in detail view

refactor(tocco-ui): harmonize question icon size/spacing

---

packages/tocco-util/src/tqlBuilder/tqlBuilder.js
packages/tocco-util/src/tqlBuilder/tqlBuilder.spec.js

rebuild fulltext search handling from old client

---

packages/app-extensions/src/form/FormBuilder.js
packages/app-extensions/src/form/FormBuilder.spec.js

refactor(app-extension): read multi path entity fields

---

packages/admin/src/modules/session/sagas.js

Refs: TOCDEV-1972
Changelog: Delete sso cookie on logout

refactor(admin): delete sso cookie on logout

---

packages/tocco-ui/package.json
packages/tocco-ui/src/EditableValue/typeEditors/HtmlEdit.js
packages/tocco-ui/yarn.lock

- update react quill
- use react to show read only html since quills rendering is not that good and this change
automatically fixes the update bug (see Refs)
Refs: TOCDEV-2067
Changelog: Adjust HTML Edit

refactor(tocco-ui): adjust html edit

---

packages/admin/src/routes/entities/components/Action/actions/ShowOutputJobsAction.js

The problem described in TOCDEV-2080 doesn't occur anymore.
It has been fixed with TOCDEV-1939.
Refs: TOCDEV-2080, TOCDEV-2075

fix(admin): remove unnecessary timeout in ShowOutputJobsAction

---

packages/tocco-util/src/tqlBuilder/tqlBuilder.js
packages/tocco-util/src/tqlBuilder/tqlBuilder.spec.js

- without the implemented check a deleted value (has value of empty string) would be handled and result in an error
since it can not be parsed to date etc.
Refs: TOCDEV-1762

refactor(tocco-util): improve undefined value handling for ranges

---

cypress/integration/entitybrowser_spec.js
package.json
packages/app-extensions/src/actions/components/ActionGroup.js
packages/entity-list/src/components/Table/ResizingController.js
yarn.lock

- add selectors
- fix failing test

refactor: fix and update cypress test

---

packages/admin/src/routes/entities/components/RelationsView/StyledComponents.js

Refs: TOCDEV-2072
Changelog: Harmonize relations view spacing

refactor(admin): harmonize relations view spacing

---

packages/app-extensions/src/notifier/components/StyledNotifier.js

Refs: TOCDEV-2122
Changelog: Reposition notifier close icon

refactor(app-extensions): reposition notifier close icon

---

packages/app-extensions/src/notifier/modules/modalComponents/StyledModalContent.js
packages/login/src/components/passwordUpdate/PasswordUpdateDialog/StyledPasswordInput.js
packages/tocco-ui/src/EditableValue/typeEditors/StyledPhoneEdit.js
packages/tocco-ui/src/EditableValue/typeEditors/StyledStringEdit.js
packages/tocco-ui/src/EditableValue/typeEditors/StyledTimeEdit.js
packages/tocco-ui/src/EditableValue/typeEditors/StyledUrlEdit.js
packages/tocco-ui/src/SearchBox/StyledSearchBox.js

chore: replace depreceated attrs functions

---

packages/tocco-ui/src/Button/StyledButton.js

Refs: TOCDEV-2190
Changelog: Fix icon positioning within buttons

refactor(tocco-ui): fix button icon positioning

---

packages/admin/src/routes/entities/modules/path/sagas.js

refactor(admin): adjust relation count to new endpoint

---

packages/app-extensions/src/form/FormBuilder.js

refactor(app-extensions): refactor FormBuilder.js

---

packages/input-edit/src/components/InputEdit/InputEdit.js
packages/input-edit/src/components/InputEdit/StyledInputEdit.js

Refs: TOCDEV-2257
Changelog: Add vertical scrolling to input edit table

refactor(input-edit): add vertical scrolling to input edit

---

packages/entity-list/src/components/Table/StyledTable.js

Refs: TOCDEV-2226
Changelog: Adjust minimum height of table content to 300px

refactor(entity-list): adjust minimum table height

---

packages/entity-list/src/components/Table/StyledTable.js

Refs: TOCDEV-2246
Changelog: Style kabob menu inside table header

refactor(entity-list): style reset button in table

---

packages/entity-list/src/components/SearchFilterList/SearchFilterList.js

Refs: TOCDEV-2287
Changelog: Center search filter icon vertically

refactor(entity-list): center search filter icon

---

packages/tocco-ui/src/Ball/StyledBall.js

Refs: TOCDEV-2291
Changelog: Fix sizing of ball

refactor(tocco-ui): fix box-sizing of ball

---

packages/entity-list/src/components/Table/NavigationCellHeader.js
packages/entity-list/src/modules/preferences/actions.js
packages/entity-list/src/modules/preferences/reducer.js
packages/entity-list/src/modules/preferences/sagas.js
packages/entity-list/src/modules/preferences/sagas.spec.js

Refs: TOCDEV-2058
Changelog: Added button to reset all preferences

feat(entity-list): add button to reset all preferences

---

packages/app-extensions/src/form/FormBuilder.js
packages/app-extensions/src/form/FormBuilder.spec.js
packages/app-extensions/src/form/ReduxFormFieldAdapter.js
packages/app-extensions/src/formField/formField.js
packages/simple-form/src/components/Form/Form.js

- pass readonly value down to children
Refs: TOCDEV-2245
Changelog: Make all children of readonly layouts readonly

feat(app-extensions): handle readonly layouts in forms

---

packages/tocco-ui/src/StatedValue/StyledStatedValue.js
packages/tocco-ui/src/utilStyles/colorMap.js
packages/tocco-ui/src/utilStyles/colorMap.spec.js

Refs: TOCDEV-2312
Changelog: Style input fields according to material design

refactor(tocco-ui): style stated value label and box

---

packages/tocco-ui/src/Table/StyledTable.js

Refs: TOCDEV-2351
Changelog:  Style draggable table headers and kabob menu

refactor(tocco-ui): style draggable th and kabob

---

packages/admin/src/routes/entities/components/RelationsView/RelationViewContainer.js
packages/admin/src/routes/entities/components/RelationsView/RelationsView.js
packages/admin/src/routes/entities/modules/path/actions.js
packages/admin/src/routes/entities/modules/path/reducer.js
packages/admin/src/routes/entities/modules/path/sagas.js

refactor(admin): show relation create button conditionally

---

packages/resource-scheduler/src/components/ResourceScheduler/ResourceScheduler.js
packages/resource-scheduler/src/components/ResourceScheduler/ResourceScheduler.spec.js
packages/resource-scheduler/src/containers/ResourceSchedulerContainer.js
packages/resource-scheduler/src/main.js

Changelog: Fix admin resource scheduler bug

refactor(resource-scheduler): fix no action proptypes bug

---

packages/admin/src/components/AboutTocco/AboutTocco.js
packages/admin/src/components/AboutTocco/AboutToccoContainer.js
packages/admin/src/components/AboutTocco/index.js
packages/admin/src/components/Header/Header.js
packages/admin/src/components/Header/HeaderContainer.js
packages/tocco-ui/src/Menu/Menu.js

Refs: TOCDEV-1447
Changelog: Add admin help menu

feat(admin): add help menu

---

packages/admin/src/components/Admin/StyledComponents.js

Refs: TOCDEV-2418
Changelog: Align bm button menu with content

refactor(admin): algin bm button

---

packages/admin/src/components/Header/Header.js

Refs: TOCDEV-2431
Changelog: Change header ball menu icon to info symbol

refactor(admin): change header ball menu icon

---

packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
packages/entity-list/src/components/AdminSearchForm/StyedComponents.js

Refs: TOCDEV-2403
Changelog: Style draggable gutter for more usability and design consistency

refactor(entity-list): style gutter for more usability

---

packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
packages/entity-list/src/components/AdminSearchForm/StyedComponents.js

Refs: TOCDEV-2403
Changelog: Adjust gutter height in admin search form

refactor(entity-list): adjust gutter height

---

packages/admin/src/components/ErrorView/ErrorView.js

Refs: TOCDEV-2325
Changelog: Style error view

refactor(admin): style error view

---

packages/entity-list/src/components/SearchFilterList/SearchFilterList.js

Refs: TOCDEV-2441
Changelog: Display search filter button only on hover - else hide

refactor(entity-list): hide search filter button

---

packages/admin/src/components/Header/Header.js

Refs: TOCDEV-2431
Changelog: Change help menu icon

refactor(admin): change header ball icon

---

packages/tocco-ui/package.json
packages/tocco-ui/src/Select/DropdownIndicator.js
packages/tocco-ui/src/Select/StyledReactSelect.js

- update react-select
Refs: TOCDEV-2415

refactor(tocco-ui): instantly open dropdown on indicator click

---

packages/admin/src/routes/entities/components/ActionView/ActionView.js
packages/entity-browser/changelog.md
packages/entity-browser/package.json

- to stop it from rerendering on menu open/close
Refs: TOCDEV-2297

refactor(admin): wrap action view with memo

---

packages/admin/src/components/ErrorView/ErrorView.js

Refs: TOCDEV-2325
Changelog: Change error view background and icon size

refactor(admin): change error view style

---

packages/tocco-ui/src/Table/StyledTable.js

refactor(tocco-ui): disable hover on navigation cell

---

packages/input-edit/src/components/InputEdit/StyledInputEdit.js

Refs: TOCDEV-2290
Changelog: Narrow left panel width of input edit

refactor(input-edit): narrow left panel width

---

packages/entity-list/src/components/ColumnPicker/ColumnPicker.js
packages/entity-list/src/components/ColumnPicker/StyledColumnPicker.js

Refs: TOCDEV-2437
Changelog: Style column picker dialog inside modal

refactor(entity-list): style column picker

---

packages/entity-list/src/components/ColumnPicker/StyledColumnPicker.js

refactor(entity-list): reset nice2 overwrite in ColumnPicker

---

packages/app-extensions/src/keyDown/Components/KeyDownWatcher/KeyDownWatcher.js

refactor(app-extensions): fix display in safari

---

packages/tocco-ui/src/Preview/Preview.js
packages/tocco-ui/src/Preview/Preview.spec.js
packages/tocco-ui/src/Preview/StyledPreview.js
packages/tocco-ui/src/Upload/Upload.js
packages/tocco-ui/src/Upload/UploadInput.js

Refs: TOCDEV-2420
Changelog: Reset css overwrites of Upload.js and refactor Preview.js

refactor(tocco-ui): refactor preview and upload

---

packages/app-extensions/src/notifier/modules/modalComponents/StyledModalContent.js

Refs: TOCDEV-2013
Changelog: Set min and max width for modal

refactor(app-extensions): restrict modal width

---

packages/admin/src/routes/entities/components/RelationsView/RelationViewContainer.js
packages/admin/src/routes/entities/components/RelationsView/RelationsView.js

refactor(admin): pass emit action to relation list

---

packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js

Refs: TOCDEV-2440
Changelog: Adjust filter pane height when expanded

refactor(entity-list): adjust filter height

---

packages/entity-browser/src/routes/entity-browser/components/EntityBrowser/EntityBrowser.js

refactor(entity-browser): refactor entity browser

---

packages/entity-list/src/components/FullTextSearchForm/FullTextSearchForm.js

refactor(entity-list): refactor fullTextSearchForm.js

---

packages/tocco-ui/src/Select/DropdownIndicator.js

Refs: TOCDEV-2627
Changelog: Change chevron icon in multi select input when dropdown is opened

refactor(tocco-ui): change icon on dropown in select

---

packages/app-extensions/src/formData/advancedSearch/AdvancedSearch.js

refactor(app-extensions): refactor props

---

packages/admin/src/routes/entities/modules/path/sagas.js
packages/admin/src/routes/entities/modules/path/sagas.spec.js

Changelog: Fix create reverse relation
Refs: TOCDEV-2639

fix(admin): set reverse relation on create

---

packages/tocco-ui/package.json
packages/tocco-ui/src/Select/Select.js
packages/tocco-ui/yarn.lock

- update react-select
- refactor to functional component
- open menu on click despite of the openMenuOnClick property, if focus is already on select.
Changelog: Open remote fields on second click
Refs: TOCDEV-2415

refactor(tocco-ui): improve Select

---

packages/entity-detail/src/components/DetailForm/DetailForm.js
packages/entity-detail/src/components/DetailForm/SaveButton.js
packages/entity-detail/src/components/ErrorBox/ErrorBox.js
packages/entity-detail/src/components/ErrorBox/ErrorBox.spec.js
packages/entity-detail/src/containers/DetailFormContainer.js
packages/entity-detail/src/modules/entityDetail/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.spec.js

- Move error-box to save buttomn
- show validation errors in toaster
Refs: TOCDEV-2581, TOCDEV-2582
Changelog: Improve form error notification

refactor(entity-detail): improve form error notifications

---

packages/admin/src/routes/entities/components/RelationsView/StyledComponents.js

Refs: TOCDEV-2730
Changelog: Adjust relations view height for smaller screens

refactor(admin): adjust height on mobile

---

packages/tocco-ui/src/Table/StyledTable.js

Refs: TOCDEV-2739
Changelog: Increase min-width of table column for more usability on smaller screens

refactor(tocco-ui): adjust min width of table column

---

packages/tocco-ui/src/EditableValue/StyledEditableValue.js

Refs: TOCDEV-2724
Changelog: Disable touch on mobile and adjust margin

refactor(tocco-ui): prevent touch on disabled inputs

---

packages/app-extensions/src/form/index.js
packages/app-extensions/src/form/reduxForm.js
packages/app-extensions/src/form/reduxForm.spec.js
packages/entity-detail/src/modules/entityDetail/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.spec.js
packages/tocco-util/src/mockData/actions.js
packages/tocco-util/src/mockData/actions.spec.js
packages/tocco-util/src/mockData/data/user_detail_form.json

- support override and is_empty type with custom endpoint
- add mock
Refs: TOCDEV-2043
Changelog: Autocomplete support

feat(entity-detail): add autocomplete endpoint support

---

packages/app-extensions/src/rest/helpers.js
packages/app-extensions/src/rest/helpers.spec.js

- Otherwise whatever is loaded first wil be used as tooltip and default display
Refs: TOCDEV-2736

fix(app-extensions): cache displays by type

---

packages/tocco-ui/src/Select/DropdownIndicator.js
packages/tocco-ui/src/Select/IndicatorsContainer.js
packages/tocco-ui/src/Select/MenuList.js
packages/tocco-ui/src/Select/Select.js

Refs: TOCDEV-2627
Changelog: Fix select for mobile

refactor(tocco-ui): fix select for mobile devices

---

packages/entity-list/src/components/EntityList/StyledComponents.js

Refs: TOCDEV-2748
Changelog: Adjust entity list height inside detail view to scale on smaller screens

refactor(entity-list): adjust entity list height

---

packages/tocco-ui/src/Link/Link.js
packages/tocco-ui/src/Link/RouterLink.js
packages/tocco-ui/src/Link/StyledLink.js

Refs: TOCDEV-2738
Changelog: Change link colors to secondary color

refactor(tocco-ui): change link colors

---

packages/app-extensions/src/appFactory/ThemeWrapper.js

refactor(app-extensions): refactor theme wrapper

---

packages/resource-scheduler/src/components/ResourceScheduler/ResourceScheduler.js

refactor(resource-scheduler): refactor resource scheduler

---

packages/admin/src/components/LoginGuard/LoginGuard.js

refactor(admin): complement ico favicon link

---

packages/entity-list/src/components/ListView/ListView.js

fix(entity-list): do not try and display action bar if none exists

---

packages/admin/src/components/Login/Login.js
packages/admin/src/components/Login/StyledComponents.js

refactor(admin): refactor login

---

__mocks__/ResizeObserver.js
packages/app-extensions/src/notifier/components/TitleMessage.js
packages/app-extensions/src/notifier/components/TitleMessage.spec.js
packages/app-extensions/src/notifier/modules/modalComponents/ModalButtons.js
packages/app-extensions/src/notifier/modules/modalComponents/ModalContent.js
packages/app-extensions/src/notifier/modules/modalComponents/ModalContent.spec.js
packages/app-extensions/src/notifier/modules/modalComponents/ModalDisplay.spec.js
packages/app-extensions/src/notifier/modules/modalComponents/StyledModalContent.js

Refs: TOCDEV-2624
Changelog: Adjust ttile width of modal to match modal width

refactor(app-extensions): adjust title width

---

packages/admin/src/components/AboutTocco/AboutTocco.js
packages/admin/src/components/AboutTocco/StyledComponents.js
packages/admin/src/components/Login/Login.js
packages/admin/src/routes/dashboard/components/Dashboard/Dashboard.js
packages/admin/src/routes/dashboard/components/Dashboard/StyledComponents.js

Refs: TOCDEV-2803
Changelog: Set height and width attribute to allow the browser to calculate/reserve sufficient space and minimize layout shifts

refactor(admin): set width and height for img

---

packages/admin/src/routes/entities/components/RelationsView/StyledComponents.js

Refs: TOCDEV-2806
Changelog: Remove hover of relation boxes on mobile devices

refactor(admin): remove relations hover on mobile

---

packages/tocco-ui/src/Preview/Preview.js

after uploading a file the filename is shown as caption below the preview

feat(tocco-ui): add caption to preview

---

packages/app-extensions/src/notifier/components/TitleMessage.js
packages/app-extensions/src/notifier/modules/modalComponents/ModalContent.js

refactor(app-extensions): fix modal unobserve

---

packages/tocco-ui/src/Select/IndicatorsContainer.js
packages/tocco-ui/src/Select/StyledIndicatorsContainer.js
packages/tocco-ui/src/StatedValue/StatedValue.js
packages/tocco-ui/src/StatedValue/StyledStatedValue.js

Refs: TOCDEV-2811
Changelog: Prevent label overflow inside input field

refactor(tocco-ui): prevent label overflow

---

packages/tocco-ui/src/Menu/Menu.js

Refs: TOCDEV-2824
Changelog: Prevent popper menu disappearing behind main menu overlay

refactor(tocco-ui): increase popper z-index

---

packages/app-extensions/src/actions/modules/actionHandlers/report.js

Refs: TOCDEV-2732
Changelog: Fix reports without custom settings

refactor(app-extensions): only include custom settings if they exist

---

packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js

Refs: TOCDEV-2440
Changelog: Add minimal padding to search filter to avoid scrollbar on fewer entries

refactor(entity-list): add padding to search filter

---

packages/entity-list/src/util/fieldFactory.js

Refs: TOCDEV-2854
Changelog: Make whole row clickable in list

refactor(entity-list): whole row clickable

---

.gitlab-ci.yml
README.md

chore: improve gitlab ci config

---

packages/entity-list/src/components/ListView/ListView.js
packages/entity-list/src/components/ListView/ListView.spec.js

Changelog: Prevent null pointer if no action bar in form model
Refs: TOCDEV-2560

fix(entity-list): Prevent null pointer if no action bar in form model

---

packages/app-extensions/src/field/editableTypeConfigs/html.js
packages/app-extensions/src/field/editableTypeConfigs/index.js

fix(app-extensions): fix label of html fields to top

---

packages/entity-list/src/components/SearchFilterList/SearchFilterList.js
packages/entity-list/src/components/SearchFilterList/StyledComponents.js

Refs: TOCDEV-2807
Changelog: Remove hover background color on active filter buttons

refactor(entity-list): set background color

---

packages/tocco-ui/src/StatedValue/StyledStatedValue.js

Refs: TOCDEV-2839
Changelog: Add height to label to prevent vertical clip

refactor(tocco-ui): add height

---

packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
packages/tocco-ui/src/EditableValue/typeEditors/StyledDateAbstract.js

Refs: TOCDEV-2895
Changelog: Prevent click on disabled date input field

refactor(tocco-ui): prevent click on disabled

---

packages/merge/src/components/MergeTable/CellRender.js
packages/merge/src/components/MergeTable/MergeTable.js
packages/merge/src/components/MergeTable/Selection.js
packages/merge/src/dev/data/sourceResponse.json
packages/merge/src/modules/merge/actions.js
packages/merge/src/modules/merge/reducer.js
packages/merge/src/modules/merge/reducer.spec.js
packages/merge/src/modules/merge/sagas.js
packages/merge/src/modules/merge/sagas.spec.js
packages/merge/src/util/sourceData.js
packages/merge/src/util/sourceData.spec.js

- add logic for radio button and checkbox
- add set target entity functionality
- call merge action endpoint
Refs: TOCDEV-2743

refactor(merge): merge v2 selection

---

.gitlab-ci.yml
deployment/storybook_link_gitlab.sh

- only comment url if not already done
- improve caching

chore: ci script improvements

---

packages/app-extensions/src/notifier/modules/modalComponents/ModalContent.js

Refs: TOCDEV-2628
Changelog: Prevent mobile keyboard from pushing the modal up

refactor(app-extensions): fix modal on mobile

---

packages/app-extensions/src/notifier/components/StyledTitleMessage.js
packages/app-extensions/src/notifier/modules/modalComponents/StyledComponents.js

Refs: TOCDEV-2959
Changelog: Fix top padding of modal

refactor(app-extensions): fix modal padding

---

packages/tocco-ui/src/StatedValue/StyledStatedValue.js

Refs: TOCDEV-2838
Changelog: Fix padding of immutable stated values

refactor(tocco-ui): fix padding

---

packages/tocco-ui/src/StatedValue/StatedValue.spec.js
packages/tocco-ui/src/StatedValue/StyledStatedValue.js

chore: fix StatedValue.js tests

---

packages/entity-detail/src/components/ErrorItems/ErrorItems.js

Refs: TOCDEV-2735
Changelog: Change the text format if there are only fieldErrors

refactor(entity-detail): refactor ErrorItems.js

---

packages/admin/src/components/Breadcrumbs/StyledBreadcrumbs.js
packages/admin/src/routes/entities/components/RelationsView/StyledComponents.js
packages/tocco-ui/src/Menu/ButtonMenu.js
packages/tocco-ui/src/Menu/ButtonMenu.spec.js
packages/tocco-ui/src/Menu/Menu.js
packages/tocco-ui/src/Menu/MenuItem.js
packages/tocco-ui/src/Menu/StyledComponents.js

Refs: TOCDEV-2965
Changelog: Normalize icon spacing after fixed width for fontawesome icons was set

chore: normalize icon spacing

---

packages/two-factor-connector/src/modules/sagas.js

fix(two-factor-connector): rename tql parameter

---

packages/admin/src/routes/entities/components/RelationsView/RelationViewContainer.js
packages/admin/src/routes/entities/components/RelationsView/RelationsView.js
packages/admin/src/routes/entities/utils/relationPersistor.js
packages/admin/src/routes/entities/utils/relationPersistor.spec.js

Changelog: persist selected relation tab on detail
Refs: TOCDEV-2805

feat(admin): persist selected relation tab on detail

---

packages/entity-detail/src/components/DetailForm/DetailForm.js

Changelog: focus on first input field in create form
Refs: TOCDEV-2830

feat(entity-detail): focus on first input field in create form

---

packages/merge/src/components/Merge/Merge.js
packages/merge/src/components/Merge/MergeContainer.js
packages/merge/src/components/MergeSummary/MergeSummary.js
packages/merge/src/components/MergeSummary/MergeSummaryContainer.js
packages/merge/src/components/MergeSummary/index.js
packages/merge/src/components/MergeTable/MergeTable.js
packages/merge/src/components/MergeTable/MergeTableContainer.js
packages/merge/src/components/MergeTable/Selection.js
packages/merge/src/dev/data/mergeResponse.json
packages/merge/src/dev/data/sourceResponse.json
packages/merge/src/dev/input.json
packages/merge/src/dev/textResources.json
packages/merge/src/modules/merge/reducer.spec.js
packages/merge/src/modules/merge/sagas.js
packages/merge/src/modules/merge/sagas.spec.js
packages/merge/src/util/sourceData.js

- Add merge summary component
- Refactor merge relations and selection data structure for rest request
- Check if field is writable
- Fix issue with not existing display of entity

refactor(merge): merge v2 selection & summary

---

packages/scheduler/package.json
packages/scheduler/src/components/FullCalendar/FullCalendar.js
packages/scheduler/src/components/FullCalendar/FullCalendar.spec.js
packages/scheduler/src/components/FullCalendar/ResourceLabelContent.js
packages/scheduler/src/components/FullCalendar/StyledFullCalendar.js
packages/scheduler/src/components/Scheduler/Scheduler.js
packages/scheduler/src/utils/calendar.js
packages/scheduler/yarn.lock
packages/tocco-ui/src/Popover/Popover.js
packages/tocco-ui/src/Popover/StyledPopover.js

Refs: TOCDEV-2662
Changelog: Update Calendar component

refactor(scheduler): update FullCalendar  to v5.5

---

packages/admin/package.json
packages/admin/src/components/Header/Header.js
packages/admin/src/components/Header/HeaderContainer.js
packages/login/src/main.js
packages/two-factor-connector/src/main.js

Refs: TOCDEV-2941
Changelog: Add password-update and two-factor-connector to menu

feat(admin): add pw update and two factor to menu

---

packages/tocco-ui/src/Range/Range.js
packages/tocco-ui/src/Range/StyledRange.js

refactor(tocco-ui): refactor range.js

---

packages/entity-detail/src/components/DetailView/DetailView.js

- show async validation in progress status in save button
- only async validate a field on blur (not on change)
Refs: TOCDEV-2573
Changelog: Async validation on blur

refactor(entity-detail): improve async validation

---

packages/app-extensions/src/rest/rest.js
packages/app-extensions/src/rest/rest.spec.js

feat(app-extensions): add X-Origin-Id header

---

packages/login/src/components/TwoStepLoginForm/TwoStepLoginForm.js
packages/tocco-ui/src/EditableValue/typeEditors/NumberEdit.js

Changelog: Fix leading zeros bug in two-factor code
Refs: TOCDEV-2973

fix(login): fix leading zeros 2fa

---

packages/two-factor-connector/src/components/GlobalStyledComponents.js
packages/two-factor-connector/src/components/Result/Result.js
packages/two-factor-connector/src/components/Result/ResultContainer.js
packages/two-factor-connector/src/components/Result/StyledComponents.js
packages/two-factor-connector/src/components/Secret/Secret.js
packages/two-factor-connector/src/components/Secret/SecretContainer.js
packages/two-factor-connector/src/components/Secret/StyledComponents.js
packages/two-factor-connector/src/components/Start/Start.js
packages/two-factor-connector/src/components/Start/StartContainer.js
packages/two-factor-connector/src/components/TwoFactorConnector/TwoFactorConnector.js
packages/two-factor-connector/src/components/Verification/StyledComponents.js
packages/two-factor-connector/src/components/Verification/Verification.js

Refs: TOCDEV-3048
Changelog: Style two-factor-connector app

refactor(two-factor-connector): style two factor connector

---

packages/login/src/components/TwoStepLoginForm/TwoStepLoginForm.js

Changelog: Login: fix leading zeros bug in two-factor code
Refs: TOCDEV-2973

refactor(login): fix leading zeros 2fa

---

packages/tocco-ui/package.json
packages/tocco-ui/src/EditableValue/typeEditors/StyledTextEdit.js
packages/tocco-ui/yarn.lock

- replace auto size text component with a similar one. The previous components
showed some performance problems in safari
Refs: TOCDEV-3032
Changelog: Text autosize new component (Fixes Safari performance problems)

refactor(tocco-ui): change text component

---

packages/scheduler/src/components/FullCalendar/StyledFullCalendar.js

Refs: TOCDEV-3021
Changelog: Reset font sizes inside updated fullcalendar

refactor(scheduler): reset font sizes

---

packages/scheduler/src/components/FullCalendar/FullCalendar.js
packages/scheduler/src/components/FullCalendar/StyledFullCalendar.js
packages/scheduler/src/utils/calendar.js

Refs: TOCDEV-3022
Changelog: Optimize print view for calendar

feat(scheduler): optimize print view for calendar

---

packages/two-factor-connector/src/components/Result/StyledComponents.js
packages/two-factor-connector/src/components/Secret/Secret.js
packages/two-factor-connector/src/components/Secret/StyledComponents.js

Refs: TOCDEV-3048
Changelog: Harmonize icon size and text spacing

refactor(two-factor-connector): harmonize spacing

---

packages/resource-scheduler/src/components/ResourceScheduler/ResourceScheduler.js

Refs: TOCDEV-2971
Changelog: Fix blank screen after navigating away from the calendar

fix(resource-scheduler): fix useEffect return statement

---

packages/tocco-ui/src/DatePicker/DatePicker.js
packages/tocco-ui/src/DatePicker/DatePickerCustomStyles.js
packages/tocco-ui/src/DatePicker/GlobalDatePickerStyles.js
packages/tocco-ui/src/DatePicker/StyledDatePicker.js
packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js

Refs: TOCDEV-3085
Changelog: Style datepicker so that it fits better into the rest of admin

refactor(tocco-ui): style datepicker

---

packages/tocco-ui/src/FormattedValue/typeFormatters/DescriptionFormatter.js
packages/tocco-ui/src/Popover/Popover.js
packages/tocco-ui/src/Popover/StyledPopover.js

Refs: TOCDEV-3084
Changelog: Add a popover variant that is placed on the right of element

refactor(tocco-ui): ajdust popover position

---

packages/app-extensions/src/field/mappings.js
packages/entity-list/src/util/api/forms.js
packages/entity-list/src/util/api/forms.spec.js
packages/tocco-ui/src/Table/StyledTable.js
packages/tocco-util/src/mockData/data/user_list_form.json

Refs: TOCDEV-2969
Changelog: Support shrinkToContent column attribute

feat(tocco-ui): support shrinkToContent column attribute

---

packages/entity-list/src/util/api/fetchOptions.js
packages/entity-list/src/util/api/fetchOptions.spec.js

Refs: TOCDEV-3090
Changelog: Fix search form endless loading with empty filter field

refactor(entity-list): handle empty searchfilter field

---

packages/admin/src/routes/docs/components/Action/LazyAction.js
packages/admin/src/routes/docs/components/Action/actions/Delete.js
packages/admin/src/routes/docs/components/DocumentView/DocumentView.js
packages/admin/src/routes/docs/components/DocumentView/DocumentViewContainer.js
packages/admin/src/routes/docs/components/DocumentView/index.js

Changelog: Support deletion of documents in docs route
Refs: TOCDEV-3113

feat(admin): Support deletion of documents in docs route

---

packages/admin/src/routes/entities/components/RelationsView/RelationViewContainer.js
packages/admin/src/routes/entities/components/RelationsView/RelationsView.js

Refs: TOCDEV-3037
Changelog: Fix relation selection bug (TOCDEV-3037)

refactor(admin): use real entity name for relation selection

---

packages/merge/src/components/GlobalStyledComponents.js
packages/merge/src/components/Merge/StyledComponents.js
packages/merge/src/components/MergeSummary/MergeSummary.js
packages/merge/src/components/MergeSummary/StyledComponents.js
packages/merge/src/components/MergeTable/MergeTable.js
packages/merge/src/components/MergeTable/StyledComponents.js

Refs: TOCDEV-3082
Changelog: Fix merge table and harmonize spacing/text

refactor(merge): fix merge styles

---

packages/tocco-ui/src/Table/StyledTable.js

Refs: TOCDEV-3121
Changelog: Fix checkbox and menu background hover inside table heading

refactor(tocco-ui): style table heading

---

packages/scheduler/src/components/FullCalendar/StyledFullCalendar.js

Refs: TOCDEV-3021
Changelog: Harmonize text styles inside calendar entries

refactor(scheduler): style times

---

packages/admin/src/routes/entities/components/ActionView/ActionView.js

- navigate back to list oder detail view if callback (onError, onCancel or onSuccess) is called
Refs: TOCDEV-3020
Changelog: support fullscreen action callbacks

feat(admin): support fullscreen action callbacks

---

packages/app-extensions/src/rest/rest.js
packages/app-extensions/src/rest/rest.spec.js

Changelog: Set origin id for each session (TOCDEV-2980)
Refs: TOCDEV-2980

feat(app-extensions): set origin id for each session

---

packages/app-extensions/src/form/FormBuilder.js
packages/app-extensions/src/form/FormBuilder.spec.js
packages/entity-list/src/components/BasicSearchForm/BasicSearchForm.spec.js

Refs: TOCDEV-3012
Changelog: Writable mutlipath fix (TOCDEV-3012)

refactor(app-extensions): fields multipath writable fix

---

packages/entity-detail/src/components/DetailForm/DetailForm.js

Refs: TOCDEV-3083
Changelog: Fix autofocus on flatpickr element

refactor(entity-detail): fix focus

---

packages/scheduler/src/components/FullCalendar/StyledFullCalendar.js

Refs: TOCDEV-3021
Changelog: Allow display of horizontal overflow when printing

refactor(scheduler): adjust print css

---

packages/admin/src/modules/session/sagas.js

Refs: TOCDEV-3103
Changelog: Fix caching of business unit

fix(admin): clear short-term cache after changing the business unit

---

packages/delete/src/components/DeleteProgress/DeleteProgress.js
packages/delete/src/components/DeleteProgress/StyledComponents.js

Refs: TOCDEV-3185
Changelog: Vertically center spinner icon in delete progress

refactor(delete): harmonize icon spacing

---

packages/merge/src/components/MergeTable/MergeTable.js
packages/merge/src/components/MergeTable/StyledComponents.js

Refs: TOCDEV-3082
Changelog: Style merge table header contents for better UX

refactor(merge): style table header

---

packages/app-extensions/src/rest/rest.js
packages/app-extensions/src/rest/rest.spec.js
packages/two-factor-connector/src/modules/sagas.js
packages/two-factor-connector/src/modules/sagas.spec.js

fix(app-extensions): handle requests to nice2/* urls separately

---

packages/tocco-ui/src/Panel/PanelHeaderFooter.js
packages/tocco-ui/src/Panel/StyledPanel.js
packages/tocco-ui/src/Panel/StyledPanelBody.js
packages/tocco-ui/src/Panel/StyledPanelHeaderFooter.js

Refs: TOCDEV-3193
Changelog: Make panel header clickable so it can also expand the panel

refactor(tocco-ui): make panel clickable

---

packages/admin/src/components/Login/StyledComponents.js

Refs: TOCDEV-3221
Changelog: Fix logo not displaying in login screen on iOS

refactor(admin): fix logo in iOS

---

packages/entity-detail/src/components/DetailForm/DetailForm.js
packages/entity-detail/src/components/DetailForm/SaveButton.js
packages/entity-detail/src/components/DetailForm/StyledComponents.js
packages/entity-detail/src/components/DetailForm/StyledDetailFormLastSaved.js
packages/entity-list/src/util/StyledComponents.js
packages/entity-list/src/util/cellRenderer.js

Refs: TOCDEV-3198
Changelog: Fix height and action button styling of detail form in old client

refactor(entity-list): fix detail form styling

---

packages/tocco-ui/src/Layout/LayoutContainer.js

refactor(tocco-ui): fix width calculation

---

packages/app-extensions/src/actions/components/StyledReportSettings.js
packages/app-extensions/src/formData/advancedSearch/StyledAdvancedSearch.js
packages/app-extensions/src/notifier/modules/modalComponents/ModalButtons.js
packages/app-extensions/src/notifier/modules/modalComponents/StyledComponents.js
packages/delete/src/components/Dialog/Dialog.js
packages/delete/src/components/Dialog/StyledComponents.js
packages/entity-list/src/components/ColumnPicker/StyledColumnPicker.js

Refs: TOCDEV-3108
Changelog: Move buttons inside modals to the right to improve UX

refactor(app-extensions): move modal buttons to the right

---

packages/app-extensions/src/actions/components/ReportSettings.js
packages/app-extensions/src/actions/modules/prepare/initialFormHandler.js

- mode is required now
Refs: TOCDEV-3218
Changelog: Fix empty report settings (TOCDEV-3218)

fix(app-extensions): set mode for simple-form

---

packages/app-extensions/src/notifier/components/StyledNotifier.js

Refs: TOCDEV-2622
Changelog: Fix spacing of notifiers without title

refactor(app-extensions): fix toastr without title

---

packages/simple-form/src/components/Form/Form.js
packages/simple-form/src/components/Form/StyledComponents.js

Refs: TOCDEV-3108
Changelog: Change button position to right side inside modal

refactor(simple-form): refactor and change button position

---

packages/two-factor-connector/src/components/Result/StyledComponents.js
packages/two-factor-connector/src/components/Secret/StyledComponents.js

Refs: TOCDEV-3048
Changelog: Fix icon and qr code spacing inside two factor connector

refactor(two-factor-connector): fix styling

---

packages/merge/src/components/MergeTable/Selection.js

Refs: TOCDEV-3229
Changelog: adjust merge table "all" label layout

fix(merge): all relation label not bold

---

packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js

refactor(tocco-ui): show delete only if not read-only

---

packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json
packages/tocco-ui/src/Preview/StyledPreview.js
packages/tocco-ui/src/Upload/StyledView.js
packages/tocco-ui/src/Upload/SyledUploadInput.js
packages/tocco-ui/src/Upload/UploadInput.js
packages/tocco-ui/src/Upload/View.js
packages/tocco-ui/src/Upload/index.js
packages/tocco-ui/src/utilStyles/index.js

Refs: TOCDEV-3191
Changelog: Style upload and switch to light icons

refactor(tocco-ui): style upload

---

packages/admin/src/components/Header/StyledComponents.js

refactor(admin): change header color

---

packages/tocco-ui/package.json
packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
packages/tocco-ui/yarn.lock

- do not close popup on any blur but only when pressing Enter or Tab
- update flatpickr to deal with bubbling key press events
- add handler to flatpickr container to have consistent handling when using popup or direct input
Refs: TOCDEV-3091

fix(tocco-ui): fix key events in date field popup

---

packages/app-extensions/src/rest/InformationError.js
packages/app-extensions/src/rest/index.js
packages/app-extensions/src/rest/request.js
packages/app-extensions/src/rest/request.spec.js
packages/app-extensions/src/rest/rest.js
packages/app-extensions/src/rest/rest.spec.js
packages/delete/src/modules/delete/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.spec.js
packages/entity-detail/src/util/api/entities.js
packages/entity-detail/src/util/api/entities.spec.js

Refs: TOCDEV-3097
Changelog: Handle information exceptions from the server in forms, delete action and a general fallback.

handle information exceptions

---

packages/entity-list/src/components/BasicSearchForm/BasicSearchForm.js
packages/entity-list/src/components/BasicSearchForm/StyledBasicSearchForm.js

Refs: TOCDEV-3269
Changelog: Restrict max height of basic search form only in modal

refactor(entity-list): adjust max-height

---

packages/tocco-ui/src/LoadMask/LoadMask.js
packages/tocco-ui/src/LoadMask/StyledLoadMask.js

Refs: TOCDEV-3298
Changelog: Prevent action buttons disappearing on scroll

refactor(tocco-ui): style and refactor load mask

---

packages/entity-list/src/components/Table/Table.js
packages/entity-list/src/components/Table/navigationCell.js

Refs: TOCDEV-3295
Changelog: hide list navigation arrow if row is not clickable

fix(entity-list): hide list navigation arrow if row is not clickable

---

packages/entity-list/src/components/ColumnPicker/StyledColumnPicker.js

Refs: TOCDEV-3294
Changelog: Reset label spacing inside column picker for old client

refactor(entity-list): reset column picker label

---

packages/tocco-ui/src/FormattedValue/typeFormatters/DescriptionFormatter.js

Refs: TOCDEV-3299
Changelog: Harmonize popover placement on description formatter

refactor(tocco-ui): harmonize popover placement

---

packages/admin/src/components/Header/Header.js
packages/admin/src/components/Navigation/Navigation.js
packages/admin/src/routes/entities/components/RelationsView/RelationsView.js
packages/admin/src/routes/entities/utils/navigationStrategy.js
packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
packages/tocco-ui/src/BurgerButton/BurgerButton.js
packages/tocco-ui/src/DatePicker/DatePicker.js
packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
packages/tocco-ui/src/MultiCheckbox/MultiCheckbox.js
packages/tocco-ui/src/SearchBox/SearchBox.js
packages/tocco-ui/src/Select/ClearIndicator.js
packages/tocco-ui/src/Table/selection/MultiSelectCell.js

Refs: TOCDEV-3216
Changelog: Add aria-labels to improve accessibility

refactor(tocco-ui): add text labels

---

packages/entity-list/src/components/SelectionController/SelectionController.js
packages/entity-list/src/modules/selection/sagas.js
packages/entity-list/src/modules/selection/sagas.spec.js

Changelog: No list refresh after selection clear
Refs: TOCDEV-3192

refactor(entity-list): improve selection clear

---

packages/tocco-ui/package.json
packages/tocco-ui/yarn.lock

- messed with the popup
Refs: TOCDEV-3091

fix(tocco-ui): revert flatpickr update

---

packages/app-extensions/src/form/FormBuilder.js
packages/app-extensions/src/form/FormBuilder.spec.js

Changelog: render description field in form
Refs: TOCDEV-3297

fix(app-extensions): render description field in form

---

packages/docs-browser/src/components/DocsView/DocsView.js
packages/entity-list/src/modules/list/sagas.js
packages/entity-list/src/modules/list/sagas.spec.js

Refs: TOCDEV-3175
Changelog: add different form for root level in dms

feat: add different form for root level in dms

---

packages/tocco-ui/src/StatedValue/StyledStatedValue.js

Refs: TOCDEV-3288
Changelog: Adjust label margin in input fields

refactor(tocco-ui): adjust stated value margin

---

packages/merge/src/modules/merge/sagas.js
packages/merge/src/modules/merge/sagas.spec.js

Refs: TOCDEV-3372
Changelog: support selection of type query

fix(merge): support selection of type query

---

packages/app-extensions/src/form/asyncValidation.js
packages/app-extensions/src/rest/request.js
packages/app-extensions/src/rest/rest.js

- add http header 'X-Client-Questions: true' to most requests
- explicitly disable client questions for validation
- allow client question response code if the header is set
Refs: TOCDEV-3266

fix: implement new client question handling

---

packages/entity-list/src/modules/list/sagas.js
packages/entity-list/src/modules/list/sagas.spec.js

the sorting of the table and preferences have a higher sorting priority then the order by of the active search filter. The fallback sorting is only set if there is no active search filter with an order by property.
Refs: TOCDEV-3207
Changelog: support sorting by search filters and preferences

fix(entity-list): support sorting by search filters and preferences

---

packages/entity-list/src/modules/list/sagas.js
packages/entity-list/src/modules/list/sagas.spec.js

Refs: TOCDEV-3178
Changelog: clear selection if parent is set

feat(entity-list): clear selection if parent is set

---

packages/merge/src/modules/merge/sagas.js
packages/merge/src/modules/merge/sagas.spec.js

Refs: TOCDEV-3372
Changelog: support selection of type query

cherrypick

---

packages/delete/src/components/InfoPart/LinkPopOver.js
packages/entity-detail/src/components/DetailForm/SaveButton.js
packages/scheduler/src/components/FullCalendar/FullCalendar.js
packages/tocco-ui/src/Popover/Popover.js
packages/tocco-ui/src/Popover/Popover.stories.js
packages/tocco-ui/src/Popover/StyledPopover.js

Refs: TOCDEV-3413
Changelog: Restrict max width of popover to 400px

refactor(tocco-ui): add max width to popover

---

packages/admin/src/routes/entities/components/RelationsView/RelationsView.js
packages/admin/src/routes/entities/utils/navigationStrategy.js
packages/tocco-ui/src/BurgerButton/BurgerButton.js
packages/tocco-ui/src/DatePicker/DatePicker.js
packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
packages/tocco-ui/src/Select/ClearIndicator.js

Refs: TOCDEV-3216
Changelog: Reference text ressources for aria-labels for improved localization

refactor(tocco-ui): reference txt ressources

---

packages/entity-list/src/modules/selection/sagas.js
packages/entity-list/src/modules/selection/sagas.spec.js

Refs: TOCDEV-3178
Changelog: clear selection fire onSelectChange

fix(entity-list): clear selection fire onSelectChange

---

packages/tocco-util/src/tqlBuilder/tqlBuilder.js
packages/tocco-util/src/tqlBuilder/tqlBuilder.spec.js

Refs: TOCDEV-3425
Changelog: Fix fulltext search

fix(tocco-util): set brackets for fulltext search

---

packages/app-extensions/src/actions/modules/actionHandlers/simpleAction.js
packages/app-extensions/src/actions/modules/actionHandlers/simpleAction.spec.js
packages/app-extensions/src/rest/index.js
packages/app-extensions/src/rest/request.js
packages/app-extensions/src/rest/request.spec.js
packages/app-extensions/src/rest/rest.js
packages/tocco-util/src/download/download.js
packages/tocco-util/src/download/index.js

Changelog: simpleAction can now handle download links returned from the backend

allow simple action to download files

---

package.json
packages/copy/package.json
packages/delete/package.json
packages/user-qr-action/package.json
scripts/helpers.sh
scripts/release-all-packages.sh
scripts/release-package.sh

- if the flag "--auto" is passed questions will be automatically answered
- suggest next version
- add script to release all packages where the package.json has a property "releasePackage" which is true and the changelog is not empty

chore: add automatic releasing

---

packages/admin/src/routes/entities/utils/navigationStrategy.js

chore: fix intl and txt ressource

---

packages/entity-detail/src/modules/entityDetail/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.spec.js

Refs: TOCDEV-3424
Changelog: Handle client question cancellation

refactor(entity-detail):  client question cancel

---

packages/tocco-ui/src/EditableValue/EditableValue.stories.js
packages/tocco-ui/src/Select/Menu.js
packages/tocco-ui/src/Select/Select.js

Refs: TOCDEV-3359
Changelog: Keep scroll position on multi select selection

fix(tocco-ui): keep scroll in multi select

---

packages/app-extensions/src/notification/modules/blocking/BlockingDisplay/BlockingDisplay.js
packages/app-extensions/src/notification/modules/blocking/BlockingDisplay/StyledComponents.js
packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/StyledComponents.js
packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/Toaster.js
packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/ToasterDisplay.js

Refs: TOCDEV-3445
Changelog: Style new notification boxes

refactor(app-extensions): style notifciations

---

packages/two-factor-connector/src/components/Start/Start.js

refactor(two-factor-connector): render text as html

---

packages/app-extensions/src/notifier/modules/modalComponents/ModalContent.js
packages/app-extensions/src/notifier/modules/modalComponents/ModalDisplay.js
packages/app-extensions/src/notifier/modules/modalComponents/StyledComponents.js

Refs: TOCDEV-3494
Changelog: Prevent stacking of modal overlays

refactor(app-extensions): prevent stacking of modal overlay

---

packages/tocco-ui/src/Menu/Menu.js

Refs: TOCDEV-3481
Changelog: Fix popper menu positioning

refactor(tocco-ui): fix menu

---

packages/entity-detail/src/components/DetailForm/StyledComponents.js
packages/tocco-ui/src/Layout/StyledLayoutContainer.js

Refs: TOCDEV-3556
Changelog: Prevent layout container overlap in detail view

refactor(tocco-ui): prevent layout container overlap

---

packages/delete/src/components/Dialog/Dialog.js
packages/delete/src/components/InfoPart/InfoPart.spec.js
packages/delete/src/utils/deleteRequestParser.js
packages/delete/src/utils/deleteRequestParser.spec.js

Refs: TOCDEV-3416
Changelog: Show not deletable entities with 0

refactor(delete): show not deletable with 0

---

packages/admin/src/modules/navigation/sagas.js
packages/app-extensions/src/rest/helpers.js
packages/app-extensions/src/rest/helpers.spec.js
packages/tocco-util/src/cache/cache.js
packages/tocco-util/src/cache/cache.spec.js
packages/tocco-util/src/cache/index.js

- remove medium term caching implementation
- menu is never cached
- form is only cached until page is reloaded
Refs: TOCDEV-3421

feat: disable medium term caching of forms und menu

---

packages/docs-browser/src/components/DocsBrowser/DocsBrowser.js
packages/docs-browser/src/components/DocsBrowser/StyledComponents.js
packages/docs-browser/src/components/DocsView/DocsView.js
packages/docs-browser/src/components/DocsView/StyledComponents.js
packages/docs-browser/src/components/DocumentView/DocumentView.js
packages/docs-browser/src/components/DocumentView/StyledComponents.js

Refs: TOCDEV-3553
Changelog: Fix icon and document view in doc browser

refactor(docs-browser): style docs browser

---

packages/admin/src/components/Admin/StyledComponents.js
packages/admin/src/components/Header/Header.js
packages/admin/src/components/Header/StyledComponents.js
packages/app-extensions/src/notifier/modules/modalComponents/StyledComponents.js
packages/entity-list/src/components/AdminSearchForm/StyedComponents.js
packages/tocco-ui/src/Breadcrumbs/StyledBreadcrumbs.js
packages/tocco-ui/src/Select/Menu.js

Refs: TOCDEV-3563
Changelog: Fix tether dropdown z-index to prevent overlay on scroll

refactor(admin): fix tether overlay on scroll

---

packages/tocco-ui/src/Upload/View.js

- prevent value false as caption

refactor(tocco-ui): fix prop type error

---

packages/entity-list/src/input.js
packages/entity-list/src/modules/list/actions.js
packages/entity-list/src/modules/list/reducer.js
packages/entity-list/src/modules/list/reducer.spec.js
packages/entity-list/src/modules/list/sagas.js
packages/entity-list/src/modules/list/sagas.spec.js

- dispatch props keys, tql and search-filters to store
- dispatch on change
Refs: TOCDEV-3532

refactor(entity-list): dispatch input to store

---

packages/docs-browser/src/components/Action/actions/CreateDomain.js
packages/docs-browser/src/components/Action/actions/CreateFolder.js
packages/docs-browser/src/components/Action/actions/Edit.js
packages/docs-browser/src/components/Action/actions/Move.js
packages/docs-browser/src/main.js

- set handle optional depending on input type
- show notifications optionally
- set emit action on all actions
Refs: TOCDEV-3461
Changelog: Fix doc-browsers client questions

refactor(docs-browser): handle notifications

---

packages/tocco-ui/src/Table/StyledTable.js

fix(tocco-ui): make navigation-column popup visible again

---

packages/tocco-ui/src/Range/StyledRange.js

Refs: TOCDEV-3573
Changelog: Prevent range input overflow

refactor(tocco-ui): improve range styling

---

packages/input-edit/src/modules/inputEdit/actions.js
packages/input-edit/src/modules/inputEdit/reducer.js
packages/input-edit/src/modules/inputEdit/sagas.js
packages/input-edit/src/modules/inputEditTable/sagas.js
packages/input-edit/src/modules/inputEditTable/sagas.spec.js

fix(input-edit): only load data when selection update is done

---

packages/entity-list/src/modules/entityList/sagas.js
packages/entity-list/src/modules/entityList/sagas.spec.js
packages/entity-list/src/modules/list/actions.js
packages/entity-list/src/modules/list/sagas.js
packages/entity-list/src/modules/list/sagas.spec.js

- introduce list initialized action to make sure the model is loaded during "set sort"
Refs: TOCDEV-3589

fix(entity-list): initialization bug

---

packages/merge/src/util/sourceData.js
packages/merge/src/util/sourceData.spec.js

Changelog: refactor extracting displays

refactor(merge): refactor extracting displays

---

packages/admin/src/components/Header/NotificationCenterButton.js
packages/admin/src/components/Header/NotificationCenterRedDot.js
packages/admin/src/components/Header/NotificationCenterRedDotContainer.js
packages/app-extensions/src/notification/modules/center/actions.js
packages/app-extensions/src/notification/modules/center/reducer.js
packages/app-extensions/src/notification/modules/center/reducer.spec.js
packages/app-extensions/src/notification/modules/center/sagas.js
packages/app-extensions/src/notification/modules/center/sagas.spec.js
packages/app-extensions/src/notification/modules/socket/sagas.js

feat: add red dot to notification center

---

packages/app-extensions/src/notifier/modules/modalComponents/ModalContent.js
packages/app-extensions/src/notifier/modules/modalComponents/StyledComponents.js
packages/tocco-ui/src/Select/Menu.js
packages/tocco-ui/src/Select/index.js
packages/tocco-ui/src/index.js

Refs: TOCDEV-3563
Changelog: Fix select menu disappearing behind modal

refactor(tocco-ui): fix tether in modal

---

packages/entity-list/src/components/FullTextSearchForm/FullTextSearchForm.js

- useMemo to prevent reinitializing
Refs: TOCDEV-3443
Changelog: Fix fulltext search form

refactor(entity-list): fix fulltext form

---

packages/admin/src/components/Header/NotificationCenterButton.js
packages/admin/src/components/Header/NotificationCenterRedDot.js
packages/admin/src/components/Header/StyledComponents.js
packages/app-extensions/src/notification/api.js
packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js
packages/app-extensions/src/notification/components/NotificationBody/StyledComponents.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/Notification.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/NotificationCenter.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/StyledComponents.js
packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json

Refs: TOCDEV-3590
Changelog: Style notification center

refactor(app-extensions): style notification center

---

server/index.html

chore: prevent body overflow on localhost

---

packages/app-extensions/src/form/FormBuilder.js
packages/entity-detail/src/components/DetailForm/StyledComponents.js
packages/tocco-ui/src/Layout/LayoutContainer.js
packages/tocco-ui/src/Layout/StyledLayoutContainer.js

Refs: TOCDEV-3639
Changelog: Introduce new prop to determine if layout containers should occupy remaining height on screen

refactor(tocco-ui): introduce new height prop

---

packages/admin/src/routes/entities/components/DocsView/DocsView.js
packages/admin/src/routes/entities/components/ListView/DocsViewAdapter.js
packages/docs-browser/README.md
packages/docs-browser/src/components/DocsBrowser/DocsBrowser.js
packages/docs-browser/src/components/DocsBrowser/DocsBrowserContainer.js
packages/docs-browser/src/components/DocsBrowser/StyledComponents.js

Refs: TOCDEV-3571
Changelog: Adjust left padding of Breadcrumbs in list view

refactor(docs-browser): adjust breadcrumbs padding

---

scripts/helpers.sh

- if version is 3.0.0 the tag shold be nice30 and not nice3

chore: fix release tag

---

packages/tocco-ui/src/Panel/StyledPanelHeaderFooter.js

Refs: TOCDEV-3686
Changelog: Change cursor to pointer on panel header/footer hover

refactor(tocco-ui): change cursor on hover

---

packages/admin/src/routes/entities/components/DocsView/DocsView.js
packages/admin/src/routes/entities/components/ListView/DocsViewAdapter.js
packages/admin/src/routes/entities/components/RelationsView/DocsViewAdapter.js
packages/docs-browser/README.md
packages/docs-browser/src/components/Action/actions/Move.js
packages/docs-browser/src/components/DocsBrowser/DocsBrowser.js
packages/docs-browser/src/components/DocsBrowser/DocsBrowserContainer.js
packages/docs-browser/src/components/DocsBrowser/StyledComponents.js

refactor(docs-browser): set noLeftPadding default to false

---

packages/admin/src/routes/entities/utils/navigationStrategy.js
packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
packages/app-extensions/src/rest/helpers.js
packages/app-extensions/src/rest/helpers.spec.js
packages/app-extensions/src/rest/index.js
packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
packages/entity-list/src/components/AdminSearchForm/AdminSearchFormContainer.js
packages/entity-list/src/components/AdminSearchForm/StyedComponents.js
packages/entity-list/src/components/SearchFilterList/SearchFilterList.js
packages/entity-list/src/components/SearchFilterList/SearchFilterListContainer.js
packages/entity-list/src/components/SearchFilterList/StyledComponents.js
packages/entity-list/src/modules/searchForm/actions.js
packages/entity-list/src/modules/searchForm/sagas.js
packages/entity-list/src/modules/searchForm/sagas.spec.js
packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json
packages/tocco-ui/src/Menu/BallMenu.js
packages/tocco-ui/src/Menu/BallMenu.spec.js
packages/tocco-util/src/navigationStrategy/navigationStrategy.js

Changelog: Added options to create a search filter from the current search, edit or delete an existing filter
Refs: TOCDEV-3360

feat(entity-list): add buttons to create, edit and delete filters

---

packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
packages/entity-list/src/components/AdminSearchForm/AdminSearchFormContainer.js
packages/entity-list/src/modules/searchForm/actions.js
packages/entity-list/src/modules/searchForm/sagas.js
packages/entity-list/src/modules/searchForm/sagas.spec.js

feat(entity-list): save and delete default filter

---

packages/admin/src/components/Login/Login.js
packages/admin/src/components/Login/StyledComponents.js

Refs: TOCDEV-3265
Changelog: Enable body scrolling on login screen for smaller screens

refactor(admin): reset scrolling on login

---

packages/entity-list/src/components/SearchFilterList/SearchFilterList.js
packages/entity-list/src/components/SearchFilterList/StyledComponents.js
packages/tocco-ui/src/Menu/index.js
packages/tocco-ui/src/index.js

Refs: TOCDEV-3698
Changelog: Fix hover delay and hover color of search filter buttons

refactor(entity-list): improve hover

---

packages/app-extensions/src/notifier/notificationActionFactory.js
packages/app-extensions/src/notifier/notificationActionFactory.spec.js
packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
packages/entity-list/src/components/SearchFilterList/SearchFilterList.js
packages/resource-scheduler/src/components/SearchPanel/SearchPanel.js
packages/scheduler/src/components/NavigationFullCalendar/NavigationFullCalendar.js
packages/tocco-theme/src/ToccoTheme/defaultTheme.js
packages/tocco-ui/src/Breadcrumbs/Breadcrumbs.js
packages/tocco-ui/src/Button/Button.stories.js
packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json
packages/tocco-ui/src/Menu/ButtonMenu.js
packages/tocco-ui/src/Menu/ButtonMenu.spec.js
packages/two-factor-connector/src/components/Result/Result.js

Refs: TOCDEV-3741
Changelog: Change all icons to light version to ensure consisten look of UI

chore: change all icons to light

---

packages/app-extensions/src/actions/components/ReportSettings.js

- i think the change from "formData" to "defaultValues" in change 9c3b7a322b1b6a0b1509d43846e7a7bdf76e67e6 was by accident
Refs: TOCDEV-3744

fix(app-extension): set form data on simpleform

---

packages/tocco-ui/src/EditableValue/typeEditors/DateEdit.js

chore: refactor class component

---

packages/entity-list/src/modules/searchForm/StyledComponents.js
packages/entity-list/src/modules/searchForm/sagas.js

Refs: TOCDEV-3688
Changelog: Adjust spacing and alignment of button inside modal

refactor(entity-list): modal button alignment

---

packages/admin/.yarnrc
packages/copy/.yarnrc
packages/delete/.yarnrc
packages/docs-browser/.yarnrc
packages/entity-browser/.yarnrc
packages/input-edit/.yarnrc
packages/installation-delta-action/.yarnrc
packages/login/.yarnrc
packages/merge/.yarnrc
packages/resource-scheduler/.yarnrc
packages/sso-login/.yarnrc
packages/tocco-theme/.yarnrc
packages/two-factor-connector/.yarnrc
packages/user-qr-action/.yarnrc
plop/templates/package/.yarnrc
scripts/tagging.sh

- the automatically created tag will be deleted. The prefix avoids naming conflicts
Refs: TOCDEV-3619

chore: prefix release tag

---

packages/app-extensions/src/actions/modules/prepare/largeSelectionHandler.js
packages/app-extensions/src/actions/modules/prepare/largeSelectionHandler.spec.js
packages/app-extensions/src/actions/modules/prepare/prepare.js
packages/app-extensions/src/notifier/modules/modalComponents/ModalButtons.js
packages/tocco-util/src/mockData/data/textResources.json
packages/tocco-util/src/mockData/data/user_list_form.json

Changelog:  Add action selection count confirm
TOCDEV-3632

feat(app-extensions): add selection count confirm

---

packages/merge/src/modules/merge/sagas.js
packages/merge/src/modules/merge/sagas.spec.js

- read updated entities from sourceData to support a query selection
Changelog: Fix merge close function with query selection
Refs: TOCDEV-3751

fix(merge): improve close action

---

packages/app-extensions/src/notifier/notificationActionFactory.js

- Add Enter and Escape support to control the confirm box. This also prevents a bug when pressing enter
Changelog: Add confirm keyboard support
Refs: TOCDEV-3690

feat(app-extension): add keyboard confirm support

---

packages/entity-list/src/modules/searchForm/sagas.js
packages/entity-list/src/modules/searchForm/sagas.spec.js

feat(entity-list): set newly created filter as active

---

packages/admin/src/components/Navigation/Navigation.js
packages/admin/src/components/Navigation/StyledComponents.js

Refs: TOCDEV-3749
Changelog: Style nav switch button to better fit into UI

refactor(admin): style nav switch button

---

packages/merge/src/modules/merge/sagas.js
packages/merge/src/modules/merge/sagas.spec.js

Changelog: disable client questions for merge action
Refs: TOCDEV-3755

fix(merge): disable client questions for merge action

---

scripts/cherrypick.sh

fix: fix auto cherrypick script

---

packages/docs-browser/src/components/DocsBrowser/DocsBrowser.js
packages/docs-browser/src/components/DocsView/DocsView.js
packages/docs-browser/src/modules/path/sagas.js
packages/docs-browser/src/modules/path/sagas.spec.js
packages/docs-browser/src/utils/isRootLocation.js
packages/docs-browser/src/utils/isRootLocation.spec.js
packages/entity-list/src/main.js
packages/entity-list/src/modules/searchForm/sagas.js
packages/tocco-ui/src/Breadcrumbs/Breadcrumbs.js

Also fix initialization of the search form field values (don't set
old values as initial values, but rather set the old values via
`change` action).
Refs: TOCDEV-3615

Fix DMS navigation issues (related to to search view)

---

scripts/helpers.sh

- to ensure all branches have the same scripts running

chore: copy script folder from master

---

packages/docs-browser/README.md

chore: correct readme entry

---

packages/merge/src/main.js
packages/merge/src/modules/merge/sagas.js
packages/merge/src/modules/merge/sagas.spec.js

Changelog: disable client questions for merge action
Refs: TOCDEV-3755

feat(merge): show client questions for merge action

---

scripts/release-package.sh

- fetch tags shortly before pushing to avoid conflicts
- accept Y as valid response
- add helper text

chore: improve release script

---

packages/entity-list/src/components/SelectionController/SelectionController.js
packages/entity-list/src/components/SelectionController/StyledSelectionController.js

Refs: TOCDEV-3764
Changelog: Fix selection controller button font color

refactor(entity-list): fix font color

---

packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
packages/entity-list/src/components/AdminSearchForm/StyedComponents.js
packages/entity-list/src/components/EntityList/EntityList.js
packages/entity-list/src/components/EntityList/StyledComponents.js
packages/entity-list/src/components/SearchView/SearchView.js
packages/entity-list/src/components/SearchView/StyledComponents.js
packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json

Refs: TOCDEV-3743
Changelog: Add collapse feature to search panel in list view

refactor(entity-list): Add search panel collapse feature

---

packages/admin/src/components/MenuTree/MenuTree.js
packages/admin/src/components/MenuTree/StyledComponents.js
packages/admin/src/components/Navigation/StyledComponents.js

Refs: TOCDEV-3749
Changelog: Harmonize menu tree spacing and switch icon size

refactor(admin): harmonize menu spacing

---

.gitlab-ci.yml

chore: add missing package

---

.gitlab-ci.yml

chore: add missing variable

---

scripts/release-package.sh

chore: release script enhance log

---

packages/tocco-util/src/tqlBuilder/tqlBuilder.js
packages/tocco-util/src/tqlBuilder/tqlBuilder.spec.js

Changelog: Fix date-time search
Refs: TOCDEV-3721

refactor(tocco-util): search for date time im gtm + 0

---

packages/admin/src/routes/entities/components/DetailView/DetailView.js
packages/admin/src/routes/entities/components/DetailView/StyledComponents.js
packages/admin/src/routes/entities/components/RelationsView/RelationsView.js
packages/admin/src/routes/entities/components/RelationsView/StyledComponents.js

Refs: TOCDEV-3742
Changelog: Add panel collapse feature in detail view

refactor(admin): add panel collapse in detail view

---

packages/tocco-ui/src/LoadMask/StyledLoadMask.js

Refs: TOCDEV-3793
Changelog: Fix overlay of modal in widget mode

refactor(tocco-ui): fix modal overlay

---

packages/admin/src/components/Navigation/StyledComponents.js

Refs: TOCDEV-3749
Changelog: Align nav switch button horizontally

refactor(admin): align nav switch button

---

packages/entity-browser/src/routes/detail/components/EntityDetail/EntityDetail.js
packages/entity-browser/src/routes/list/containers/ListViewContainer.js
packages/entity-detail/src/components/SubGrid/SubGrid.js
packages/entity-detail/src/main.js

due to naming conflicts the same store was loaded for different nice tabs.
With this change i made sure, that every tab gets its own id.
Refs: TOCDEV-3683
Changelog: Fix multi-tab problem
Cherry-pick:Up

refactor(entity-browser): adjust store ids

---

build/webpack.config.js

chore: fix missing map files

---

packages/tocco-ui/src/Menu/Menu.js
packages/tocco-ui/src/Menu/StyledComponents.js

Refs: TOCDEV-3792
Changelog: Fix popper menu on safari browsers

refactor(tocco-ui): fix popper menu on safari

---

packages/app-extensions/src/notification/modules/socket/socket.js
packages/app-extensions/src/notification/modules/socket/socket.spec.js

- use window.location for relativ backend urls
Changelog: Fix notification socket url

refactor(app-extensions): fix relativ backend url

---

packages/tocco-ui/src/Select/IndicatorsContainer.js
packages/tocco-ui/src/Select/Menu.js
packages/tocco-ui/src/Select/MenuList.js
packages/tocco-ui/src/Select/Select.js
packages/tocco-ui/src/Select/StyledComponents.js
packages/tocco-ui/src/Select/StyledIndicatorsContainer.js
packages/tocco-ui/src/Select/index.js

Refs: TOCDEV-3700
Changelog: Make select dropdown menu style more uniform for a more consistent UI

refactor(tocco-ui): make select more uniform

---

packages/admin/src/routes/entities/components/RelationsView/RelationsView.js
packages/admin/src/routes/entities/components/RelationsView/StyledComponents.js
packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
packages/entity-list/src/components/AdminSearchForm/StyedComponents.js
packages/entity-list/src/components/EntityList/StyledComponents.js
packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json

Refs: TOCDEV-3743
Changelog: Change collpase icon for detail and list view

refactor(entity-list): change collapse icon

---

packages/admin/src/components/Navigation/Navigation.js
packages/admin/src/components/Navigation/StyledComponents.js

Refs: TOCDEV-3814
Changelog: Add hover effect to nav switch button

refactor(admin): add hover effect

---

packages/app-extensions/src/notification/modules/modal/ModalDisplay/ModalDisplay.js
packages/app-extensions/src/notification/modules/modal/ModalDisplay/StyledComponents.js

Refs: TOCDEV-3558
Changelog: Align modal globally at same position

refactor(app-extensions): align modal globally

---

packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/StyledComponents.js
packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/ToasterDisplay.js

refactor(app-extensions): load toasters in body

---

packages/merge/src/components/MergeTable/MergeErrors.js
packages/merge/src/components/MergeTable/Selection.js
packages/merge/src/components/MergeTable/StyledComponents.js

Refs: TOCDEV-3862
Changelog: Style merge errors

refactor(merge): style merge errors

---

packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/StyledComponents.js
packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/Toaster.js
packages/app-extensions/src/notification/types.js

Refs: TOCDEV-3860
Changelog: Harmonize toaster styling

refactor(app-extensions): harmonize toaster styling

---

packages/app-extensions/src/notification/modules/blocking/BlockingDisplay/BlockingDisplay.js
packages/app-extensions/src/notification/modules/blocking/BlockingDisplay/StyledComponents.js

Refs: TOCDEV-3860
Changelog: Fix blocking info being covered by header

refactor(app-extensions): adjust blocker-display

---

packages/input-edit/src/components/InputEdit/StyledInputEdit.js

Refs: TOCDEV-3871
Changelog: Adjust height and width of input edit table

refactor(input-edit): adjust dimensions

---

packages/admin/src/components/Navigation/Navigation.js

feat(admin): open default tabs when switching visible menus

---

packages/app-extensions/src/notification/modules/blocking/BlockingDisplay/BlockingDisplay.js
packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/Toaster.js

refactor(app-extensions): fix toaster content

---

packages/app-extensions/src/notification/api.js
packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js

- catch 404 for already deleted output jobs
Refs: TOCDEV-3878
Changelog: Fix notifications for already deleted outputjobs

refactor(app-extensions): fix outputjob 404

---

packages/tocco-ui/src/Range/rangeTypeMappings.js

fix(tocco-ui): use local date when using single value in range

---

scripts/release-all-packages.sh

chore: fix release all script

---

packages/merge/src/components/MergeTable/MergeErrors.js

Changelog: fix merge error summary
Refs: TOCDEV-3862

fix(merge): fix merge error summary

---

packages/entity-list/src/components/ColumnPicker/StyledColumnPicker.js

Refs: TOCDEV-3925
Changelog: Add hover effect to column picker list

refactor(entity-list): column picker hover

---

packages/app-extensions/src/field/editableTypeConfigs/index.js
packages/app-extensions/src/field/mappings.js
packages/app-extensions/src/rest/helpers.js
packages/app-extensions/src/rest/helpers.spec.js
packages/app-extensions/src/rest/index.js
packages/entity-detail/src/components/DetailForm/DetailForm.js
packages/entity-detail/src/components/DetailForm/MarkButton.js
packages/entity-detail/src/components/DetailForm/StyledComponents.js
packages/entity-detail/src/modules/entityDetail/actions.js
packages/entity-detail/src/modules/entityDetail/reducer.js
packages/entity-detail/src/modules/entityDetail/reducer.spec.js
packages/entity-detail/src/modules/entityDetail/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.spec.js
packages/entity-list/src/components/Table/Table.js
packages/entity-list/src/components/Table/markingCell.js
packages/entity-list/src/containers/TableContainer.js
packages/entity-list/src/customActions.js
packages/entity-list/src/modules/list/actions.js
packages/entity-list/src/modules/list/sagas.js
packages/entity-list/src/modules/list/sagas.spec.js
packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json
packages/tocco-util/src/tqlBuilder/tqlBuilder.js
packages/tocco-util/src/tqlBuilder/tqlBuilder.spec.js

Will be used for the marking feature (regular (empty) star will be
displayed for unmarked entities and the new solid star for marked
entities)
Refs: TOCDEV-3362

markable feature (TOCDEV-3362)

---

packages/tocco-ui/src/Menu/Menu.js
packages/tocco-ui/src/Menu/StyledComponents.js

Refs: TOCDEV-3884
Changelog: Prevent dropdown menu being clipped in viewport

refactor(tocco-ui): prevent menu clipping

---

packages/merge/src/main.js

fix(merge): fix notifications

---

packages/entity-list/src/components/SearchFilterList/StyledComponents.js
packages/tocco-ui/src/Menu/BallMenu.js
packages/tocco-ui/src/Menu/StyledComponents.js
packages/tocco-ui/src/Menu/index.js
packages/tocco-ui/src/index.js

Refs: TOCDEV-3943
Changelog: Fix search filter menu hover

refactor(tocco-ui): fix search filter menu hover

---

packages/tocco-ui/src/EditableValue/typeEditors/StyledLocationEdit.js

Refs: TOCDEV-3746
Changelog: Style location edit dropdown to match other dropdowns

refactor(tocco-ui): style location edit dropdown

---

packages/app-extensions/src/actions/components/ReportSettings.js

Refs: TOCDEV-3945
Changelog: Remove download icon inside button of report settings

refactor(app-extensions): remove button icon

---

packages/admin/src/components/Header/NotificationCenterButton.js
packages/admin/src/components/Header/NotificationCenterRedDot.js
packages/admin/src/components/Header/StyledComponents.js

Refs: TOCDEV-3946
Changelog: Adjust notification dot position

refactor(admin): adjust dot position

---

packages/entity-browser/README.md
packages/entity-browser/src/main.js

feat(entity-browser): allow entity-browser to run with specific bu

---

packages/app-extensions/src/actions/components/ReportSettings.js
packages/app-extensions/src/actions/components/ReportSettings.spec.js

refactor(app-extensions): refactor class component

---

.github/workflows/auto_pr.yml
scripts/cherrypick.sh
scripts/release-package.sh

chore: add auto pr action

---

packages/app-extensions/src/notification/modules/modal/ModalDisplay/StyledComponents.js

Refs: TOCDEV-3987
Changelog: Increase z-index of modal holder to properly display as widget

refactor(app-extensions): fix modal holder z-index

---

packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/StyledComponents.js

Refs: TOCDEV-3987
Changelog: Increase toaster z-index to properly display as widget

refactor(app-extensions): fix toaster z-index

---

packages/app-extensions/src/notifier/components/Notifier.js

Refs: TOCDEV-3996
Changelog: Fix notifier toasters disappearing behind header

refactor(app-extension): fix notifier in dms

---

scripts/cherrypick.sh
scripts/tagging.sh

../github appears to be kept across pipelines. Move it somewhere
were this isn't the case.

chore: adjust GitLab CI scripts for our own runnerrs

---

packages/admin/src/routes/entities/components/RelationsView/ListView.js
packages/entity-list/src/main.js

Refs: TOCDEV-3795
Changelog: Refresh list on navigation back to list

refactor(entity-list): reload list on store reload

---

packages/tocco-ui/src/FormattedValue/typeFormatters/HtmlFormatter.js
packages/tocco-ui/src/StatedValue/StyledStatedValue.js

Refs: TOCDEV-3984
Changelog: Harmonize html formatter spacing inside stated value

refactor(tocco-ui): harmonize html formatter spacing

---

packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js
packages/app-extensions/src/notification/components/NotificationBody/StyledComponents.js

Refs: TOCDEV-4020
Changelog: Harmonize icon spacing and hover behaviour in notifications

refactor(app-extensions): harmonize spacing and hover

---

build/webpack.config.js

- with the update of webpack to version 5.x a hidden problem was introduced.
There is a problem with  multiple webpack-compiled files loaded on the same page. Like in nice2.
They would overwrite themself in an internal webpack caching util.
Therefore the library name is needed.
Refs: TOCDEV-3998

chore: fix build

---

packages/app-extensions/src/notification/modules/modal/ModalDisplay/ModalContent.js

Refs: TOCDEV-3939
Changelog: Add the feature to close modals via escape key

refactor(app-extensions): add feature to close modal via esc

---

packages/tocco-ui/src/AdminLink/linkStyle.js

Refs: TOCDEV-4081
Changelog: Add underline to links

refactor(tocco-ui): change link style

---

packages/tocco-ui/src/FormattedValue/typeFormatters/UrlFormatter.js

- prevent event propagation
Changelog: Open Url in list in new window
Refs: TOCDEV-3933

refactor(tocco-ui): open url in new window

---

packages/app-extensions/src/form/formDefinition.js
packages/app-extensions/src/form/formDefinition.spec.js

Changelog: Fix simple-search extend button in remote search
Refs: TOCDEV-3983

refactor(app-extensions): ignore hidden fields

---

packages/tocco-ui/src/Breadcrumbs/Breadcrumbs.js

Refs: TOCDEV-3990
Changelog: Improve browser tab title

refactor(tocco-ui): support currentViewTitle for title

---

packages/tocco-ui/src/Layout/StyledLayoutBox.js
packages/tocco-ui/src/Layout/StyledLayoutContainer.js
packages/tocco-ui/src/Panel/Panel.spec.js
packages/tocco-ui/src/Panel/PanelBody.js
packages/tocco-ui/src/Panel/PanelHeaderFooter.js
packages/tocco-ui/src/Panel/PanelHeaderFooter.spec.js
packages/tocco-ui/src/Panel/StyledPanel.js
packages/tocco-ui/src/Panel/StyledPanelBody.js
packages/tocco-ui/src/Panel/StyledPanelHeaderFooter.js

Refs: TOCDEV-4083
Changelog: Harmonize collapsible panel styling for better contrast

refactor(tocco-ui): harmonize panel styling

---

packages/tocco-ui/src/Menu/MenuItem.js
packages/tocco-ui/src/Menu/StyledComponents.js

Refs: TOCDEV-4089
Changelog: Prevent early line breaks in popover menu

refactor(tocco-ui): prevent line break in menu

---

packages/app-extensions/src/notification/components/NotificationBody/StyledComponents.js

Refs: TOCDEV-4081
Changelog: Remove initial underline in notification detail link

refactor(app-extensions): remove text-decoration

---

packages/entity-list/src/components/Table/NavigationCellHeader.js
packages/entity-list/src/components/Table/Table.js
packages/entity-list/src/containers/TableContainer.js
packages/entity-list/src/modules/list/actions.js
packages/entity-list/src/modules/list/reducer.js
packages/entity-list/src/modules/list/sagas.js
packages/entity-list/src/util/api/forms.js
packages/tocco-util/src/mockData/data/dummy_entity_list_form.json

- read and store property
- add mock data
Changelog: support disablePreferencesMenu in table
Refs: TOCDEV-3992

refactor(entity-list):  support disablePreferencesMenu

---

packages/app-extensions/src/field/editableTypeConfigs/moneyamount.js
packages/app-extensions/src/field/formattedTypeConfigs/moneyamount.js

Refs: TOCDEV-4094
Changelog: Money post point digits fallback

refactor(app-extensions): set money default value

---

packages/tocco-ui/package.json
packages/tocco-ui/src/Select/Select.js
packages/tocco-ui/yarn.lock

- because of a bug that triggered the onMenuOpen function on input change the react select was flickering
- handle empty search input when
Refs: 	TOCDEV-4079
Changelog: Update select

refactor(tocco-ui): update react select

---

packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js

Refs: TOCDEV-4005
Changelog: add "open output job" to notification

feat(app-extensions): add "open output job" to notification

---

packages/tocco-ui/src/EditableValue/typeEditors/IntegerEdit.js

feat(tocco-ui): allow negative integers

---

packages/app-extensions/src/notification/api.js
packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/NotificationCenter.js

feat(app-extensions): do not show deleted output job notifications

---

packages/delete/src/components/Dialog/Dialog.js

Disable delete button

---

packages/app-extensions/src/notification/modules/center/NotificationCenter/Notification.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/StyledComponents.js

Refs: TOCDEV-3801
Changelog: Add background color to unread notifications

feat(app-extensions): color unread notification differently

---

packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js
packages/app-extensions/src/notification/types.js

Refs: TOCDEV-3999
Changelog: fix opening task execution of notification

fix(app-extensions): fix opening task execution of notification

---

packages/app-extensions/src/notification/modules/socket/actions.js
packages/app-extensions/src/notification/modules/socket/sagas.js
packages/app-extensions/src/notification/modules/socket/sagas.spec.js
packages/app-extensions/src/notification/modules/socket/socket.js
packages/app-extensions/src/notification/modules/socket/socket.spec.js
packages/app-extensions/src/socket/index.js
packages/app-extensions/src/socket/socket.js
packages/app-extensions/src/socket/socket.spec.js
packages/devcon/src/routes/devcon/components/DevCon/DevCon.js
packages/devcon/src/routes/devcon/components/DevCon/StyledDevCon.js
packages/devcon/src/routes/index.js
packages/devcon/src/routes/log/components/LogTable/ExceptionDetails.js
packages/devcon/src/routes/log/components/LogTable/LogEntry.js
packages/devcon/src/routes/log/components/LogTable/LogTable.js
packages/devcon/src/routes/log/components/LogTable/LogTableContainer.js
packages/devcon/src/routes/log/components/LogTable/StyledLogEntry.js
packages/devcon/src/routes/log/components/LogTable/index.js
packages/devcon/src/routes/log/components/LogView/LogView.js
packages/devcon/src/routes/log/components/LogView/index.js
packages/devcon/src/routes/log/index.js
packages/devcon/src/routes/log/modules/actions.js
packages/devcon/src/routes/log/modules/index.js
packages/devcon/src/routes/log/modules/reducer.js
packages/devcon/src/routes/log/modules/sagas.js
packages/devcon/src/routes/log/route.js

Devcon logging

---

packages/tocco-ui/src/FormattedValue/typeFormatters/DocumentCompactFormatter.js
packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json
packages/tocco-ui/src/Upload/SyledUploadInput.js
packages/tocco-ui/src/Upload/UploadInput.js
packages/tocco-ui/src/Upload/View.js

Refs: TOCDEV-4198
Changelog: Swap out donwload and upload icons to harmonize look

refactor(tocco-ui): swap out download/upload icons

---

packages/scheduler/src/components/NavigationFullCalendar/NavigationFullCalendar.js
packages/scheduler/src/components/NavigationFullCalendar/NavigationFullCalendar.spec.js
packages/tocco-ui/src/utilStyles/interactiveStyling.js

Refs: TOCDEV-4099
Changelog: Harmonize button color of calendar navigation

refactor(scheduler): adapt navigation button color

---

packages/tocco-ui/src/DatePicker/GlobalDatePickerStyles.js

Refs: TOCDEV-4136
Changelog: Change date picker month button color for better visibility

refactor(tocco-ui): change date picker buttons

---

packages/admin/src/components/Header/NotificationCenterButton.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/Notification.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/NotificationCenter.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/StyledComponents.js

Refs: TOCDEV-4195
Changelog: Harmonize notification center styling

refactor(app-extensions): harmonize notification center styling

---

packages/devcon/src/routes/devcon/components/DevCon/DevCon.js
packages/devcon/src/routes/index.js
packages/devcon/src/routes/modelvalidation/components/ChangelogDialog/ChangelogDialog.js
packages/devcon/src/routes/modelvalidation/components/ChangelogDialog/ChangelogDialogContainer.js
packages/devcon/src/routes/modelvalidation/components/ChangelogDialog/index.js
packages/devcon/src/routes/modelvalidation/components/CheckEvents/CheckEventGroup.js
packages/devcon/src/routes/modelvalidation/components/CheckEvents/CheckEvents.js
packages/devcon/src/routes/modelvalidation/components/CheckEvents/CheckEventsContainer.js
packages/devcon/src/routes/modelvalidation/components/CheckEvents/StyledCheckEvents.js
packages/devcon/src/routes/modelvalidation/components/CheckEvents/index.js
packages/devcon/src/routes/modelvalidation/components/ModelValidationView/ModelValidationView.js
packages/devcon/src/routes/modelvalidation/components/ModelValidationView/index.js
packages/devcon/src/routes/modelvalidation/components/SqlDialog/SqlDialog.js
packages/devcon/src/routes/modelvalidation/components/SqlDialog/SqlDialogContainer.js
packages/devcon/src/routes/modelvalidation/components/SqlDialog/index.js
packages/devcon/src/routes/modelvalidation/components/ValidationProgress/ProgressBar.js
packages/devcon/src/routes/modelvalidation/components/ValidationProgress/StyledProgressBar.js
packages/devcon/src/routes/modelvalidation/components/ValidationProgress/ValidationProgress.js
packages/devcon/src/routes/modelvalidation/components/ValidationProgress/ValidationProgressContainer.js
packages/devcon/src/routes/modelvalidation/components/ValidationProgress/index.js
packages/devcon/src/routes/modelvalidation/index.js
packages/devcon/src/routes/modelvalidation/modules/actions.js
packages/devcon/src/routes/modelvalidation/modules/index.js
packages/devcon/src/routes/modelvalidation/modules/reducer.js
packages/devcon/src/routes/modelvalidation/modules/sagas.js
packages/devcon/src/routes/modelvalidation/route.js

Features:
- execute model validation (progress is shown)
- see all validation errors
- generate and execute SQL statements to fix errors (a.k.a. "try fix"
from former DevCon)
- generate liquibase changesets to fix errors
Refs: TOCDEV-3951

feat(devcon): Add simple model validation view

---

packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js
packages/app-extensions/src/notification/components/NotificationBody/StyledComponents.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/Notification.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/NotificationCenter.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/NotificationCenterContainer.js
packages/app-extensions/src/notification/modules/center/actions.js
packages/app-extensions/src/notification/modules/center/sagas.js
packages/app-extensions/src/notification/modules/socket/socket.js
packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/Toaster.js
packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/ToasterDisplay.js
packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/ToasterDisplayContainer.js
packages/app-extensions/src/notification/types.js

add button to cancle tasks from notifications

---

packages/app-extensions/src/login/sagas.js

feat(app-extensions): check cached business unit on session check

---

packages/tocco-ui/src/Table/StyledTable.js

Refs: TOCDEV-4238
Changelog: Change table hover colors to a more generic grey tone

refactor(tocco-ui): change table hover

---

packages/docs-browser/src/components/DocsView/StyledComponents.js

Refs: TOCDEV-4066
Changelog: Change icon size within docs-browser

refactor(docs-browser): change icon size

---

packages/admin/src/routes/entities/utils/navigationStrategy.js
packages/tocco-ui/src/AdminLink/linkStyle.js
packages/tocco-ui/src/FormattedValue/typeFormatters/UrlFormatter.js
packages/tocco-ui/src/Link/StyledLink.js

Refs: TOCDEV-4100
Changelog: Harmonize link styling to be consistent

refactor(tocco-ui): adapt underline style

---

packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js

Refs: TOCDEV-4250
Changelog: Increase min-height of filter panel in search form

refactor(entity-list): change min size of panel

---

packages/admin/src/components/AboutTocco/AboutToccoContainer.js

Refs: TOCDEV-4245
Changelog: fix about tocco

fix(admin): fix about tocco

---

packages/tocco-ui/src/Select/IndicatorsContainer.js
packages/tocco-ui/src/Select/Select.spec.js

fix(tocco-ui): hide remote create when field is disabled

---

packages/app-extensions/src/field/editableTypeConfigs/remote.js

Refs: TOCDEV-4244, TOCDEV-4261

fix(app-extension): add default value to createPermission

---

package.json
packages/entity-detail/src/components/ErrorItems/ErrorItems.js
packages/entity-detail/src/modules/entityDetail/sagas.js
yarn.lock

fix(entity-detail): unescape html entities from validator messages

---

packages/admin/src/routes/entities/components/DocsView/DocsView.js

Refs: TOCDEV-4263
Changelog: fix entity docs url

fix(admin): fix entity docs url

---

packages/tocco-ui/src/Table/ResizingController.js
packages/tocco-ui/src/Table/StyledTable.js

Refs: TOCDEV-4286
Changelog: Improve table hover colors for better readability

refactor(tocco-ui): adjust table hover colors

---

packages/tocco-ui/src/Popover/StyledPopover.js

Refs: TOCDEV-4287
Changelog: Change popover text color of paragraphs to white

refactor(tocco-ui): change text color

---

packages/input-edit/src/components/InputEditTable/StyledComponents.js

Refs: TOCDEV-4278
Changelog: Improve text input UX within input edit table

refactor(input-edit): improve input ux

---

packages/app-extensions/src/notification/modules/center/NotificationCenter/NotificationCenter.js

Refs: TOCDEV-4297
Changelog: Reduce notification center title size

refactor(app-extensions): change title size

---

packages/entity-detail/src/modules/entityDetail/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.spec.js

feat(entity-detail): run auto-complete on change as well

---

packages/app-extensions/src/rest/rest.js
packages/app-extensions/src/rest/rest.spec.js

feat(app-extensions): allow request endpoints to start with a slash

---

packages/app-extensions/src/form/formDefinition.js
packages/app-extensions/src/form/formDefinition.spec.js

fix(app-extensions): make falsy default values work

---

packages/login/src/login.stories.js

Correct default data for storybook to fix failing cypress test

test(login): fix failing cypress test

---

packages/admin/src/modules/navigation/sagas.js
packages/admin/src/modules/preferences/sagas.js

fix(admin): do not send multiple requests to save preferences

---

packages/entity-detail/src/modules/entityDetail/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.spec.js

- remove onBlur since it is no longer necessary with onChange
Refs: TOCDEV-4391

fix(entity-detail): debounce auto complete

---

packages/entity-detail/src/components/DetailForm/DetailForm.js

fix(entity-detail): don't fire touched when nothing is touched

---

packages/tocco-ui/src/TextareaAutosize/StyledComponents.js

Changelog: show textarea bigger for better distinction
Refs: TOCDEV-4339

feat(tocco-ui): show textarea bigger for better distinction

---

packages/entity-list/src/components/Table/Table.js
packages/entity-list/src/containers/TableContainer.js
packages/tocco-ui/src/Pagination/Pagination.js
packages/tocco-ui/src/Pagination/Pagination.spec.js
packages/tocco-ui/src/Table/StyledTable.js
packages/tocco-ui/src/Table/Table.js
packages/tocco-ui/src/Table/Table.stories.js
packages/tocco-ui/src/Table/TableFooter.js
packages/tocco-util/src/dragAndDrop/useDnD.spec.js

added refresh button for reloading page data with keeping filter and current page
Changelog: table can be refreshed
Refs:TOCDEV-4290

feat(tocco-ui): table can be refreshed

---

packages/entity-list/src/components/SelectionController/SelectionController.js

fix(entity-list): always allow return to overview in list

---

packages/admin/src/components/Navigation/menuType/MenuEntry.js
packages/admin/src/components/Navigation/menuType/StyledComponents.js
packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json

Changelog: show menu item icons
Refs: TOCDEV-4407

feat(admin): show menu item icons

---

packages/entity-detail/src/components/DetailFooter/DetailFooterFull.js
packages/entity-detail/src/components/DetailFooter/DetailFooterReduced.js
packages/entity-detail/src/components/DetailFooter/StyledComponents.js

Refs: TOCDEV-4322
Changelog: harmonize detail footer spacing

refactor(entity-detail): harmonize detail footer spacing

---

packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
packages/entity-list/src/components/AdminSearchForm/StyedComponents.js

Refs: TOCDEV-4472
Changelog: fix placing of chevron icon in placeholder panel of admin search form

refactor(entity-list): fix icon in placeholder-panel

---

packages/tocco-ui/src/Select/SingleValue.js
packages/tocco-ui/src/Select/StyledComponents.js
packages/tocco-ui/yarn.lock

Refs: TOCDEV-4462
Changelog: fix missing popover in single values and overflowing in firefox

refactor(tocco-ui): fix missing popover and overflow

---

packages/tocco-ui/src/StatedValue/StyledStatedValue.js

Refs: TOCDEV-4487
Changelog: remove floating label animation to improve performance in firefox

refactor(tocc-ui): remove floating label animation

---

packages/app-extensions/src/field/formattedTypeConfigs/remote.js
packages/app-extensions/src/field/index.js
packages/entity-list/src/util/fieldFactory.js
packages/tocco-ui/src/FormattedValue/typeFormatters/SingleSelectFormatter.js

Changelog: add tooltip for remote fields
Refs: TOCDEV-4389

feat(tocco-ui): add tooltip for remote fields

---

packages/input-edit/src/components/InputEditTable/InputEditTable.js

Changelog: fix dnd in input edit
Refs: TOCDEV-4470

fix(input-edit): fix dnd in input edit

---

packages/dashboard/src/components/InfoBox/typeContent/InfoBoxSearchFilterContent.js
packages/dashboard/src/components/InfoBox/typeContent/InfoBoxSearchFilterContent.spec.js

Changelog: fix dashboard searchfilter

fix(dashboaord): fix dashboard searchfilter

---

packages/admin/src/components/MenuTree/StyledComponents.js
packages/admin/src/components/Navigation/Navigation.js
packages/admin/src/components/Navigation/StyledComponents.js
packages/admin/src/components/Navigation/menuType/MenuEntry.js

Refs: TOCDEV-4480
Changelog: harmonize navigation spacing and collapse button focus style

refactor(admin): adjust navigation spacing

---

packages/admin/src/components/MenuTree/StyledComponents.js
packages/admin/src/components/Navigation/StyledComponents.js

Refs: TOCDEV-4542
Changelog: position collapse buttons in absolute fashion to prevent jumps when scrollbar appears

refactor(admin): position collapse

---

packages/app-extensions/src/notification/modules/modal/ModalDisplay/StyledComponents.js

Refs: TOCDEV-4545
Changelog: adjust z-index of modal to prevent legacy actions falling behind it

refactor(app-extensions): adjust z-index

---

packages/admin/src/components/MenuTree/StyledComponents.js

Refs: TOCDEV-4480
Changelog: harmonize menu entry padding for cleaner left alignment

refactor(admin): harmonize menu entry padding

---

packages/admin/src/components/Navigation/Navigation.js
packages/admin/src/components/Navigation/StyledComponents.js

Refs: TOCDEV-4559
Changelog: harmonize navigation tab spacing and sizing

refactor(admin): harmonize navigation tabs

---

packages/tocco-ui/src/EditableValue/typeEditors/LocationEdit.js
packages/tocco-ui/src/EditableValue/typeEditors/StyledLocationEdit.js

Refs: TOCDEV-4390
Changelog: adjust min width of location edit postcode field and refactor component

refactor(tocco-ui): adjust minimum postcode field width

---

packages/admin/src/routes/entities/modules/path/sagas.js

- check if relation entity exists instead of parent entity
- fixes error handling for non-existent relation entity
Changelog: handle-non-existent relation entity gracefully

fix(admin): handle non-existent relation entity gracefully

---

package.json
packages/entity-detail/src/components/ErrorItems/ErrorItems.js
yarn.lock

Changelog: fix html in toaster message
Refs: TOCDEV-4248, TOCDEV-4540

fix(entity-detail): fix html in toaster message

---

packages/tocco-util/src/tqlBuilder/tqlBuilder.js

Changelog: tql builder support login type
Refs: TOCDEV-3923

fix(tocco-util): tql builder support login type

---

packages/admin/src/components/Navigation/menuType/MenuChildrenWrapper.js

Refs: TOCDEV-4543
Changelog: fix menu navigation with arrow keys when some groups were collapsed

fix(admin): remove hidden menu entries from DOM

---

packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/Toaster.js
packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/ToasterDisplay.js
packages/tocco-util/src/react/useUserActive.js

Refs: TOCDEV-4376
Changelog: change toaster behavior to stay on hover and refactor ToasterDisplay

refactor(app-extensions): change toaster behavior

---

packages/app-extensions/src/actions/modules/actionHandlers/simpleAction.js

Refs: TOCDEV-3782
Changelog: remove X-Enable-Notifications header

refactor(app-extensions): remove X-Enable-Notifications header

---

packages/tocco-theme/README.md
packages/tocco-theme/src/ToccoTheme/defaultTheme.js
packages/tocco-ui/src/Popover/StyledPopover.js

Refs: TOCDEV-4580
Changelog: harmonize popover background color and spacing

refactor(tocco-ui): harmonize color/spacing in popover

---

packages/tocco-ui/src/FormattedValue/typeFormatters/DocumentCompactFormatter.js

Refs: TOCDEV-4474
Cherrypick: up

feat(tocco-ui): remove DocumentCompactFormatter Popover

---

packages/entity-browser/src/dev/input-no-mock.json
packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json

Changelog: register more icons

feat(tocco-ui): register icons

---

packages/input-edit/src/components/InputEdit/InputEdit.js
packages/input-edit/src/components/InputEdit/StyledInputEdit.js

Refs: TOCDEV-4571
Changelog: add panel collapse feature to input edit

refactor(input-edit): add panel collapse feature

---

packages/app-extensions/src/notification/modules/center/NotificationCenter/NotificationCenter.js
packages/app-extensions/src/notification/modules/center/NotificationCenter/StyledComponents.js

cherry-pick: up
Refs: TOCDEV-4628
Changelog: change notification title and refactor NotificationCenter

refactor(app-extensions): change notification title

---

packages/app-extensions/README.md
packages/app-extensions/src/notification/README.md
packages/docs-browser/src/modules/chooseDocument/README.md

docs: add documentation for addToStore

---

packages/admin/src/main.js
packages/app-extensions/src/intl/intl.js
packages/app-extensions/src/intl/intl.spec.js
packages/tocco-util/src/mockData/textResource.js

refactor: replace textresources regex with comma-separated list

---

packages/dashboard/src/components/Dashboard/Dashboard.js
packages/tocco-ui/src/Table/StyledTable.js

Refs: TOCDEV-4637
Changelog: reintroduce table min-height and refactor Dashboard.js

refactor(tocco-ui): reset table min-height

---

packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/tocco-ui/src/Icon/mapping.json

Changelog: register more icons
Refs: TOCDEV-4639

feat(tocco-ui): register more icons

---

packages/dashboard/src/components/Dashboard/DashboardColumn.js
packages/dashboard/src/components/Dashboard/StyledComponents.js
packages/dashboard/src/components/InfoBoxSettings/InfoBoxSettings.js

cherry: pick-up
Refs: TOCDEV-4651
Changelog: add scrollbar to dashboard panel and refactor dashboard components

refactor(dashboard): add scrollbar

---

packages/app-extensions/src/appFactory/App.js
packages/app-extensions/src/appFactory/appFactory.js
packages/login/src/LoginApp.js
packages/login/src/PasswordUpdateApp.js
packages/login/src/main.js

refactor(login): refactor login app

---

packages/docs-browser/src/modules/chooseDocument/sagas.js

Refs: TOCDEV-4547
Changelog: fix docs-browser height inside modal

refactor(docs-browser): fix docs-browser modal

---

package.json
packages/admin/src/components/Admin/Admin.js
packages/admin/src/components/Admin/StyledComponents.js
packages/tocco-ui/src/BurgerButton/BurgerButton.js
packages/tocco-ui/src/BurgerButton/BurgerButton.stories.js
packages/tocco-ui/src/BurgerButton/StyledComponents.js
packages/tocco-ui/src/BurgerButton/framerMotionFeatures.js
packages/tocco-ui/src/Panel/framerMotionFeatures.js
yarn.lock

Refs: TOCDEV-4724
Changelog: remove framer-motion dependency for burger button and create pure css version instead

refactor(tocco-ui): build pure css burger button

---

packages/admin/src/components/Header/Header.js
packages/admin/src/utils/docsUtils.js
packages/admin/src/utils/docsUtils.spec.js

Changelog: correct link to user manual

fix(admin): correct link to user manual for >= 3.0 releases

---

packages/admin/src/components/Navigation/Navigation.js
packages/admin/src/modules/navigation/actions.js
packages/admin/src/modules/navigation/sagas.js
packages/admin/src/modules/navigation/sagas.spec.js
packages/admin/src/shortcuts.js
packages/admin/src/utils/navigationUtils.js

Changelog: remove empty menus
Refs: TOCDEV-4576

feat(admin): remove empty menus

---

scripts/tagging.sh

fix: tagging script increase depth

---

packages/admin/src/components/Admin/Admin.js
packages/admin/src/components/Admin/StyledComponents.js

Refs: TOCDEV-4741
Changelog: adjust viewport height calculation to correctly render when entering fullscreen mode on android chrome

refactor(admin): adjust viewport height rendering

---

packages/app-extensions/src/notification/README.md
packages/app-extensions/src/notification/notification.stories.mdx
packages/entity-detail/src/modules/entityDetail/sagas.js

docs: update toaster documentation

---

packages/tocco-ui/src/Panel/StyledPanelHeaderFooter.js

Changelog: fix flicker in Firefox on panel hovers
Refs: TOCDEV-4581

fix(tocco-ui): fix flicker in Firefox on panel hovers

---

packages/admin/src/components/AboutTocco/AboutTocco.js

Refs: TOCDEV-4627
Changelog: add admin package version info to about modal

refactor(admin): add package info to about

---

packages/entity-detail/src/modules/entityDetail/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.spec.js
packages/tocco-util/src/api/display.js
packages/tocco-util/src/api/display.spec.js

Changelog: do not load display of null entity

fix(tocco-util, entity-detail): do not load display of null entity

---

.eslintrc

- code already formatted like that
- only enfore by adding eslint-rule

chore: add newline needed eslint rule

---

packages/widget-utils/README.md
packages/widget-utils/package.json
packages/widget-utils/src/bootstrap/bootstrapWidgets.js
packages/widget-utils/src/bootstrap/bootstrapWidgets.spec.js
packages/widget-utils/src/bootstrap/constants.js
packages/widget-utils/src/bootstrap/requests.js

- widget is configured in the admin
- the boostrap script gets the widget config by the key
- the key is added as data attribute
- widget gets initialized based on fetched config
Changelog: initialize widget with widget config
Refs: TOCDEV-4748

feat(widget-utils): initialize widget with widget config

---

packages/tocco-ui/src/EditableValue/StyledEditableValue.js
packages/tocco-ui/src/EditableValue/typeEditors/DurationEdit.js
packages/tocco-ui/src/EditableValue/typeEditors/DurationEdit.spec.js
packages/tocco-ui/src/EditableValue/typeEditors/StyledDurationEdit.js

Refs: TOCDEV-4754
Changelog: harmonize DuratioEdit spacing and refactor class based component to functional component

refactor(tocco-ui): adjust DurationEdit spacing

---

packages/widget-utils/src/bootstrap/bootstrapWidgets.js
packages/widget-utils/src/bootstrap/bootstrapWidgets.spec.js
packages/widget-utils/src/bootstrap/remoteLogger.js
packages/widget-utils/src/bootstrap/utils.js

- handle all kinds of errors while initializing the widgets
- try to log errors on remote
Changelog: handle errors and log to remote
Refs: TOCDEV-4757

feat(widget-utils): handle errors and log to remote

---

packages/login/src/components/PasswordRequest/PasswordRequest.js
packages/login/src/components/PasswordRequest/PasswordRequest.spec.js

refactor(login): refactor password request

---

packages/widget-config-edit/package.json
plop/templates/package/package.json

a private package is not released

chore: set package per default to private

---

packages/app-extensions/src/form/asyncValidation.js
packages/app-extensions/src/rest/request.js
packages/app-extensions/src/rest/rest.js
packages/merge/src/modules/merge/sagas.js
packages/merge/src/modules/merge/sagas.spec.js

feat(app-extensions): set custom client type for rest requests

---

packages/admin/src/components/Navigation/menuType/StyledComponents.js
packages/tocco-ui/src/Button/StyledRouterLinkButton.js

refactor(tocc-ui): reset nice2 link overwrites

---

packages/app-extensions/src/notification/modules/toaster/ToasterDisplay/StyledComponents.js

Refs: TOCDEV-4907
Changelog: change toaster to fixed positioning to guarantee visibility on scroll

refactor(app-extensions): fix toaster positioning

---

packages/tocco-util/src/dragAndDrop/useDnD.js

Refs: TOCDEV-4414
Changelog: improve DnD performance

fix(tocco-util): improve DnD performance

---

packages/tocco-ui/src/Table/StyledTable.js

Refs: TOCDEV-4925
Changelog: increase table style specificities to prevent them from being overwritten inside widgets

refactor(tocco-ui): increase specificity

---

packages/tocco-ui/src/Select/Select.js

refactor(tocco-ui): remove throttle dependancy

---

packages/dashboard/src/components/Dashboard/Dashboard.js
packages/dashboard/src/modules/dashboard/reducer.js
packages/dashboard/src/modules/dashboard/reducer.spec.js

Refs: TOCDEV-4865
Changelog: show loading mask while fetching info-boxes

feat(dashboard): show loading mask while fetching info-boxes

---

packages/docs-browser/src/modules/chooseDocument/StyledComponents.js
packages/docs-browser/src/modules/chooseDocument/sagas.js

Refs: TCODEV-4547
Changelog: align choose document button to the right

refactor(docs-browser): align choose document button

---

packages/entity-list/src/components/AdminSearchForm/QueryView.js

Refs: TOCDEV-4806
Changelog: The model field in the QueryView is now a display.

style(entity-list): change model in query view to display

---

packages/tocco-ui/src/Select/Select.js

Refs: TOCDEV-5003
Changelog: Fixed searching in select boxes. Removed default searchOptions from Select.

fix(tocco-ui): fix filtering of select boxes

---

packages/app-extensions/src/appFactory/App.js
packages/app-extensions/src/appFactory/styles.css

refactor(app-extensions): reintroduce font css

---

package.json
scripts/tag-all-packages.sh

Refs: TOCDEV-5015
Changelog: added script to tag all packages with current release tag

feat: create tag-all-packages

---

packages/entity-list/src/components/SearchFilterList/SearchFilterList.js

Changelog: searchfilter show description as mouseover
Refs: TOCDEV-4929

feat(entity-list): searchfilter show description as mouseover

---

scripts/release-package.sh

fix: fix syntax

---

packages/two-factor-connector/src/modules/sagas.js
packages/two-factor-connector/src/modules/sagas.spec.js

Changelog: fix activating two factor without session
Refs: TOCDEV-5034

fix(two-factor-connector): fix activating two factor without session

---

packages/admin/src/components/Header/Header.js
packages/admin/src/components/Header/HeaderContainer.js

Refs: TOCDEV-4936
Changelog: menu now closes when navigating to the dashboard

feat(admin): close menu when navigating to dashboard

---

packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js

Changelog: legacy actions ignore some exceptions
Refs: TOCDEV-5058

fix(app-extensions): legacy actions ignore some exceptions

---

packages/admin/src/components/MenuTree/MenuTree.js
packages/admin/src/components/MenuTree/StyledComponents.js
packages/admin/src/components/Navigation/Navigation.js

- show search results over all items on menu when nothing
has beend found on active menu tab
Changelog: improve menu search result handling
Refs: TOCDEV-4915

feat(admin): improve menu search result handling

---

packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
packages/docs-browser/src/modules/chooseDocument/sagas.js
packages/entity-list/src/components/AdminSearchForm/QueryView.js
packages/entity-list/src/modules/list/reducer.spec.js
packages/tocco-ui/src/Select/Select.js

style: fix prettier

---

.gitlab-ci.yml

fix: add missing coverage artifacts to gitlab_ci.yml

---

packages/tocco-ui/package.json
packages/tocco-ui/src/Select/Menu.js
packages/tocco-ui/yarn.lock

Refs: TOCDEV-5022
Changelog: update react-tether dependency and change Menu.js to new method

refactor(tocco-ui): update react-tether

---

packages/entity-browser/src/components/EntityDetail/DetailLinkRelative.js
packages/entity-browser/src/components/EntityDetail/EntityDetail.js
packages/entity-detail/src/components/DetailView/DetailView.js

Refs: TOCPROD-41
Changelog: convert entity-detail class compomeents to functional components

refactor(entity-detail): convert to func comp

---

.gitlab-ci.yml

chore: run prettier format check as ci job

---

packages/core/entity-detail/src/main.js
packages/core/entity-detail/src/modules/entityDetail/reducer.js
packages/core/entity-detail/src/modules/entityDetail/reducer.spec.js

Changelog: fix entity-browser create new form

fix: fix default value for defaultValues

---

packages/app-extensions/src/appFactory/index.js
packages/app-extensions/src/appFactory/useApp.js
packages/entity-list/src/main.js

Refs: TOCDEV-5119
Changelog: fix entity-list re-init handling on store updates

fix(entity-list): fix update store on entity-list

---

packages/apps/admin/package.json
packages/apps/admin/src/components/Navigation/Navigation.js
packages/apps/admin/yarn.lock

Refs: TOCDEV-5018
Changelog: update react-burger-menu and fix input focus

refactor(admin): update react-burger-menu

---

packages/core/tocco-ui/src/StatedValue/StyledStatedValue.js

Refs: TOCDEV-5154
Changelog: harmonize error list spacing within forms

refactor(tocco-ui): harmonize error list spacing

---

packages/tocco-ui/src/Range/Range.js

Changelog: update range values properly
Refs: TOCDEV-5176

fix(tocco-ui): update range values properly

---

packages/core/tocco-ui/src/Select/Menu.js

Refs: TOCDEV-3699
Changelog: constrain tether to parent element to prevent z-index problems inside modal

refactor(tocco-ui): constrain styled tether

---

packages/core/app-extensions/src/notification/modules/toaster/ToasterDisplay/Toaster.js
packages/core/tocco-ui/src/Icon/FontAwesomeAdapter.js

Refs: TOCDEV-5190
Changelog: add hasFixedWidth prop to harmonize spacing if necessary

refactor(tocco-ui): add hasFixedWidth prop

---

packages/core/tocco-ui/src/EditableValue/typeEditorFactory.js
packages/core/tocco-ui/src/EditableValue/typeEditors/DateEdit.js
packages/core/tocco-ui/src/EditableValue/typeEditors/DatePicker.js
packages/core/tocco-ui/src/EditableValue/typeEditors/DateTimeEdit.js
packages/core/tocco-ui/src/EditableValue/typeEditors/IntegerEdit.js
packages/core/tocco-ui/src/EditableValue/typeEditors/StyledDatePicker.js
packages/core/tocco-ui/src/Range/Range.js

Changelog: show from and to placeholders on ranges
Refs: TOCDEV-5189

feat(tocco-ui): show from and to placeholders on ranges

---

packages/actions/resource-scheduler/src/components/ResourceScheduler/ResourceScheduler.js
packages/actions/resource-scheduler/src/components/ResourceScheduler/StyledComponents.js

Refs: TOCDEV-5187
Changelog: add collapse feature to resource-scheduler

refactor(resource-scheduler): add collapse feature

---

packages/core/entity-list/src/components/AdminSearchForm/QueryView.js
packages/core/entity-list/src/components/AdminSearchForm/SearchView.js
packages/core/entity-list/src/components/AdminSearchForm/StyedComponents.js

Refs: TOCDEV-5110
Changelog: add collapse feature to tql view in entity-list

refactor(entity-list): add collapse feature

---

packages/core/tocco-ui/src/DatePicker/useDatePickr.js

Refs: TOCDEV-5249
Changelog: fix date picker modal position

fix(tocco-ui): fix date picker modal position

---

packages/actions/resource-scheduler/changelog.md
packages/actions/resource-scheduler/package.json
packages/apps/admin/changelog.md
packages/apps/admin/package.json
packages/widgets/docs-browser/changelog.md
packages/widgets/docs-browser/package.json
packages/widgets/entity-browser/changelog.md
packages/widgets/entity-browser/package.json

- tocco-docs-browser@1.0.12
- tocco-entity-browser@1.0.11
- tocco-resource-scheduler@1.0.8
- tocco-admin@1.0.26

chore: release packages

---

packages/apps/admin/src/components/MenuTree/MenuTree.js
packages/apps/admin/src/components/MenuTree/StyledComponents.js
packages/core/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/core/tocco-ui/src/Icon/mapping.json

Refs: TOCDEV-5178
Changelog: harmonize extended search result styling

refactor(admin): style extended search

---

packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js

Changelog: do not reuse same tab for different reports
Refs: TOCDEV-5251

fix(app-extensions): do not reuse same tab for different reports

---

packages/widgets/docs-browser/src/modules/create/sagas.js

Changelog: use correct files name for upload
Refs: TOCDEV-5212

feat(docs-browser): use correct files name for upload

---

packages/core/tocco-ui/src/Select/Menu.js

Refs: TOCDEV-3699
Changelog: attach tether to target to prevent coverage of input fields

refactor(tocco-ui): attach tether to target

---

packages/core/tocco-theme/src/WidgetTheme/widgetTheme.js

Refs: TOCDEV-4909
Changelog: change secondary and secondaryLight color of widget-theme

refactor(tocco-theme): change secondary colors

---

packages/core/tocco-ui/src/FormattedValue/typeFormatters/LibPhoneFormatter.js
packages/core/tocco-ui/src/FormattedValue/typeFormatters/PhoneFormatter.js
packages/core/tocco-ui/src/FormattedValue/typeFormatters/PhoneFormatter.spec.js

refactor(tocco-ui): convert class component

---

packages/tocco-ui/src/EditableValue/typeEditors/UrlEdit.spec.js
packages/tocco-util/src/react/Debouncer.spec.js

test: fix shaky timer tests

---

scripts/release-packages.sh

chore: fix release script

---

packages/core/tocco-ui/src/Popover/Popover.js
packages/core/tocco-ui/src/Popover/StyledPopover.js

Refs: TOCDEV-4914
Changelog: fix popper arrow positioning

refactor(tocco-ui): fix popper arrow

---

packages/core/app-extensions/src/notification/api.js
packages/core/tocco-util/src/request/request.js
packages/core/tocco-util/src/request/request.spec.js

feat(tocco-util): dynamic client type

---

packages/core/app-extensions/src/notification/modules/center/NotificationCenter/NotificationCenter.js

Refs: TOCDEV-5314
Changelog: make notification message at the end of notification center italic

refactor(app-extensions): style notification msg

---

packages/tocco-ui/src/EditableValue/StyledEditableValue.js

Refs: TOCDEV-5166
Changelog: fix double scrollbar on textarea

fix(tocco-ui): fix double scrollbar on textarea

---

build/scripts/copy-package-to-nice2.js

chore: finish setup of address-update widget

---

packages/actions/resource-scheduler/src/input.js
packages/actions/resource-scheduler/src/modules/resourceScheduler/actions.js
packages/actions/resource-scheduler/src/modules/resourceScheduler/sagas.js
packages/actions/resource-scheduler/src/modules/resourceScheduler/sagas.spec.js

Changelog: query selections now get resolved in the resource-scheduler action
Refs: TOCDEV-5322

feat(resource-scheduler): handle query selection

---

packages/core/entity-list/src/components/Table/StyledComponents.js

Refs: TOCDEV-5337
Changelog: remove vertical center alignment for marking column

refactor(entity-list): remove center alignment

---

packages/widgets/wage-view/README.md
packages/widgets/wage-view/src/components/WageView/WageView.js
packages/widgets/wage-view/src/components/WageView/WageViewContainer.js
packages/widgets/wage-view/src/dev/input.json
packages/widgets/wage-view/src/main.js

feat(wage-view): add limit parameter

---

packages/core/tocco-ui/src/EditableValue/typeEditors/HtmlEdit.js
packages/core/tocco-ui/src/EditableValue/typeEditors/StyledHtmlEdit.js

Refs: TOCDEV-4902
Changelog: convert HtmlEdit class component to functional component

refactor(tocco-ui): refactor HtmlEdit

---

packages/core/tocco-ui/src/SearchBox/SearchBox.js
packages/core/tocco-ui/src/SearchBox/StyledSearchBox.js
packages/core/tocco-ui/src/StatedValue/StatedValue.js
packages/core/tocco-ui/src/StatedValue/StatedValue.spec.js
packages/core/tocco-ui/src/StatedValue/StyledStatedValue.js

Refs: TOCDEV-5339
Changelog: remove floating labels in favour of fixed labels

refactor(tocco-ui): remove floating labels

---

package.json
packages/core/tocco-ui/package.json
packages/core/tocco-ui/yarn.lock
yarn.lock

chore: upgrade forteawesome icons

---

packages/core/app-extensions/package.json
packages/core/app-extensions/yarn.lock

Refs: TOCDEV-4976, TOCDEV-5020

chore: upgrade validator dependency

---

packages/widgets/address-update/package.json
packages/widgets/address-update/src/main.js

Refs: TOCDEV-5211
Changelog: remove "choose document" option for image upload

fix(address-update): remove "choose document" option for image upload

---

packages/core/tocco-ui/src/Select/Menu.js
packages/core/tocco-ui/src/Select/StyledComponents.js

Refs: TOCDEV-5424
Changelog: fixate menu on multiremote select fields at bottom to improve ux

refactor(tocco-ui): fixate menu at bottom

---

packages/app-extensions/src/formData/searchFilters/sagas.js
packages/app-extensions/src/formData/searchFilters/sagas.spec.js

Changelog: fix searchfilters url with query params
Refs: TOCDEV-5452

fix(app-extensions): fix searchfilters url with query params

---

packages/core/entity-list/src/modules/list/actions.js
packages/core/entity-list/src/modules/list/reducer.js
packages/core/entity-list/src/modules/list/sagas.js
packages/core/entity-list/src/modules/list/sagas.spec.js
packages/core/entity-list/src/util/api/forms.js

fix(entity-list): load constriction from form again

---

packages/core/app-extensions/src/actions/modules/prepare/prepare.js

Changelog: add form properties to prepare request
Refs: TOCDEV-5361

feat(app-extensions): add form properties to prepare request

---

packages/core/tocco-theme/src/ToccoTheme/defaultTheme.js

Refs: TOCDEV-5493
Changelog: increase body background contrast by setting it to same color as breadcrumbs

refactor(tocco-theme): increase body background contrast

---

packages/app-extensions/src/appFactory/ThemeWrapper.js

Refs: TOCDEV-5613
Changelog: add css classes for display expressions styling

feat(app-extensions): add css classes for display expressions styling

---

packages/widgets/address-update/package.json
packages/widgets/wage-view/package.json
packages/widgets/widget-utils/package.json

widgets are currently only developed in the master so we won't bugfix anything

chore: set widget packages to private

---

packages/core/tocco-ui/src/EditableValue/editors/PhoneEdit.js
packages/core/tocco-ui/src/EditableValue/editors/PhoneEdit.spec.js
packages/core/tocco-ui/src/Layout/Layout.js
packages/core/tocco-ui/src/StatedValue/StatedValue.stories.js
packages/core/tocco-ui/src/StatedValue/StyledStatedValue.js
packages/core/tocco-ui/src/Typography/Typography.js
packages/widgets/sso-login/src/components/LoginBox/LoginBox.js
packages/widgets/sso-login/src/components/LoginBox/LoginBox.spec.js
packages/widgets/sso-login/src/components/LoginBox/StyledComponents.js

Refs: TOCPROD-41
Changelog: convert phoneEdit to functional component

refactor(tocco-ui): refactor phoneEdit

---

packages/core/app-extensions/src/errorLogging/handlers/remoteHandler.js

Changelog: fix remote error handler

fix(app-extensions): fix remote error handler

---

packages/core/entity-list/src/components/BasicSearchForm/BasicSearchForm.js

Refs: TOCDEV-5617
Changelog: support simple search flag for fulltext search field

fix(entity-list): support simple search flag for fulltext search field

---

packages/core/tocco-ui/src/ColumnPicker/ColumnPicker.js

Refs: TOCDEV-5664
Changelog: optimize toggle behaviour of column picker to only select currently visible items

refactor(tocco-ui): optimize column picker ux

---

packages/core/app-extensions/src/actions/components/StyledReportSettings.js
packages/core/tocco-ui/src/Select/StyledComponents.js

Refs: TOCDEV-5684
Changelog: fix modal footer when opening multiselect fields

refactor(app-extenions): fix modal footer

---

packages/actions/entity-report/src/components/Selection/Selection.js
packages/actions/entity-report/src/dev/textResources.json

Refs: TOCDEV-5420
Changelog: add label to entity report

feat(entity-report): add label

---

packages/apps/admin/src/components/Header/StyledComponents.js

Refs: TOCDEV-5582
Changelog: fix header text-overflow in firefox

refactor(admin): fix header in FF

---

packages/core/tocco-ui/src/EditableValue/editors/DatePicker.js
packages/core/tocco-ui/src/EditableValue/editors/StyledDatePicker.js

- fixes issue with multiple dates being selected and keyboard input no longer working
Refs: TOCDEV-5630
Changelog: today button in datepicker now behaves as expected

fix(tocco-ui): create custom today button for datepicker

---

packages/app-extensions/src/notifier/modules/modalComponents/StyledComponents.js

cherrypick 4b8648f2c4f82dcbd8507b79f1ecd47d5ce455e5 to version 2.29 to fix z-index issue
Refs: BS-7483

fix(app-extensions): fix z-index for entity-browser in old client

---

packages/core/tocco-ui/src/Breadcrumbs/Breadcrumbs.js
packages/core/tocco-ui/src/Breadcrumbs/Breadcrumbs.spec.js
packages/core/tocco-ui/src/Breadcrumbs/BreadcrumbsContainer.js
packages/core/tocco-ui/src/Breadcrumbs/index.js

Refs: TOCDEV-5612
Changelog: enhance breadcrumbs

feat(tocco-ui): enhance breadcrumbs

---

packages/core/tocco-ui/src/DatePicker/ChildrenWrapper.js
packages/core/tocco-ui/src/DatePicker/DatePicker.js
packages/core/tocco-ui/src/DatePicker/GlobalDatePickerStyles.js
packages/core/tocco-ui/src/EditableValue/editors/DatePicker.js
packages/core/tocco-ui/src/EditableValue/editors/StyledDatePicker.js
packages/core/tocco-ui/src/Range/StyledRange.js

Refs: TOCDEV-5695
Changelog: style new date picker like the old one

refactor(tocco-ui): style new date picker

---

packages/core/app-extensions/src/form/sagasUtils.js

fix(app-extensions): correct usage of textresource in validation

---

packages/tocco-ui/src/FormattedValue/typeFormatters/EmailFormatter.js
packages/tocco-ui/src/FormattedValue/typeFormatters/PhoneFormatter.js

Changelog: fix breakwords for email and phone formatter
Refs: TOCDEV-5765

fix(tocco-ui): fix breakwords for email and phone formatter

---

packages/apps/admin/src/components/AboutTocco/AboutTocco.js
packages/apps/admin/src/components/AboutTocco/AboutToccoContainer.js

Changelog: add build time to about tocco
Refs: TOCDEV-5698

feat(admin): add build time to about tocco

---

target-branch.txt

chore: set target-branch for 3.2

---

packages/core/app-extensions/src/field/editableComponentConfigs/remote.js

Changelog: use constrictions from form in remotefield as well

fix(app-extensions): read remotefield constriction from form as well

---

packages/core/tocco-ui/src/EditableValue/editors/DatePicker.spec.js

test(tocco-ui): fix shaky datetime tests

---

packages/core/app-extensions/src/rest/helpers.js
packages/core/app-extensions/src/rest/helpers.spec.js

Refs: TOCDEV-5720
Changelog: only cache displays as long as tab is open

feat(app-extensions): only cache displays for as long as tab is open

---

packages/entity-detail/src/modules/entityDetail/sagas.js
packages/entity-detail/src/modules/entityDetail/sagas.spec.js

Refs: TOCDEV-5811
Changelog: check form definition if form is markable

fix(entity-detail): check form definition if form is markable

---

packages/core/entity-detail/src/components/SubGrid/SubGrid.js
packages/core/entity-detail/src/main.js

fix(entity-detail): fix prop types for component

---

package.json

chore: fix plop after upgrade

---

.gitlab-ci.yml
cypress.config.js
cypress/e2e/entitybrowser_spec.js
cypress/plugins/database.js
cypress/plugins/index.js
cypress/support/commands.js
scripts/nice2/helpers.sh

- create expected database user
- remove redundant cypress env var
- create cypress helpers for widgets

chore: cleanup cypress setup

---

packages/widgets/entity-browser/src/components/EntityDetail/EntityDetail.js

Changelog: remount entity-detail app after navigation
Refs: TOCDEV-5770

fix(entity-browser): remount entity-detail app after navigation

---

packages/core/tocco-ui/src/SignalBox/SignalBox.js
packages/core/tocco-ui/src/SignalBox/StyledSignalBox.js

Refs: TOCDEV-5736
Changelog: change signal box background colors for more consistency

refactor(tocco-ui): harmonize signal box color

---

packages/core/tocco-ui/src/DatePicker/DatePicker.js
packages/core/tocco-ui/src/DatePicker/GlobalDatePickerStyles.js
packages/core/tocco-ui/src/EditableValue/editors/DatePicker.js

Refs: TOCDEV-5695
Changelog: improve datepicker styling and fix bugs in widgets

refactor(tocco-ui): fix datepicker styling

---

packages/core/tocco-ui/src/EditableValue/editors/Document.spec.js
packages/core/tocco-ui/src/Upload/StyledComponents.js

Refs: TOCDEV-5733
Changelog: force hover styles of upload button when hovering upload field

refactor(tocco-ui): force hover of upload button

---

packages/core/app-extensions/src/formData/advancedSearch/sagas.js
packages/core/app-extensions/src/formData/advancedSearch/sagas.spec.js
packages/core/tocco-util/src/mockData/data/textResources.json

Refs: TOCDEV-5735
Changelog: remove advanced search text in modal title

refactor(app-extensions): shorten modal title

---

packages/widgets/address-update/src/main.js

Refs: TOCDEV-5727
Changelog: add business unit to input props

feat(address-update): add business unit to input props

---

packages/core/app-extensions/src/form/formModifier.js
packages/core/app-extensions/src/form/formModifier.spec.js

Changelog: fix position of reports in form modifier
Refs: TOCDEV-5771

fix(app-extensions): fix position of reports in form modifier

---

packages/core/tocco-ui/src/Range/rangeTypeMappings.js
packages/core/tocco-ui/src/Range/rangeTypeMappings.spec.js

Refs: TOCDEV-5780
Changelog: fix datetime range with single default value

fix(tocco-ui): fix datetime range with single default value

---

packages/core/tocco-ui/src/EditableValue/EditorProvider.js

Changelog: do not clear date input on blur
Refs: TOCDEV-5694

fix(tocco-ui): do not clear date input on blur

---

server/main.js

chore: fix nice2 proxy for local development

---

packages/core/tocco-ui/src/DatePicker/DatePicker.js
packages/core/tocco-ui/src/DatePicker/GlobalDatePickerStyles.js
packages/core/tocco-ui/src/EditableValue/editors/DatePicker.js

Refs: TOCDEV-5695
Changelog: remove date picker arrow as the positioning seems to be off when fields are too long

refactor(tocco-ui): remove date picker arrow

---

packages/core/scheduler/src/components/FullCalendar/StyledFullCalendar.js

Refs: TOCDEV-5813
Changelog: fix overflowing text in fullcalender entries

refactor(scheduler): fix overflowing text

---

packages/apps/admin/src/routes/entities/components/RelationsView/RelationBox.js
packages/apps/admin/src/routes/entities/components/RelationsView/StyledComponents.js

Refs: TOCDEV-5772
Changelog: prevent relation box count label from being cut on overflow

refactor(admin): fix relation label count

---

packages/core/app-extensions/src/actions/modules/prepare/initialFormHandler.js
packages/core/app-extensions/src/notification/modules/modal/ModalDisplay/ModalContent.js
packages/core/app-extensions/src/notification/modules/modal/ModalDisplay/StyledComponents.js

Refs: TOCDEV-5843
Changelog: harmonize modal spacing of modal message

refactor(app-extensions): harmonize modal spacing

---

packages/widgets/address-update/src/main.js

Refs: TOCDEV-5826
Changelog: apply global styles to fix datepicker

fix(address-update): apply global styles to fix datepicker

---

packages/core/app-extensions/src/formData/advancedSearch/StyledAdvancedSearch.js
packages/core/app-extensions/src/notification/modules/modal/ModalDisplay/StyledComponents.js
packages/core/entity-list/src/components/EntityList/StyledComponents.js

Refs: TOCDEV-5868
Changelog: enable fullscreen modals for mobile/touch devices

refactor(app-estensions): enable fullscreen modal on mobile

---

packages/core/tocco-ui/src/HtmlEditor/HtmlEditor.js

The 'SourceEditing' plugin internally updates the editor sources
on `editor.getData()`. This leads to an infinite loop of
`getData()` calls and `onChange` events (as this `onChange`
event handler calls `getData()`.) Therefore, we have to make
sure that we handle the `onChange` only once if we're in the
source editing mode.
Note:
The `onChange` never actually gets fired during changes in the
source editing mode. Rather, the editor gets unmounted before the form
gets saved. During this procedure an internal destroy function is called
which updates the sources and in turn fires the `onChange` event.
Note 2:
In general, it seems quite fragile and hacky. However, the SourceEditing
plugin exposes only the `isSourceEditingMode` and there are no useful
events or something like that. So, this …

fix(tocco-ui): HTML editor: fix saving the form in source editing mode

---

packages/apps/admin/src/routes/entities/components/RelationsView/StyledComponents.js
packages/core/app-extensions/src/notification/modules/modal/ModalDisplay/StyledComponents.js
packages/core/tocco-ui/src/Panel/StyledPanelHeaderFooter.js
packages/core/tocco-ui/src/index.js
packages/core/tocco-ui/src/utilStyles/declareTouchCss.js
packages/core/tocco-ui/src/utilStyles/index.js

refactor(tocco-ui): add touch css helper function

---

packages/actions/mailing-list-mail-action/src/components/MailAction/MailAction.js
packages/actions/mailing-list-mail-action/src/components/StyledComponents.js

Refs: TOCDEV-5854
Changelog: style mail action button inside modal

refactor(actions): style mail action button

---

packages/widgets/login/README.md
packages/widgets/login/src/PasswordUpdateApp.js
packages/widgets/login/src/components/LoadUsernameMask/LoadUsernameMask.js
packages/widgets/login/src/components/LoadUsernameMask/LoadUsernameMaskContainer.js
packages/widgets/login/src/components/LoadUsernameMask/index.js
packages/widgets/login/src/modules/passwordUpdate/dialog/actions.js
packages/widgets/login/src/modules/passwordUpdate/dialog/index.js
packages/widgets/login/src/modules/passwordUpdate/dialog/sagas.js
packages/widgets/login/src/modules/passwordUpdate/dialog/sagas.spec.js
packages/widgets/login/src/modules/passwordUpdate/reducers.js

Changelog: make username input prop optional and use current user
Refs: TOCDEV-5882

feat(login): make username input prop optional and use current user

---

packages/core/app-extensions/src/actions/modules/actionHandlers/report.js
packages/core/app-extensions/src/actions/modules/actionHandlers/report.spec.js

Refs: TOCDEV-5672
Changelog: generate reports without dialog in widgets

feat(app-extensions): generate reports without dialog in widgets

---

packages/widgets/login/README.md
packages/widgets/login/src/modules/sagas.js
packages/widgets/login/src/modules/sagas.spec.js

Refs: TOCDEV-5749
Changelog: add redirect that happens after successful login, destination defined by widget config

feat(login): add redirect to login

---

packages/core/dashboard/src/components/Dashboard/DashboardInfoBox.js
packages/core/dashboard/src/components/Dashboard/StyledComponents.js

Refs: TOCDEV-5113
Changelog: change dashboard layout on mobile to single column and disable drag and drop feature

refactor(dashboard): change layout on mobile

---

packages/core/tocco-ui/src/DatePicker/GlobalDatePickerStyles.js

Refs: TOCDEV-5873
Changelog: adjust sizing of datepicker on mobile screens

refactor(tocco-ui): adjust mobile datepicker sizing

---

packages/simple-form/src/components/Form/StyledComponents.js

Refs: TOCDEV-5943
Changelog: implement sticky buttons for simple-form modal

refactor(simple-form): implement sticky buttons in modal

---

packages/core/tocco-ui/src/Select/Menu.js
packages/core/tocco-ui/src/Select/MenuList.js
packages/core/tocco-ui/src/Select/Select.js

Refs: TOCDEV-5532
Changelog: reset select dropdown to older state and implement close on scroll feature

refactor(tocco-ui): reset select dropdown

---

packages/core/tocco-ui/src/Select/Select.js

Refs: TOCDEV-5978
Changelog: fix select dropdown dimension calculations

refactor(tocco-ui): fix select dropdown dimensions

---

packages/apps/admin/src/components/Header/Header.js
packages/apps/admin/src/routes/dashboard/components/Dashboard/Dashboard.js
packages/core/tocco-ui/src/Breadcrumbs/Breadcrumbs.js
packages/core/tocco-ui/src/Button/StyledRouterLinkButton.js
packages/core/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/core/tocco-ui/src/Icon/mapping.json

Refs: TOCDEV-5982
Changelog: add home icon to header and breadcrumbs

refactor(admin): add home icon

---

packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js

Changelog: add model name to notification
Refs: TOCDEV-5941, TOCDEV-5942

feat(app-extensions): add model name to notification

---

scripts/helpers.sh

in version 3.1 and earlier the path to the package is different
Refs: TOCDEV-5746

chore: fix changelog generation

---

packages/core/tocco-ui/src/EditableValue/editors/DatePicker.js

Refs: TOCDEV-5983
Changelog: close datepicker on scroll

refactor(tocco-ui): close datepicker on scroll

---

packages/core/tocco-ui/src/DatePicker/GlobalDatePickerStyles.js
packages/core/tocco-ui/src/EditableValue/editors/DatePicker.js

Refs: TOCDEV-5983
Changelog: fix datepicker year dropdown closing on scroll

refactor(tocco-ui): fix year scroll

---

packages/apps/admin/src/routes/entities/components/DetailView/DetailView.js
packages/apps/admin/src/routes/entities/components/DetailView/StyledComponents.js
packages/apps/admin/src/routes/entities/components/RelationsView/RelationsView.js
packages/apps/admin/src/routes/entities/components/RelationsView/StyledComponents.js

Refs: TOCDEV-5111
Changelog: add mobile collapse feature to detail view

refactor(admin): add mobile collapse feature

---

packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js

Changelog: fix whitespace in notification
Refs: TOCDEV-5941, TOCDEV-5942

fix(app-extensions): fix whitespace in notification

---

packages/apps/admin/src/utils/docsUtils.js
packages/apps/admin/src/utils/docsUtils.spec.js

Changelog: remove locale from documentation url

fix(admin): remove locale from documentation url

---

packages/core/tocco-ui/src/EditableValue/editors/DatePicker.js

variable was renamed in version 3.4
Changelog: fix date picker icon
Refs: TOCDEV-5930

fix(tocco-ui): fix date picker icon

---

packages/core/entity-list/src/modules/entityList/sagas.js

Refs: TOCDEV-5934
Changelog: let entity list handle changed props properly

fix(entity-list): handle changed props properly

---

packages/apps/admin/src/routes/entities/components/DetailView/DetailView.js

Refs: TOCDEV-5111
Changelog: fix mobile pane bug in detail view on small screens when right pane is open

refactor(admin): fix mobile pane bug

---

packages/core/tocco-ui/src/Menu/MenuItem.js
packages/core/tocco-ui/src/Menu/StyledComponents.js

Refs: TOCDEV-5869
Changelog: increase menu item padding on touch devices for better usability

refactor(tocco-ui): increase menu item padding on touch devices

---

packages/core/tocco-ui/src/Select/Select.js

Changelog: fix scroll on select

fix(tocco-ui): fix scroll on select

---

packages/core/entity-detail/src/components/Actions/SaveButton.js
packages/core/entity-detail/src/components/Actions/StyledComponents.js
packages/core/tocco-ui/src/Icon/FontAwesomeAdapter.js
packages/core/tocco-ui/src/Icon/mapping.json

Refs: TOCDEV-6062
Changelog: improve save button look on error

refactor(entity-detail): change save button look

---

packages/core/entity-list/src/components/ListView/ListView.js
packages/core/entity-list/src/components/ListView/StyledComponents.js
packages/core/tocco-ui/src/Ball/StyledBall.js
packages/core/tocco-ui/src/Menu/StyledComponents.js
packages/core/tocco-ui/src/Pagination/StyledComponents.js
packages/core/tocco-ui/src/Pagination/index.js
packages/core/tocco-ui/src/Table/StyledComponents.js

Refs: TOCDEV-5865
Changelog: improve responsiveness of table component

refactor(tocco-ui): improve table responsiveness

---

packages/widgets/entity-browser/package.json
packages/widgets/entity-browser/src/components/LazyAction/actions/Export.js
packages/widgets/entity-browser/src/components/LazyAction/index.js

Refs: TOCDEV-5888
Changelog: add export action to entity-browser

fix(entity-browser): add export action to entity browser

---

packages/core/tocco-ui/src/Icon/mapping.json

refactor(tocco-ui): fix home icon mapping

---

packages/core/app-extensions/src/notification/modules/modal/ModalDisplay/ModalContent.js
packages/core/app-extensions/src/notification/modules/modal/ModalDisplay/StyledComponents.js

Refs: TOCDEV-5868
Changelog: prevent body scroll when modal is opened

refactor(app-extensions): prevent body scroll on modal

---

packages/core/app-extensions/src/notification/modules/socket/socket.js
packages/core/app-extensions/src/notification/modules/socket/socket.spec.js

Changelog: disable removing outputjob toasters in widgets
Refs: TOCDEV-5957

feat(app-extensions): disable removing outputjob toasters in widgets

---

packages/widgets/user-availability/src/components/UserAvailability/UserAvailability.js
packages/widgets/wage-view/src/components/WageView/WageView.js

Refs: TOCDEV-6065
Changelog: remove create action group when not configured to show

remove create action group from widgets when forbidden

---

packages/core/tocco-ui/src/SearchBox/SearchBox.js
packages/core/tocco-ui/src/SearchBox/StyledSearchBox.js

Refs: TOCDEV-6119
Changelo: replace native search field clear button with custom button

refactor(tocco-ui): replace search field clear button

---

server/index.html

Refs: TOCDEV-6160
Changelog: disable autozoom of input fields on ios devices

refactor(admin): disable autozoom

---

packages/core/entity-list/src/components/SearchFilterList/StyledComponents.js

Refs: TOCDEV-6123
Changelog: always show search filter button icons on touch devices because of missing hover function

refactor(entity-list): show button icons on mobile

---

packages/core/tocco-ui/src/StatedValue/StatedValue.js
packages/core/tocco-ui/src/StatedValue/StyledStatedValue.js

Refs: TOCDEV-6093
Changelog: increase top padding of input label to prevent cut off

refactor(tocco-ui): increase label padding

---

packages/widgets/login/src/modules/sagas.js

Refs: TOCDEV-6060
Changelog: allow login to redirect to another page from an url parameter

feat(login): redirect from login based on query parameter

---

packages/bundles/widget-bundle/package.json
packages/bundles/widget-bundle/src/apps/user-menu.js
packages/widgets/user-menu/.npmignore
packages/widgets/user-menu/.yarnrc
packages/widgets/user-menu/README.md
packages/widgets/user-menu/changelog.md
packages/widgets/user-menu/package.json
packages/widgets/user-menu/src/components/UserMenu/StyledComponents.js
packages/widgets/user-menu/src/components/UserMenu/UserMenu.js
packages/widgets/user-menu/src/components/UserMenu/UserMenuContainer.js
packages/widgets/user-menu/src/components/UserMenu/index.js
packages/widgets/user-menu/src/dev/fetchMocks.js
packages/widgets/user-menu/src/dev/input.json
packages/widgets/user-menu/src/dev/textResources.json
packages/widgets/user-menu/src/input.js
packages/widgets/user-menu/src/main.js
packages/widgets/user-menu/src/modules/reducers.js
packages/widgets/user-menu/src/modules/userMenu/actions.js
packages/widgets/user-menu/src/modules/userMenu/index.js
packages/widgets/user-menu/src/modules/userMenu/reducer.js
packages/widgets/user-menu/src/modules/userMenu/sagas.js
packages/widgets/user-menu/src/modules/userMenu/sagas.spec.js

Changelog: add user menu widget
Refs: TOCDEV-5750

feat(user-menu): add user menu widget

---

packages/widgets/user-menu/src/main.js

Changelog: add missing setInputEnvs
Refs: TOCDEV-5750

fix(user-menu): add missing setInputEnvs

---

target-branch.txt

chore: set target-branch for 3.3

---

packages/actions/widget-code-copy/src/utils/widgetCode.js
packages/actions/widget-code-copy/src/utils/widgetCode.spec.js

Refs: TOCDEV-6223
Changelog: simplify widget code

feat(widget-code-copy): simplify widget code

---

packages/core/app-extensions/src/formData/relationEntities/sagas.js
packages/core/app-extensions/src/formData/relationEntities/sagas.spec.js

Refs: TOCDEV-5562
Changelog: use a new custom display when displaying entities in select boxes

feat(app-extensions): use custom display in remote fields

---

packages/core/entity-detail/src/components/Actions/StyledComponents.js

Refs: TOCDEV-6062
Changelog: fix save button being clipped and change hover on error

refactor(entity-detail): fix clipping

---

packages/actions/input-edit/src/components/InputEditTable/StyledComponents.js
packages/core/tocco-ui/src/Select/index.js
packages/core/tocco-ui/src/index.js

Refs: TOCDEV-6192
Changelog: fix react-select dropdown being clipped inside input-edit table

refactor(input-edit): fix react-select

---

packages/widgets/user-menu/src/components/FixedWrapper/StyledComponents.js
packages/widgets/user-menu/src/components/FixedWrapper/index.js
packages/widgets/user-menu/src/components/UserMenu/StyledComponents.js
packages/widgets/user-menu/src/components/UserMenu/UserMenu.js
packages/widgets/user-menu/src/dev/input.json
packages/widgets/user-menu/src/main.js

Changelog: fixed width for user-menu
Refs: TOCDEV-6342

feat(user-menu): set fixed width

---

packages/tocco-util/src/tqlBuilder/tqlBuilder.js

Changelog: support identifier type in tql builder
Refs: TOCDEV-6235

fix(tocco-util): support identifier type in tql builder

---

packages/actions/resource-scheduler/src/components/ResourceScheduler/ResourceScheduler.js
packages/actions/resource-scheduler/src/components/ResourceScheduler/StyledComponents.js
packages/core/scheduler/src/components/FullCalendar/FullCalendar.js
packages/core/scheduler/src/components/FullCalendar/StyledFullCalendar.js
packages/core/scheduler/src/components/NavigationFullCalendar/StyledComponents.js

Refs: TOCDEV-6193
Changelog: remove the split pane feature as it doesn not improve UX and wrap scheduler in generic sidepanel component

refactor(scheduler): remove split pane

---

packages/core/app-extensions/src/field/editableComponentConfigs/remote.js
packages/core/app-extensions/src/field/editableComponentConfigs/remote.spec.js

Refs: TOCDEV-5523
Changelog: support disabling remote create button

feat(ap-extensions): support disabling remote create button

---

packages/apps/admin/src/components/Navigation/menuType/StyledComponents.js
packages/core/app-extensions/src/notification/modules/modal/ModalDisplay/ModalContent.js
packages/core/app-extensions/src/notification/modules/modal/ModalDisplay/StyledComponents.js
packages/core/entity-list/src/components/SearchFilterList/StyledComponents.js

Reverts tocco/tocco-client#3252

Revert "Pr/modal"

---

cypress/e2e/reloadconfiguration_spec.js

do not open action in separate tab

test: fix relaod action

---

packages/apps/admin/src/components/Navigation/Navigation.js
packages/apps/admin/src/components/Navigation/menuType/ActionEntry.js
packages/apps/admin/src/components/Navigation/menuType/StyledComponents.js
packages/apps/admin/src/main.js
packages/core/app-extensions/src/actions/components/Action.js
packages/core/app-extensions/src/actions/components/SingleAction.js
packages/core/app-extensions/src/actions/index.js
packages/core/tocco-ui/src/Button/Button.js
packages/core/tocco-ui/src/Button/buttonStyle.js

Needs backend change https://git.tocco.ch/c/nice2/+/46780

allow non-fullscreen custom actions in menu

---

packages/apps/admin/src/components/Navigation/menuType/ActionEntry.js

fix(admin): clean up custom action guard in ActionEntry

---

packages/core/tocco-ui/src/BurgerButton/BurgerButton.stories.js
packages/core/tocco-ui/src/DatePicker/DatePicker.stories.js
packages/core/tocco-ui/src/EditableValue/EditableValue.stories.js
storybook/preview.js

- fix controls for editable value
- improve performance for edtiable values (remove global styles)
- fix intl messages proxy

chore: improve storybook

---

.gitlab-ci.yml
build/jest.config.base.js
jest.config.js
package.json
sonar-project.properties

feat: use jest coverage for sonarqube

---

packages/apps/admin/src/modules/session/sagas.js

Refs: TOCDEV-6266
Changelog: user now gets redirected to homepage after logout

feat(admin): redirect to base route after logout

---

packages/widgets/personal-dms/src/components/PersonalDms/PersonalDms.js

Refs: TOCDEV-6319
Changelog: user now gets new widget forms for personal-dms

feat(personal-dms): personal-dms seperate forms
