- packages/action-password-update/README.md
- packages/action-password-update/src/components/PasswordUpdateDialog/PasswordUpdateDialog.js
- packages/action-password-update/src/components/PasswordUpdateDialog/PasswordUpdateDialog.spec.js
- packages/action-password-update/src/containers/PasswordUpdateDialogContainer.js
- packages/action-password-update/src/modules/actions.js
- packages/action-password-update/src/modules/reducers.js
- packages/action-password-update/src/modules/sagas.js
- packages/action-password-update/src/modules/sagas.spec.js
- This event is fired once the dialog is fully initialized (validation rules
have been loaded and rendered)
- Can, for instance, be used to center the application container in the
view screen
> feat(action-password-update): Introduce `initialized` event

- .eslintignore
- README.md
- package.json
- server/index.html
- server/main.js
- server/static/package.json
- Libs (React and Bootstrap) used by the local server are loaded from a seperate node_modules folder. This allows offline development and easy dependency update
- introduce npm setup script to to run both npm install
> chore(tocco-client): load server libs locally

- build/webpack.config.js
- package.json
- plugin throws an error if case in import statement is incorrect. Important to avoid errors on case-insensitive operating systems like OSX
- some formatting in webpack.config.js
> chore: webpack case-sensitive path plugin

- packages/login/src/modules/sagas.js
- packages/login/src/modules/sagas.spec.js
- If no text is found for the given key, the key is returned as fallback
- This also fixes a bug where no failure message was displayed if
corresponding text resource was not found
> refactor(login): Change text resource selector to return text for key

- packages/login/package.json
- packages/login/src/dev/loginResponseMocks.js
- packages/login/src/modules/sagas.js
- packages/login/src/modules/sagas.spec.js
If fetch requests fail, errors are caught and logged and a generic failure
response is returned.
> refactor(login): Improve error handling in sagas

- packages/merge/package.json
- packages/merge/src/components/MergeMatrix/table-components/HeaderRow.js
- packages/merge/src/components/MergeStrategy/MergeStrategy.js
- packages/merge/src/components/MergeStrategy/MergeStrategy.spec.js
- packages/merge/src/components/MergeWizard/MergeResponse.js
- packages/merge/src/components/MergeWizard/MergeWizard.js
- packages/merge/src/components/Wizard/Wizard.js
- packages/merge/src/main.js
- due to new convention, a package name should not include its usage. therefore 'action' prefix gets removed.
- bump merge to version 0.1.4
> refactor(merge): rename package and adjust text-resource name

- config/_development.js
- 'http://8080' did not proper work as relative backend dev url. 'Fetch' was not able to parse such urls.
- JSON.stringify will not work with the new fix because the expression (window.location.hostname) would be evaluated during compile time
> chore(tocco-client): fix relative backend url

- packages/tocco-ui/src/Table/Table.js
- packages/tocco-ui/src/Table/Table.spec.js
- packages/tocco-ui/src/Table/example.js
A table cell can contain multiple field values. They are rendered as a comma
separated string (by default, but you can register your own renderer using the
`cellRenderer` prop.
> feat(tocco-ui): Add support for multiple cell values in `<Table>`

- build/webpack.config.js
- package.json
- With this integration, a linting error gets noticed during development without calling separate npm command
> chore: integrate linting in build process

- build/karma-saucelabs.conf.js
- build/karma.conf.js
- yarn.lock
- Update yarn.lock file to fit package.json
- Disable coverage completely on saucelabs test run. Otherwise the coverage folder on travis will be overridden and an empty report gets uploaded to codecov
- karma.cong:  change loader to rules (webpack 2 syntax)
> chore: yarn.lock file and saucelabs coverage

- .flowconfig
- otherwise various js files from there will throw a warning
on npm run flow
> chore: flow ignore node_modules folder

- packages/tocco-ui/src/FormattedValue/FormattedValue.js
- packages/tocco-ui/src/FormattedValue/FormattedValue.spec.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/BooleanFormatter.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/BooleanFormatter.spec.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/DecimalFormatter.spec.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/DurationFormatter.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/MoneyFormatter.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/MoneyFormatter.spec.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/NumberFormatter.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/PercentFormatter.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/StringFormatter.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/TextFormatter.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/TimeFormatter.spec.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/UrlFormatter.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/UrlFormatter.spec.js
- https://github.com/tocco/tocco-client/commit/81c943757d07da49263f7c72a8bf14c7751b830a
since 'undefined' values getting handled in root component, the checks can be removed on type implementations
> refactor(tocco-ui): FormatedValue remove undefined checks

- packages/tocco-util/src/appFactory/appFactory.js
- packages/tocco-util/src/errorLogging/handlers/consoleHandler.js
- packages/tocco-util/src/errorLogging/sagas.js
- packages/tocco-util/src/externalEvents/externalEvents.js
- packages/tocco-util/src/utilFetchMocks/log.js
- since consoleLogger gets exported as default, changes in tocco-util are needed as well.
> fix(tocco-util): apply changes of default export

- packages/tocco-ui/package.json
- packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
- A newer version of flatpickr handles timezone input in UTC (Z) format.
Therefore the onChange event should send changed value also in utc.
- update flatpickr to newest version
> fix(tocco-ui): DateTimeEdit fix timezone problem

- packages/entity-browser/src/components/DetailView/DetailView.js
- packages/entity-browser/src/util/detailView/asyncValidation.js
- like on submit, only send dirty fields to rest api
> fix(entity-browser): only validate dirty fields async

- packages/tocco-ui/src/FormattedValue/typeFormatters/DateFormatter.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/DateFormatter.spec.js
- packages/tocco-ui/src/FormattedValue/util/DateUtils.js
- packages/tocco-ui/src/FormattedValue/util/DateUtils.spec.js
Before the time zone was set to UTC fixed. This caused an issue because dates in js alsways
have a time and a time zone. Different browser handle the time zone differently. Some
use the UTC time zone and some use the local time zone (e.g. GMT +2)
Now the time zone is not set to UTC by default anymore. If a date object is passed to the
date formatter, it just will be passed. In this case the time zone handling does not matter.
If a string or a number is passed, the `Date.parse` function is used to parse the date and
the time zone offset will be added to the created date object.
> fix(tocco-ui): fix a date formatter time zone issue

- packages/entity-browser/src/components/FormField/formFieldUtil.js
- packages/entity-browser/src/components/FormField/formFieldUtil.spec.js
- packages/entity-browser/src/dev/rest-responses/messages.json
- packages/entity-browser/src/routes/detail/components/DetailForm/DetailForm.js
- packages/tocco-ui/src/EditableValue/example.js
- packages/tocco-ui/src/EditableValue/typeEditors/MultiRemoteSelect.js
- packages/tocco-ui/src/EditableValue/typeEditors/MultiRemoteSelect.spec.js
- packages/tocco-ui/src/EditableValue/typeEditors/RemoteSelect.js
- packages/tocco-ui/src/EditableValue/typeEditors/RemoteSelect.spec.js
Add some properties to the remote select components to set customized text on the components.
The following four new properties have been added to the RemoteSelect and MultiRemoteSelect components:
- searchPromptText
- clearValueText
- clearAllText
- noResultsText
In the DetailForm component we use the intl.formatMessage function to provide localized strings.
> Pr/tocco ui/remote select properties

- packages/tocco-ui-showcase/src/components/ShowCaseApp.js
- packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
- server/index.html
- server/standalone.html
The class has been removed in index.html and standalone.html in commit 0ae1cea.
That's okay, but we have to add it on the root of the showcase app, so that it
looks nice again.
> fix(tocco-ui-showcase): Add `tocco-ui-theme` class again for showcase

- packages/tocco-ui/src/EditableValue/typeEditorFactory.js
- blur workaround for known react-select issue: https://github.com/erikras/redux-form/issues/82
- without this fix, all react-select editableValues are emptied onBlur event
> fix(entity-browser): redux-form react-select empty value fix

- packages/entity-list/src/containers/SearchFormContainer.js
- packages/entity-list/src/modules/searchForm/actions.js
- packages/entity-list/src/modules/searchForm/reducer.js
- packages/entity-list/src/modules/searchForm/reducer.spec.js
- packages/entity-list/src/modules/searchForm/sagas.js
- packages/entity-list/src/modules/searchForm/sagas.spec.js
Before the entity list has become a separate package, this action (and the
reducer and the sagas) were part of the parent module "entity-browser" and we
didn't have to implement it in the list by ourselves.
> fix(entity-list): Readd action `loadRelationEntity`

- packages/entity-list/README.md
- packages/entity-list/src/containers/ListViewContainer.js
- packages/tocco-util/src/externalEvents/externalEvents.js
- packages/tocco-util/src/externalEvents/externalEvents.spec.js
- packages/tocco-util/src/externalEvents/index.js
- packages/tocco-util/src/storeFactory/storeFactory.js
Simply dispatch a `fireExternalEvent` action (action creator located in the
`externalEvents` module of the `tocco-util` package) and the saga (which will
always be registered if the store got created using storeFactory#createStore())
will invoke the event listeners.
Example:
```
import {externalEvents} from 'tocco-util'
store.dispatch(externalEvents.fireExternalEvent('myExternalEvent', myEventPayload))
```
> feat(tocco-util): Introduce "shared" saga to fire an external event

- packages/entity-list/src/main.js
Example usage of `onRowClick` event of `EntityListApp`:
```
import EntityListApp from 'entity-list'
<EntityListApp onRowClick={id => console.log(id)} .../>
```
> feat(entity-list): Support external events passed via props

- packages/entity-browser/src/dev/rest-responses/messages.json
- packages/entity-browser/src/routes/detail/components/DetailForm/DetailForm.js
- packages/entity-browser/src/routes/detail/components/DetailView/DetailView.js
- packages/entity-browser/src/routes/detail/components/DetailView/DetailView.spec.js
- packages/entity-browser/src/routes/detail/containers/DetailViewContainer.js
- packages/entity-browser/src/util/detailView/parseUrl.js
- packages/entity-browser/src/util/detailView/parseUrl.spec.js
Before, the back button always switched to the list (path '/'). This is not
desired on the detail view of a related entity -> in this case, we want to
return to the parent detail view.
Additionally, the back button has been moved to the top of the detail view.
> fix(entity-browser): Fix back button for related entity detail view

- packages/entity-browser/src/routes/list/modules/sagas.js
- packages/entity-browser/src/routes/list/modules/sagas.spec.js
- packages/entity-browser/src/util/searchInputs.js
- packages/entity-browser/src/util/searchInputs.spec.js
- packages/entity-list/src/util/searchInputs.js
- packages/entity-list/src/util/searchInputs.spec.js
- Searchfield relation type multi should not be retrieved from model
because a single relation probably gets displayed as multi-select or
as string (fulltext) in searchForm. Getting information form
searchFormDefinition also doesn't work because of hidden input search
values which are not represented in definition.
> fix(entity-list): getSearchInputsForRequest not from model

- packages/entity-browser/src/dev/fetchMocks.js
- packages/entity-browser/src/dev/rest-responses/form_user_detail.json
- packages/entity-browser/src/dev/rest-responses/form_user_detail_relDummySubGrid_search.json
- packages/entity-browser/src/routes/detail/components/SubGrid/SubGrid.js
- packages/entity-list/src/components/SearchForm/SearchForm.js
- packages/entity-list/src/components/SearchForm/SearchForm.spec.js
- packages/entity-list/src/util/api/forms.js
- packages/entity-list/src/util/api/forms.spec.js
- packages/tocco-util/src/rest/rest.js
- packages/tocco-util/src/rest/rest.spec.js
Example code to load a form and accept a 404 status code (form not found):
```
request(`forms/${formName}`, undefined, undefined, undefined, undefined, [404])
```
> Search forms for sub grids

- packages/entity-list/README.md
- packages/entity-list/src/dev/input.json
- packages/entity-list/src/main.js
- simpleSearchFields: string is expected (not array)
- preselectedSearchValues: this input will be ignored, the right name is: preselectedSearchFields
> fix(entity-list): Fix input prop types and documentation

- packages/entity-list/package.json
- packages/entity-list/src/components/ListView/ListView.js
- packages/entity-list/src/components/ListView/ListView.scss
- packages/entity-list/src/components/ListView/ListView.spec.js
- packages/entity-list/src/dev/textResources.json
- packages/entity-list/src/util/api/entities.js
- packages/entity-list/src/util/api/entities.spec.js
- packages/entity-list/src/util/api/forms.js
- packages/entity-list/src/util/api/forms.spec.js
- replace tocco-ui table and pagination with react-bootstrap-table
- hide pagination if no more than one page exists
- add __key attribute to entity and story fields directly in object and not in an attribute values (entities.js).
This change was needed to add mandatory key columns to react bootstrap table
- Columndefinition: Only regard first field in columns. To add two fields into one column, freemarker is required.
This change made handling with react-bootstrap-table easier and does not require a hack.
> feat(entity-list): integrate react-bootstrap-table

- packages/entity-detail/src/containers/DetailViewContainer.js
- packages/entity-detail/src/modules/entityDetail/actions.js
- packages/entity-detail/src/modules/entityDetail/reducer.js
- packages/entity-detail/src/modules/entityDetail/reducer.spec.js
- packages/entity-detail/src/modules/entityDetail/sagas.js
- packages/entity-detail/src/modules/entityDetail/sagas.spec.js
- packages/entity-detail/src/util/api/entities.js
- packages/entity-detail/src/util/api/entities.spec.js
- packages/tocco-ui/src/EditableValue/typeEditors/RemoteSelect.js
Changes applied compared to entity-browser:
- `loadRemoteEntity` saga has to be registered with `takeEvery` effect
instead of `takeLatest`, because it might be triggered for several select
boxes in parallel (they must not cancel each other).
- Both "relation entities" and "remote entities" should be loaded without
fields and without relations (query params: _fields=!&_relations=!), since
we only need the key and the display value to display. It might be much
faster this way.
> fix(entity-detail): Fix support for remote entities (RemoteSelect)

- packages/entity-detail/README.md
- packages/entity-detail/src/components/DetailForm/DetailForm.js
- packages/entity-detail/src/components/DetailForm/DetailForm.spec.js
- packages/entity-detail/src/components/DetailView/DetailView.js
- packages/entity-detail/src/components/DetailView/DetailView.spec.js
- packages/entity-detail/src/containers/DetailViewContainer.js
- packages/entity-detail/src/modules/entityDetail/actions.js
- packages/entity-detail/src/modules/entityDetail/reducer.js
- packages/entity-detail/src/modules/entityDetail/reducer.spec.js
- packages/entity-detail/src/modules/entityDetail/sagas.js
- packages/entity-detail/src/modules/entityDetail/sagas.spec.js
Can be used in the parent component to display a confirmation message
if user navigates away from the detail view, but has unsaved changes.
> feat(entity-detail): Introduce external event `onTouchedChange`

- packages/entity-detail/src/components/ReduxFormFieldAdapter/ReduxFormFieldAdapter.js
- packages/tocco-util/src/formField/formField.js
- pass submitting to formfield and handle readonly there.
This change helps to make code simpler.
> refactor(entity-util): formField readonly clean up

- .travis.yml
- only deploy showcase if its not a cron job.
Otherwise there are unnecessary commits on gh-pages branch
> chore: cron job no showcase deployment

- package.json
Omitting the + means we can't upgrade to a new version of the
license should the copyright holder of any commit ever be any
other party than Tocco. Also, we really want to be able to
upgrade in case the license turns out to be flawed, legally
unenforceable or if legal circumstances change.
note: SPDX allows a + suffix to indicate "or any later version"
> chore(tocco-client): switch license to AGPLv3+ (adding the +)

- packages/tocco-util/src/rest/index.js
- packages/tocco-util/src/rest/rest.js
- packages/tocco-util/src/rest/rest.spec.js
- New functions/generators `requestSaga` (for function `request`)
and `getRequestSaga` (for function `getRequest`).
- Advantage of sagas instead of normal functions: we can put
redux actions or call other sagas (will be used for client question
stuff, which will be handled directly in the REST utils).
- Old functions `request` and `getRequest` are deprecated and
should not be used anymore.
> feat(tocco-util): Add REST request functions as sagas

- packages/entity-browser/src/main.js
This way we don't have to define the fetch mock in both modules (for example
the text resources of the `entity-detail` module)
> fix: Include `entity-detail` fetch mocks in `entity-browser`

- packages/entity-detail/src/util/detailView/reduxForm.js
when loaded in nice2 context, getDirtyFields always returned an empty array.
It seems like the reduce function from lodash internally uses a function, that behaves differently when running in nice2 context.
Probably a polyfill overwrites a functionality.
It couldn't be analyzed what exactly caused this so in a simple workaround the whole method got rewritten to work without _reduce
> refactor(entity-detail): rewrite getDirtyFields

- packages/entity-detail/src/util/detailView/asyncValidation.js
- packages/tocco-util/src/rest/index.js
- packages/tocco-util/src/rest/request.js
- packages/tocco-util/src/rest/rest.js
- packages/tocco-util/src/rest/rest.spec.js
This function returns a promise and can be used outside of sagas.
Please note that in contrast to `requestSaga` it does not support
client questions. Whenever possible, `requestSaga` should be used.
> refactor: Replace deprecated function `request` with `simpleRequest`

- packages/entity-list/src/components/SearchForm/SearchForm.js
- otherwise there will be an error, if an empty array is not set in input
> refactor(entity-list): preselectedSearchFields input not mandatory

- packages/entity-list/src/input.js
- packages/entity-list/src/modules/list/sagas.js
- packages/entity-list/src/modules/list/sagas.spec.js
- packages/entity-list/src/modules/searchForm/actions.js
- packages/entity-list/src/modules/searchForm/reducer.js
- packages/entity-list/src/modules/searchForm/reducer.spec.js
- packages/entity-list/src/modules/searchForm/sagas.js
- packages/entity-list/src/modules/searchForm/sagas.spec.js
- before this change it could have happened, that the list loads it data
without the preselected search fields being set.
- move reset saga to search module since the button is there
> refactor(entity-list): fix sequence problem

- build/webpack.config.js
- this plugin helps to reduce the bundle size about 30kbs.
Unfortunately lodash does not behave exactly same.
For example _reduce with an object is not possible. The plugin is added
in Dev mode as well to notice this behavior during development and
prevent production only errors.
> chore: use webpack lodash plugin in dev mode

- packages/tocco-ui/src/EditableValue/specUtils.js
- packages/tocco-ui/src/EditableValue/typeEditors/DateEdit.js
- packages/tocco-ui/src/EditableValue/typeEditors/DateEdit.spec.js
- packages/tocco-ui/src/EditableValue/utils.js
- packages/tocco-ui/src/EditableValue/utils.spec.js
AbstractDate returns an array of ISO date-time strings in UTC.
We need to convert the string into a local date (without time)
in the current time zone (example if we're currently in the
GMT+2 time zone: '2017-04-12T22:00:00.000Z' -> '2017-04-13')
> fix(tocco-ui): Use date only instead of date with time in DateEdit

- packages/entity-list/src/modules/list/sagas.js
- packages/entity-list/src/modules/list/sagas.spec.js
The `initialize` saga is called when the list view is mounted.
In case it's already initialized, we should still refresh the current
page, since the displayed data might be outdated now (example: user
switches from the list view to the detail view of an entity, updates
the entity and returns back to the list -> list is now outdated and
should be refreshed).
> feat(entity-list): Refresh the current page on mount if initialized

- packages/tocco-ui/src/Button/Button.js
- packages/tocco-ui/src/Button/Button.spec.js
- packages/tocco-ui/src/Button/example.js
- without this change, the pending icon only was shown, if an icon was
set on button
- improve example
> refactor(tocco-ui): show pending indicator

- packages/entity-browser/package.json
- packages/entity-detail/package.json
- packages/entity-list/package.json
- packages/login/package.json
- packages/merge/package.json
- packages/tocco-ui-showcase/package.json
- packages/tocco-ui-showcase/yarn.lock
- packages/tocco-util/package.json
- plop/templates/package/package.json
- with >0.1.0 lerna bootstrap always looking for the newest version (local).
If a packages gets updated, one doen't have to update each package.json
> chore: set flexible package version for local packages

- package.json
- this flag got lost during refactoring
> chore: (re)disable istanbul for saucelabs

- packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
- set local change only if already initialized
- setDate only when new value. Otherwise this component could trigger a endless loop
if used with redux-form
> refactor(tocco-ui): date abstract fix

- packages/entity-browser/README.md
- packages/entity-browser/src/input.js
- packages/entity-browser/src/main.js
- packages/entity-browser/src/routes/entity-browser/route.js
- packages/tocco-util/src/route/input.js
- packages/tocco-util/src/route/input.spec.js
- packages/tocco-util/src/route/route.js
- previous input dispatching did not effect the app since it got
overwritten by the route. instead the way the route dispatches the input
got optimized and default values are now possible.
- introduce new input "memoryHistory". When true, a memory based history is used. This
should be set if the application run in an environment where the url cannot be used
as history. e.g. when included as tab in nice2
> fix(entity-browser): dispatching input & history configurable

- packages/entity-detail/src/dev/textResources.json
- packages/entity-detail/src/modules/entityDetail/sagas.js
- packages/tocco-ui/src/FormField/FormField.js
- packages/tocco-util/src/actions/modules/actionHandlers/simpleAction.js
- packages/tocco-util/src/mockData/data/textResources.json
- use 'uploadFailedTitle' and 'uploadFailedMessage' text-resource from
components.form since detail gets refactored away later.
- adjust 'alt' attribute and set at title as well for chrome
- rename actions.successTitle
> refactor: text-resource cleanup

- packages/entity-list/README.md
- packages/entity-list/src/components/ListView/ListView.js
- packages/entity-list/src/components/ListView/ListView.spec.js
- packages/entity-list/src/components/Table/Table.js
- packages/entity-list/src/components/Table/Table.scss
- packages/entity-list/src/containers/ListViewContainer.js
- packages/entity-list/src/input.js
- packages/entity-list/src/main.js
- packages/entity-list/src/modules/list/sagas.js
- packages/entity-list/src/modules/list/sagas.spec.js
- packages/entity-list/src/util/api/forms.js
- packages/entity-list/src/util/api/forms.spec.js
- packages/tocco-util/src/mockData/data/dummy_entity_list_form.json
- packages/tocco-util/src/mockData/data/user_list_form.json
- new flag selectable in list form definition determines if checkboxes are shown
- remove input param selectable on entity-list (is now set via form defintion)
- action selection only current page (no multi page selection at the moment)
> feat(entity-browser): simple selection concept

- packages/tocco-ui/package.json
- packages/tocco-ui/src/EditableValue/EditableValue.scss
- packages/tocco-ui/src/EditableValue/typeEditors/MultiRemoteSelect.js
- packages/tocco-ui/src/EditableValue/typeEditors/MultiRemoteSelect.spec.js
- packages/tocco-ui/src/EditableValue/typeEditors/MultiSelect.js
- packages/tocco-ui/src/EditableValue/typeEditors/MultiSelect.spec.js
- packages/tocco-ui/src/EditableValue/typeEditors/RemoteSelect.js
- packages/tocco-ui/src/EditableValue/typeEditors/RemoteSelect.spec.js
- packages/tocco-ui/src/EditableValue/typeEditors/SingleSelect.js
- packages/tocco-ui/src/EditableValue/typeEditors/SingleSelect.spec.js
- packages/tocco-ui/src/EditableValue/typeEditors/TetherSelectWrap.js
- packages/tocco-ui/yarn.lock
- to prevent overflow hidden problems and dynamically position the menu
on top or at bottom
- update react-select
> refactor(tocco-ui): wrap select menu in tether

- packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.spec.js
- the async loading of the datepickr can sometimes take longer than
2000 seconds.
> test(tocco-ui): increase timeout for DateAbstract test

- build/karma.conf.js
- package.json
- packages/entity-list/src/components/ListView/ListView.js
- yarn.lock
- update to latest webpack version (bug fixes) and dev-server/hot-middleware
- update lodash-webpack plugin (to get rid deprecated warning)
- only show errors in test run
> chore: webpack update

- packages/tocco-util/src/color/contrast.js
- packages/tocco-util/src/color/contrast.spec.js
- contrast for red (#ff0000) should be a bright value since dark/black is not that readable
- add unit test
> refactor(tocco-util): color contrast tune lumniance limit

- packages/entity-detail/src/components/SubGrid/SubGrid.js
- packages/entity-detail/src/components/SubGrid/SubGrid.spec.js
- packages/entity-detail/src/util/detailView/fromFieldFactories/subGrid.js
- packages/entity-detail/src/util/detailView/fromFieldFactories/subGrid.spec.js
The previously hardcoded page limit of 5 now acts as a default value.
> feat(entity-detail): Allow sub grid page limit to be set in model

- packages/scheduler/src/components/FullCalendar/FullCalendar.js
- packages/scheduler/src/components/FullCalendar/FullCalendar.scss
the description property of a calendar event now will return html
instead of text. to correctly apply the html to the popover the
`dangerouslySetInnerHtml` property for React components is used.
the popover content has to be split because in raw html code the react
component `Conflict` will not be recognized otherwise.
> chore(scheduler): use raw html in calendar event popover

- packages/tocco-ui/src/Preview/Preview.js
- packages/tocco-ui/src/Preview/StyledPreview.js
- packages/tocco-ui/src/Preview/example.js
- packages/tocco-ui/src/Upload/UploadProgress.js
- packages/tocco-ui/src/Upload/View.js
- packages/tocco-ui/src/utilStyles/index.js
- packages/tocco-ui/src/utilStyles/propTypesValidator.js
- packages/tocco-ui/src/utilStyles/propTypesValidator.spec.js
I have implemented maximal dimension as parameter because not always is such a limitation desirable or should be used equally. Unit 'vw' and 'vh' enables responsiveness to some limitations. 
Current implementation corresponds with scale only but not with a crop and scale. A crop and scale effect would be possible with css property background-image and an additional element but needs a lot more logic. 
Personally I question an automatic crop function in an editor centric view anyway. Crop is a good choice to assures a nice aligned layout in a multi image read only view but not to administer raw data.
> style(tocco-ui): limit maximal dimension of Preview image

- packages/tocco-util/src/rest/clientQuestions.js
- packages/tocco-util/src/rest/clientQuestions.spec.js
- We don't want to further develop client questions support.
Form client questions would need some refactoring to work with the new
advanced search feature. Also it creates a circular dependency between
simple-form and tocco-util. Therefore it gets removed completely.
> refactor(tocco-util): remove FormQuestionHandler in action

- packages/tocco-util/src/notifier/modules/modalComponents/ModalDisplay.js
- packages/tocco-util/src/notifier/modules/modalComponents/ModalDisplay.spec.js
- packages/tocco-util/src/notifier/modules/modalComponents/ModalDisplayContainer.js
- first simple solution to show a modal over a modal. this is used
for example to prompt an advancedsearch modal over an action form data modal.
> feat(tocco-util): allow multiple modals

- packages/tocco-util/src/actions/components/ActionGroup.js
- packages/tocco-util/src/actions/components/GroupElement.js
- since creation of GroupElement prop onSelect was required
- only ActionGroup uses GroupElement but has never passed prop onSelect
> fix(tocco-util): remove unused prop onSelect

- packages/resource-scheduler/package.json
- packages/resource-scheduler/yarn.lock
- yarn.lock
- due to lack of ie11 support
- remove upath from yarnlock so yarn setup can be run
> refactor(resource-scheduler): update split pane package

- packages/tocco-ui/src/FormattedValue/typeFormatters/PhoneFormatter.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/PhoneFormatter.spec.js
PhoneFormatter could get empty object and threw an
error on async loading
> fix(tocco-ui): fix phoneformatter async bug

- packages/entity-list/src/util/api/entities.js
There are other types such as "multi" that get implemented later.
As a workaround a fallback to an empty string is added.
> refactor(entity-list): add default for unhandled list types

- packages/tocco-ui/src/Menu/StyledMenuStack.js
error:    ItemMenu and ItemAccordion in MenuStack are layout out horizontally.
solution: Use flexbox properties to layout vertically.
reason:   Error was introduced by change d7f3c8ab3.
> fix(tocco-ui): stack menu items horizontally

- packages/tocco-ui/src/Button/Button.js
- packages/tocco-ui/src/Button/example.js
- packages/tocco-ui/src/Icon/Icon.js
- packages/tocco-ui/src/IconTocco/IconTocco.js
- packages/tocco-ui/src/IconTocco/StyledIconTocco.js
- packages/tocco-ui/src/LoadMask/StyledLoadMask.js
- correct spacing for buttons with prop spacing
- do not pass obsolete props ink, look and theme to component FontAwesomeIcon
- simplify color handling in component IconTocco by inheriting colors with svg feature currentColor instead of redeclaring
- declare primary color for IconTocco in LoadMask
> fix(tocco-ui): ensure correct color and spacing for icons

- .eslintrc
- build/webpack.config.js
- config/_base.js
- packages/app-extensions/src/appFactory/store/store.js
- server/main.js
To improve (re)build time:
- no source map files in CI mode
- no source map files for 3rd party bundles
- use eval-source-map for DEV and source-map for PROD
- improve webpack console log
- cleanup global vars
> chore: improve build with sourcemaps

- README.md
- package.json
- this is a temporary fix. Long term the message should disappear
as soon as user activity (a click) is registered. This will prevent
unseen successful messages.
> refactor(app-extensions): auto hide successful action messages

- packages/app-extensions/src/notifier/components/StyledNotifier.js
The fixed positioned div (.toastr-attention) is not displayed correctly in Safari if the div is nested in an element which declares scroll for overflow-y (.top-right).
Check https://stackoverflow.com/questions/26704903/only-in-safari-positionfixed-child-cut-off-when-parent-is-positionfixed-and and https://bugs.webkit.org/show_bug.cgi?id=160953 for more information.
The colored background of .toastr-attention only covers the area of .top-right even if .toastr-attention spans the whole viewport. Which is wanted to prevent clicks while the blocking info is showed.
Since it is only a styling error in Safari and accessibility (scroll) and functionality (preventing clicks) is more important than visualization (background color) the background was made transparent.
> fix(app-extensions): workaround ugly style in safari

- packages/app-extensions/src/form/ReduxFormFieldAdapter.js
- packages/app-extensions/src/form/formBuilder.js
- packages/app-extensions/src/formData/advancedSearch/actions.js
- packages/app-extensions/src/formData/advancedSearch/sagas.js
- packages/app-extensions/src/formData/advancedSearch/sagas.spec.js
- packages/app-extensions/src/formData/formData.js
- packages/app-extensions/src/formData/index.js
- packages/app-extensions/src/formData/values/actions.js
- packages/app-extensions/src/formData/values/sagas.js
- packages/app-extensions/src/formData/values/sagas.spec.js
- packages/app-extensions/src/formField/editableValueFactory.js
- packages/app-extensions/src/formField/editableValueFactory.spec.js
- packages/app-extensions/src/formField/formField.js
- packages/entity-browser/src/dev/input-no-mock.json
- packages/entity-detail/src/components/DetailForm/DetailForm.js
- packages/entity-detail/src/containers/DetailFormContainer.js
- packages/entity-detail/src/main.js
- packages/entity-detail/src/modules/entityDetail/actions.js
- packages/entity-detail/src/modules/entityDetail/sagas.js
- packages/entity-detail/src/modules/entityDetail/sagas.spec.js
- packages/entity-list/src/containers/SearchFormContainer.js
- packages/entity-list/src/main.js
- packages/entity-list/src/modules/searchForm/actions.js
- packages/entity-list/src/modules/searchForm/sagas.js
- packages/entity-list/src/modules/searchForm/sagas.spec.js
- packages/simple-form/src/containers/FormContainer.js
- packages/simple-form/src/main.js
- packages/simple-form/src/modules/simpleForm/actions.js
- packages/simple-form/src/modules/simpleForm/sagas.js
- This refactoring helps to eliminate duplicate code in the packages and is
the groundwork for an upcoming refactoring.
The goal is to move all "form utils" to formData so that they can be
provided with a container.
> refactor: move advanced search and value change to app-extensions

- packages/app-extensions/src/form/FormBuilder.js
- packages/app-extensions/src/form/FormBuilder.spec.js
- packages/app-extensions/src/formField/formattedValueFactory.js
- packages/app-extensions/src/formField/formattedValueFactory.spec.js
- packages/tocco-util/src/mockData/entityFactory.js
- in readonly mode field were not displayed because wrongly set
parameters (formName was missing) after refactoring.
- also hide fields if field is absent in value object.
- adjust tests
- add mockData for decimal and moneyamount field
> fix(app-extensions): readonly display bug

- packages/app-extensions/src/appFactory/ThemeWrapper.js
Constant mergedTheme guarantees already that ToccoTheme is available. 
By adding theme as default prop only the console warning is eliminated.
> refactor(app-extensions): specify ToccoTheme as default

- packages/tocco-ui/src/Button/Button.js
- packages/tocco-ui/src/Button/Button.stories.js
- packages/tocco-ui/src/Icon/Icon.js
- do not pass on Button defined Icon props to FontAwesomeIcon to suppress warning
- adapt icon prop on Button story to suppress warning
> fix(tocco-ui): do not pass unnecessary props to FontAwesomeIcon

- packages/tocco-ui/src/Upload/View.js
- packages/tocco-ui/src/Upload/View.spec.js
- A query param was introduces in backend to set the Content-Disposition as attachment.
This header is needed for a direct file download with a link attribute.
Changelog: Upload Component: Add download query param to file download link
> refactor(tocco-ui): add download query param to Upload download

- packages/scheduler/src/components/Conflict/Conflict.js
- packages/scheduler/src/components/FullCalendar/FullCalendar.js
- An event description can contain HTML. Use FormattedValue to proper format
otherwise HTML would be shown as string.
Changelog: Format HTML event descriptions
> fix(scheduler): fix description HTML display

- packages/tocco-ui/src/EditableValue/typeEditors/DurationEdit.js
- packages/tocco-ui/src/EditableValue/typeEditors/DurationEdit.spec.js
- Label of StatedValue covers units of DurationEdit which looks ugly and is confusing.
- Show units only if focus is on DurationEdit or if hours or minutes are set.
> feat(tocco-ui): show unit in DurationEdit if not disturbing

- packages/sso-login/src/components/ProviderButton/ProviderButton.js
- The encodedWindowUrl as parameter is needed for the registration
part in the sso-login process. From now on login and registrations
are possible through sso.
Refs: TOCDEV-611
> feat(sso-login): add encodedWindowUrl to sso url in ProviderButton

- packages/tocco-util/src/saga/saga.js
- The problem is that JS Error object cannot be naively stringified.
Therefore some attribute where picked from the object.
> refactor(tocco-util): improve error handling

- packages/app-extensions/src/appFactory/App.js
- packages/app-extensions/src/appFactory/appFactory.js
- without the watch config, the whole dom (body) will be watched.
This leads to problems when an app in embedded into nice2 since nice
also uses fontawesome.
Refs: TOCDEV-1083
Changelog: Restrict global icon dom watch
> fix(app-extensions): restrict global icon dom watch

- packages/entity-list/src/modules/searchForm/sagas.js
- packages/entity-list/src/modules/searchForm/sagas.spec.js
- packages/entity-list/src/util/api/forms.js
- packages/entity-list/src/util/api/forms.spec.js
- packages/tocco-util/src/mockData/data/dummy_entity_search_form.json
- if a search form has a parent condition and a search-field with the same
path, this field must not be a full-text search field. And it should be
read only. This change makes sure such fields are replaced with a readonly
single-select field.
Refs: TOCDEV-1084
Changelog: Fix parent Search field bug
> refactor(entity-list): replace parent search field

- packages/app-extensions/src/actions/actionTypes.js
- packages/app-extensions/src/actions/modules/actionHandlers/index.js
- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.spec.js
- The first time a legacy action handler is executed, the required
ExtJS and legacy-client sources are loaded
- There's are still some things to do. For instance, there are several
types of record selections that must be supported eventually (e.g.
actual selection of some particular records by key or a set of entities
defined by query conditions only). At the moment, only actual selection
by entity key is implemented.
Refs: TOCDEV-1507
> feat(app-extension): add handler for legacy actions (ExtJs)

- packages/simple-form/src/dev/input.json
- wrap fields and relations in paths object in simple-form mocks
- was changed some time ago in code, but mocks where never adjusted to fit
> fix(simple-form): correct simple-form mocks

- packages/entity-list/src/components/Table/Table.js
- packages/entity-list/src/modules/list/sagas.js
- packages/entity-list/src/modules/list/sagas.spec.js
Refs: TOCDEV-1650
Changelog: Fix fallback sorting bug
> refactor(entity-list): only set fallback sorting if field exists

- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.spec.js
- Stylesheet is loaded from legacy code base
- The stylesheet will contain all CSS rules that are necessary to
make legacy actions look good in the new client
- The stylesheet won't be included in the legacy client
Refs: TOCDEV-1581
> style(app-extension): Include dedicated stylesheet for legacy actions

- packages/tocco-ui/src/FormattedValue/typeFormatters/HtmlFormatter.js
- Necessary so that notifications with HTML content are formatted
properly. Without the `breakWords` property (which is true for the
notifications) passed to the `StyledHtmlFormatter`, the notification
content is truncated after a few words, which makes many notifications
more or less useless.
- The other type formatters respect the `breakWords` prop, too.
Was it ignored in the HtmlFormatter on purpose?
Refs: TOCDEV-1698
> style(tocco-ui): Take `breakWords` into account in HtmlFormatter

- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.spec.js
The scope is required at least for the LabelReportAction legacy action.
Refs: TOCDEV-1825
> feat(app-extensions): Add form scope to action situation

- packages/app-extensions/src/actions/components/ActionGroup.js
- packages/tocco-util/src/mockData/data/user_detail_form.json
The property for the default action in the action group definition
is called `defaultAction`, not `action`.
Refs: TOCDEV-1877
> fix(app-extensions): Fix default actions for action groups

- packages/admin/src/main.js
- server/index.html
- Those actions are run via the ReactContainer and the `reactRegistry`
which is available on the global scope now (thanks to the new import
of nice2-newclient-react-registry.release.js)
- The reactRegistry needs a React and ReactDOM instance to render the
registered apps. Those are usually found on the global window scope,
but not if the admin is run locally -> in this case they're imported
via ES6 imports. The reactRegistry now has a setter for the React
and ReactDOM instance to use (default is `window.React` resp.
`window.ReactDOM`).
- Note that in the production environment (i.e. on master.tocco.ch/beta)
those actions already worked because the React libraries and the
reactRegistry are included via the nice2-react.release.js file in the
beta/index.html)
- This commit depends on: …
> fix(admin): fix "legacy actions" that are implemented in React

- packages/admin/src/main.js
Quickfix for the storybook. To fix everything properly, the reactRegistry
should be made available on the global scope in the storybook.
Refs: TOCDEV-1886
> fix(admin): only call `setReact` if reactRegistry and function exist

- packages/app-extensions/src/field/editableTypeConfigs/remote.js
- packages/app-extensions/src/field/editableTypeConfigs/select.js
- packages/app-extensions/src/field/formattedTypeConfigs/remote.js
- packages/app-extensions/src/field/formattedValueFactory.js
Refs: TOCDEV-1816
Changelog: Support multi-path select and remote fields
> refactor(app-extension): load targetEntity from form-model

- packages/tocco-ui/src/EditableValue/typeEditors/Document.js
`onChange` and `options` both are optional props and can be undefined.
Refs: TOCDEV-1902
> fix(tocco-ui): prevent null pointer exceptions in Document component

- packages/user-qr-action/.npmignore
- packages/user-qr-action/.yarnrc
- packages/user-qr-action/README.md
- packages/user-qr-action/package.json
- packages/user-qr-action/src/components/UserQrCode/UserQrCode.js
- packages/user-qr-action/src/components/UserQrCode/index.js
- packages/user-qr-action/src/containers/UserQrCodeContainer.js
- packages/user-qr-action/src/dev/fetchMocks.js
- packages/user-qr-action/src/dev/input.json
- packages/user-qr-action/src/dev/textResources.json
- packages/user-qr-action/src/main.js
- packages/user-qr-action/src/modules/qrCode/actions.js
- packages/user-qr-action/src/modules/qrCode/index.js
- packages/user-qr-action/src/modules/qrCode/reducer.js
- packages/user-qr-action/src/modules/qrCode/reducer.spec.js
- packages/user-qr-action/src/modules/qrCode/sagas.js
- packages/user-qr-action/src/modules/qrCode/sagas.spec.js
- packages/user-qr-action/src/modules/reducers.js
- packages/user-qr-action/src/utils/qrCodeUtils.js
- packages/user-qr-action/src/utils/qrCodeUtils.spec.js
Takes selection of the admin as input (only selection for entity name
"User" and with type "ID" supported and requires exactly one selected
key).
Refs: TOCDEV-1888
> feat(user-qr-action): add action that displays QR code of a user

- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
- returns an object containing the record id if selection contains
exactly one element
- this emulates the `getRecord()` function of the GridActionContext
which is needed for grid actions
-> for instance the `TriggerBatchjobAction`
Refs: TOCDEV-1984
> feat(app-extensions): add `getRecord()` to legacy action context

- packages/entity-list/src/components/Table/StyledTable.js
- packages/entity-list/src/util/api/forms.js
- packages/entity-list/src/util/api/forms.spec.js
- packages/entity-list/src/util/cellRenderer.js
- ignore form model width (for the moment) since the new client expects a absolute pixel value but the old client works with relative number.
- Decrease cell min-width
- break words false for display expressions in table
- Fix no data found styling
> refactor(entity-list): tableV2 improvements

- packages/admin/src/routes/entities/components/EntitiesRoute/EntitiesRoute.js
- packages/admin/src/routes/entities/modules/path/sagas.js
- At the moment the useEffect hook was triggered, the history object was already updated. That means that in case of a redirect from /key to key/detail, the detail view got initialized twice. To fix this issue a const was introduce to preserve the location
Refs: TOCDEV-1939
> refactor(admin): fix duplicate call of path loading

- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.spec.js
- The release sources are compressed and thus load faster
- Now that most of the legacy actions work in the new client and
there's not a lot to debug anymore, we don't need the debug sources
anymore
Refs: TOCDEV-2083
> feat(app-extension): Use `release` sources for legacy actions

- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
Since https://git.tocco.ch/c/nice2/+/37586 the path of the action is
stored in new attribute called `path` and not in `id` anymore.
Refs: TOCDEV-2070
> fix(app-extensions): Use `path` attribute of legacy action definition

- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.spec.js
- If a legacy action is executed in the legacy environment
(e.g. in a new react action that is embedded in the legacy admin
client (-> e.g. input edit action), or in the react entity-browser
widget in a CMS page), we shouldn't load all the sources (JS/CSS)
that are required in the new admin client (because it might break
JS functionality as well as styling)
- To control which sources should be loaded, the environment provides
a global variable `legacyActionEnv`. If no variable is set, the
new admin client environment is assumed.
- Also see https://git.tocco.ch/c/nice2/+/37708
Refs: TOCDEV-2238
> fix(app-extensions): Don't load legacy action sources twice

- packages/app-extensions/src/form/FormBuilder.js
- packages/app-extensions/src/form/FormBuilder.spec.js
- packages/app-extensions/src/form/ReduxFormFieldAdapter.js
- packages/app-extensions/src/formField/formField.js
- packages/simple-form/src/components/Form/Form.js
- rename readonly param to "parentReadOnly" to make origin more clear
- introduce one function to determine whether a field is rendered with "readOnly" mapping
- remove unused propTypes
> refactor(app-extension): cleanup readonly mapping

- packages/admin/src/routes/entities/components/Action/actions/ResourceScheduler.js
For the deployment on master.tocco.ch, the admin input prop `baseRoute`
(which is used as `basename` for the router) is set to `/beta`.
By using `history#createHref` the URL is prefixed with the basename
which was missing before -> the entities that should be opened when
the user clicks on an event in the scheduler couldn't be displayed
on master.tocco.ch because the URL was wrong.
Refs: TOCDEV-2347
> fix(admin): Take `baseRoute` into account for resource scheduler

- packages/admin/src/components/Navigation/StyledComponents.js
Refs: TOCDEV-2417
Changelog: Add background color to search box to prevent scrolling text shining through under it
> refactor(tocco-ui): add bg color to search box

- packages/entity-list/src/components/Table/StyledTable.js
- packages/entity-list/src/components/Table/Table.js
- packages/entity-list/src/containers/TableContainer.js
- packages/entity-list/src/modules/list/actions.js
- packages/entity-list/src/modules/list/reducer.js
- packages/entity-list/src/modules/list/reducer.spec.js
- packages/entity-list/src/modules/list/sagas.js
- packages/entity-list/src/modules/list/sagas.spec.js
- packages/entity-list/src/util/api/forms.js
- packages/entity-list/src/util/api/forms.spec.js
By default, a row is clickable. If the `clickable` flag is set on the
table in form model, the rows aren't clickable anymore. However, if
`selectable` is true they still can be selected using the checkbox.
Refs: TOCDEV-2364
> feat(entity-list): Support `clickable` flag in table form model

- packages/entity-list/src/modules/list/sagas.spec.js
- packages/entity-list/src/util/api/fetchOptions.spec.js
- packages/tocco-util/src/tqlBuilder/tqlBuilder.js
- packages/tocco-util/src/tqlBuilder/tqlBuilder.spec.js
- change string comparator to "like"
- add boolean handler that does not handle false values to imitate the current clients behavior
Changelog: Handle strings in search with "like" and add boolean handler
> refactor(tocco-util): improve tql builder

- packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
Refs: TOCDEV-2440
Changelog: Adjust search filter area height to have minimal padding at bottom when expanded
> refactor(entity-list): adjust search filter height

- packages/tocco-ui/src/Table/StyledTable.js
Refs: TOCDEV-2371
Changelog: Set box sizing on td to prevent overwrite in external context
> refactor(tocco-ui): set box sizing on td

- packages/app-extensions/src/formData/tooltips/sagas.js
- packages/app-extensions/src/formData/tooltips/sagas.spec.js
- packages/app-extensions/src/rest/helpers.js
- packages/app-extensions/src/rest/helpers.spec.js
Refs: TOCDEV-1567
Changelog: Remove all usages of old display endpoints and use 'entities/2.0/displays'
> refactor(app-extensions): use new displays endpoint everywhere

- packages/tocco-ui/src/StatedValue/StatedValue.js
- packages/tocco-ui/src/StatedValue/StyledStatedValue.js
Refs: TOCDEV-2413
Changelog: 
- Remove stated value error animation, as it caused a wobble effect
- Add focused prop to styled stated value error to prevent evaluation on every key stroke
> refactor(tocco-ui): fix stated value error display

- packages/input-edit/src/components/InputEdit/InputEdit.js
- packages/input-edit/src/components/InputEdit/InputEditContainer.js
- packages/input-edit/src/components/InputEditTable/InputEditTable.js
- packages/input-edit/src/modules/inputEdit/actions.js
- packages/input-edit/src/modules/inputEdit/reducer.js
- packages/input-edit/src/modules/inputEdit/sagas.js
- packages/input-edit/src/modules/inputEditInformation/sagas.js
- packages/input-edit/src/modules/inputEditSearch/actions.js
- packages/input-edit/src/modules/inputEditSearch/reducer.js
- packages/input-edit/src/modules/inputEditSearch/sagas.js
- packages/input-edit/src/modules/inputEditSearch/sagas.spec.js
- packages/input-edit/src/modules/inputEditTable/sagas.js
- packages/input-edit/src/modules/inputEditTable/sagas.spec.js
- load data only if search form is initialized and prevent loadData to be called twice initially
- return null if columns are empty to calm down loading process
Refs: TOCDEV-2429
> refactor(input-edit): optimize input edit initialization

- packages/tocco-ui/src/Select/Select.js
- otherwise blur is never called and listeners such as auto-complete would not be triggered
- disable blur on input select to make it work with redux form
> refactor(tocco-ui): optimize blur effect

- packages/tocco-util/src/route/route.js
- packages/tocco-util/src/route/route.spec.js
If caching of a route should be enabled, a key for the cache can be
passed to `loadRoute` as the 4th argument.
In this case the already loaded component will be returned which might
eliminate unnecessary rerenders of the same route.
Refs: TOCDEV-2560
> feat(tocco-util): Allow caching of loaded async route component

- packages/scheduler/src/components/FullCalendar/FullCalendar.js
- this makes sure, if multiple calendars are in the dom (multiple nice tabs opened), the right one is selected
Refs: TOCDEV-2552
Changelog: Fix deselect all bug
> fix(scheduler): improve querySelector with boundary

- packages/tocco-ui/src/Typography/styledTypography.js
Refs: TOCDEV-2821
Changelog: Change typography link color to secondary (blue)
> refactor(tocco-ui): change link color

- server/main.js
- otherwise there is an error when the backend (localhost:8080) is not running
and a mocked version is started
> chore: only serve nice2 resource if mock is not active

- packages/admin/src/components/Admin/StyledComponents.js
Default z-index of button is 1000 which is higher than the mask of the
legacy action modal windows (not good).
It seems like it doesn't need to be higher than 1, therefore we set it
to 1.
Refs: TOCDEV-2549
> fix(admin): Hide burger menu button behind legacy modal window mask

- packages/admin/src/routes/docs/components/DocsRoute/DocsRoute.js
- packages/admin/src/routes/docs/components/DocsView/DocsView.js
There were several issues when navigating around:
- When the user searched and then navigated to a search result (to
a document) and then returned to the search results using the
back button, the list view was reset to the list of domains.
We want to return to the search results instead. This is achieved
by reusing the existing store (using the viewPersistor).
- There proper URL should always be up to date according to the current
view (/docs vs. docs/search). This was fixed by cleaning up the
`onSearchChange` event handlers.
Refs: TOCDEV-2881
> fix(admin): Fix navigation between search/tree/document view

- packages/tocco-ui/src/LoadMask/StyledLoadMask.js
Refs: TOCDEV-2787
Changelog: Reset load mask height to 100%
> refactor(tocco-ui): set load mask height

- packages/entity-list/src/modules/searchForm/sagas.js
- packages/entity-list/src/modules/searchForm/sagas.spec.js
Refs: TOCDEV-2575
Changelog: Default search filter is disabled when opening the relations view of an entity as its own list
> feat(entity-list): don't use default filter in list with parent

- packages/entity-list/src/modules/preferences/reducer.js
- packages/entity-list/src/modules/preferences/reducer.spec.js
- resetting to null resulting in a infinite waiting for the preferences to be loaded in getPreferencesSorting.
Refs: TOCDEV-2894
Changelog: Fix table reset
> refactor(entity-list): reset preferences to empty values

- packages/tocco-ui/src/Table/TableHeader.js
Refs: TOCDEV-2062
Changelog: Use column label as titles when hovering over headers
> feat(tocco-ui): add title to column headers

- packages/entity-list/src/components/ListView/ListView.js
- packages/entity-list/src/components/ListView/ListView.spec.js
- Otherwise it could be, that preferences are not loaded at this point.
Hence a null pointer would occur.
> refactor(entity-list): add preferences defined check

- packages/tocco-ui/src/EditableValue/StyledEditableValue.js
Refs: TOCDEV-2837
Changelog: Disable pointer events on Desktop as text can't be copied otherwise in Firefox
> refactor(tocco-ui): disable pointer event on desktop

- packages/tocco-ui/src/Menu/StyledComponents.js
Refs: TOCDEV-2965
Changelog: Remove obsolete right margin inside menu item
> refactor(tocco-ui): remove obsolete margin

- deployment/deploy_storybook_gitlab.sh
this pull potentially fixes a problem, where the branch is not up to date when pushing.
This can happen if another ci pushed to the gh-pages branch after the current job did
clone the project.
> chore: fix ci parallel problem

- packages/tocco-ui/src/LoadMask/StyledLoadMask.js
Refs: TOCDEV-3014
Changelog: Prevent content ghosting in safari when opening/closing collapsibles
> refactor(tocco-ui): prevent content ghosting

- packages/entity-detail/src/components/DetailForm/DetailForm.js
- packages/tocco-ui/src/Layout/StyledLayoutBox.js
- packages/tocco-ui/src/Layout/StyledLayoutContainer.js
Refs: TOCDEV-3044
Changelog: Adjust left pane grid in detail view for android tablets to prevent overflow
> refactor(tocco-ui): adjust detail view

- packages/entity-list/src/components/SearchFilterList/utils.js
- a default filter is always listed before all other search filters
Refs: TOCDEV-2804
> fix(entity-list): fix sorting of search filters

- packages/tocco-ui/src/Preview/Preview.js
- packages/tocco-ui/src/Upload/View.js
Refs: TOCDEV-3013
Changelog: Upload component: Show file names only in upload process
> refactor(tocco-ui): show file name only in upload process

- packages/tocco-util/src/api/entities.js
- packages/tocco-util/src/api/entities.spec.js
- before it could be, that fields starting with the same path name end up in the entity, even though they are not "dirty"
Refs: TOCDEV-3094
Changelog: Fix path dirty bug
> refactor(tocco-util): fix multi-path handling

- packages/app-extensions/src/form/formDefinition.js
- packages/app-extensions/src/form/formDefinition.spec.js
- if field id and path is not the same, this lead to an wrong default value
Refs: TOCDEV-3101
Changelog: Fix missing default values bug
> fix(app-extensions): set default values by path

- packages/entity-detail/src/modules/entityDetail/sagas.js
- packages/entity-detail/src/modules/entityDetail/sagas.spec.js
Cause of the bug:
Fields in related entities are contained in the flat entity
representation in the format '{relation name}.{field name}',
but the format in the list of the dirty fields is
'{relation name}--{field name}'.
Therefore, those fields are never considered dirty and thus those
fields are never added to the request.
Fix:
We have to convert the dirty field names back to
'{relation name}.{field name}' before calling `api.toEntity`.
Example (there aren't many of them):
One example where we want to write to a field in a related entity is
`relContent.description` (among other fields on `relContent`) in
`relResource_detail`.
Refs: TOCDEV-3118
> fix(entity-detail): Fix writing to fields in related entities

- packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
- packages/tocco-ui/src/EditableValue/typeEditors/DateTimeEdit.js
- packages/tocco-util/src/js/object.js
- packages/tocco-util/src/js/object.spec.js
- parse manually entered dates
- add button to clear field
- handle Enter key the same as Tab
Refs: TOCDEV-3091
Changelog: Added clear button to Date and DateTime fields. DateTime fields can now parse typed out dates as inputs.
> feat(tocco-ui): expand DateTimeEdit

- packages/app-extensions/src/formData/upload/sagas.js
- packages/app-extensions/src/formData/upload/sagas.spec.js
If the field is of a related entity (path: '{relation name}.{field name}'),
we have to transform the path before putting the redux-form `change`
action to update the field --> the field IDs in the redux form cannot
contain dots, which is why we have to transform them to `--`.
Refs: TOCDEV-3118
> fix(app-extension): Fix uploading documents via relation path

- packages/tocco-ui/src/Range/StyledRange.js
- packages/tocco-ui/src/StatedValue/StyledStatedValue.js
Refs: TOCDEV-3123
Changelog: Fix hidden extender and force border rendering of ranges in chrome
> refactor(tocco-ui): fix range display

- packages/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
Until now, the action context didn't have a panel (2nd constructor
parameter of the action context). This led to a null pointer when
the legacy action tried to call
`this.getActionContext().getPanel().getStore().reload()` in
`refreshListPanel()`.
Now we're providing a fake panel with a fake store to avoid the null
pointer exception and to reload the list.
Refs: TOCDEV-3100
> fix(app-extension): Fix legacy actions that call `refreshListPanel()`

- packages/admin/src/routes/docs/components/DocsView/DocsView.js
The entities lists also have 25 entries. This is why we choose 25
for the docs list as well.
> feat(admin): Increase docs list limit from 10 (default) to 25

- packages/admin/src/routes/docs/components/DocumentView/DocumentView.js
The new form `DmsResource_detail` contains display expressions instead
of legacy custom data providers, so they will be rendered in the
new client, too.
See https://git.tocco.ch/c/nice2/+/39800
Refs: TOCDEV-3120
> feat(admin): Add more information to docs detail form

- packages/merge/README.md
- packages/merge/src/components/MergeSummary/MergeSummary.js
- packages/merge/src/components/MergeSummary/MergeSummaryContainer.js
- packages/merge/src/components/MergeTable/CellRender.js
- packages/merge/src/components/MergeTable/Selection.js
- packages/merge/src/dev/input.json
- packages/merge/src/main.js
- packages/merge/src/modules/merge/actions.js
- packages/merge/src/modules/merge/sagas.js
- packages/merge/src/modules/merge/sagas.spec.js
- packages/merge/src/util/StyledComponents.js
- packages/merge/src/util/manyRelationEntityCount.js
Refs: TOCDEV-3081
Changelog: remove workaround for opening an entity list in the old client
> refactor(merge): use navigation strategy for old client

- packages/copy/src/modules/copy/sagas.js
location-field element in form has no path and produces a 400 "empty path" error during fetching the entity
Refs: TOCDEV-3293
> fix(copy): ignore field if path is null

- build/jest-setup.js
- otherwise sub apps (e.g. two-factor-connector in login app) will register itself with a wrong public path
Refs: TOCDEV-3330
Changelog: Fix empty pop-up in old client
> refactor: register app only if package name matches

- packages/two-factor-connector/README.md
- packages/two-factor-connector/src/main.js
- packages/two-factor-connector/src/modules/sagas.js
- packages/two-factor-connector/src/modules/sagas.spec.js
This event is fired whenever the size of the screen (resp. its height)
changes substantially (similar to the `resize` event of the login
and password update app).
This event, for instance, is useful if the app is rendered in a popup
window which should be centered whenever the height of the app changes.
Refs: TOCDEV-3048
> feat(two-factor-connector): Add external event `onResize`

- packages/entity-list/src/components/ColumnPicker/StyledColumnPicker.js
Refs: TOCDEV-3294
Changelog: Reset label spacing inside column picker for old client
> refactor(entity-list): reset column picker label

- packages/admin/src/modules/navigation/sagas.js
- packages/admin/src/modules/session/sagas.js
- packages/app-extensions/src/rest/helpers.js
- packages/app-extensions/src/rest/helpers.spec.js
- packages/login/src/modules/sagas.js
- packages/tocco-util/src/cache/cache.js
- packages/tocco-util/src/cache/cache.spec.js
- packages/tocco-util/src/cache/index.js
check if the user and business unit is the same if in the long term cache all items of the type form and menu are removed after the following events:
- page is refreshed (checking after the login is not enough because the tocco support login and cookies won't trigger the check)
- login (avoid problems with login after logout without reloading the page)
Additional fix:
- the loginSuccess event should be fired after the cache is cleared
Refs: TOCDEV-3273
Changelog: fix long term caching
> fix: fix long term caching

- packages/docs-browser/README.md
- packages/docs-browser/src/components/DocsView/DocsView.js
- packages/docs-browser/src/components/DocsView/DocsView.spec.js
- packages/docs-browser/src/components/DocsView/DocsViewContainer.js
- packages/docs-browser/src/components/DocsView/index.js
- packages/docs-browser/src/dev/input.json
- packages/docs-browser/src/main.js
Can, for instance, be used for the default mode of the public docs
browser ("domainTypes": ["public_file_repository"]).
Refs: TOCDEV-3368
Changelog: New input param `domainTypes` to filter domains
> feat(docs-browser): Add input param `domainTypes` to filter domains

- packages/docs-browser/src/modules/path/sagas.js
- packages/docs-browser/src/modules/path/sagas.spec.js
If root nodes are defined, the breadcrumbs navigation should "stop"
at the specified root node instead of showing the entire path up to
the actual domain node.
Also see: https://git.tocco.ch/c/nice2/+/40240
Refs: TOCDEV-3368
> fix(docs-browser): Only show breadcrumbs up to specified root node

- packages/docs-browser/README.md
- packages/docs-browser/src/components/DocumentView/DocumentView.js
- packages/docs-browser/src/components/DocumentView/DocumentViewContainer.js
- packages/docs-browser/src/main.js
Can be defined to override the default document detail form name
(which is "DmsResource")
Refs: TOCDEV-3458
> feat(docs-browser): Add input prop `documentDetailFormName`

- packages/entity-list/src/modules/list/sagas.js
- packages/entity-list/src/modules/list/sagas.spec.js
- packages/entity-list/src/modules/preferences/reducer.js
- packages/entity-list/src/modules/preferences/reducer.spec.js
if the setParent method was called while the entities are already loaded but the entity count request was not finished, the list was not reloaded because initialized is not true
> fix(entity-list): fix load data if parent is changed

- packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.js
- packages/tocco-ui/src/EditableValue/typeEditors/DateAbstract.spec.js
- only show clear button when data exists
- make clear button work after save
- make flatpickr popup respond well to tab and enter
- make sure flatpickr popup is closed when navigating to next field
Refs: TOCDEV-3091
Changelog: Clear button in date fields only show up when data has been entered, tab and enter can now be used to navigate in the calendar popup and between date fields
> feat(tocco-ui): improve DateAbstract handling

- packages/admin/src/routes/entities/components/DocsView/DocsView.js
- with view persistor active, the form is persisted and showActions has no effect
> refactor(admin): disable view persistor

- packages/tocco-ui/src/EditableValue/EditableValue.stories.js
- packages/tocco-ui/src/EditableValue/typeEditors/HtmlEdit.js
- in HTML Edit a onChange should only be triggered after user Input and never of api changes. Such api changes can be triggered if the value has content that is not wrapped in an element.
Changelog: Fix html edit initial change
Refs: TOCDEV-336
> fix(tocco-ui): no initial onChange

- packages/app-extensions/src/rest/request.js
- packages/tocco-util/src/saga/abortController.js
- packages/tocco-util/src/saga/index.js
- packages/tocco-util/src/saga/saga.js
if page is refreshed and a request is pending in firefox this results in an unexpected error notifier. if requests are aborted because the page is reloaded no notifier should be shown.
Refs: TOCDEV-3557
Changelog: do not show notifier for aborted fetch
> fix: do not show notifier for aborted fetch

- packages/docs-browser/src/components/Action/actions/Move.js
Refs: TOCDEV-3571
Changelog: Set background color of breadcrumbs inside doc browser to white
> refactor(docs-browser): set embedded property

- packages/admin/src/routes/entities/components/RelationsView/RelationsView.js
Refs: TOCDEV-3570
Changelog: Buttons navigating to create view have been disabled in relation tabs showing Resource
> feat(admin): hide create buttons in Resource relation tabs

- packages/docs-browser/src/components/DocsView/DocsView.js
In commit 9250b83, the `listFormName` variable was introduced on
line 82. However, the variable depends on `keys` which was set later
on line 97. Therefore, `keys` was always undefined, so the form
for specific root nodes `Root_docs_list_item_specific` was never used.
> fix(docs-browser): Fix usage of special list form if root nodes set

- packages/docs-browser/README.md
- packages/docs-browser/src/components/Action/actions/CreateDomain.js
- packages/docs-browser/src/components/Action/actions/CreateFolder.js
- packages/docs-browser/src/components/Action/actions/Edit.js
- packages/docs-browser/src/components/DocsView/DocsView.js
- packages/docs-browser/src/components/DocsView/DocsViewContainer.js
- packages/docs-browser/src/utils/getDetailFormName.js
New props `domainDetailFormName` and `folderDetailFormName` which
work the same way as the already existing `documentDetailFormName`.
-> Can be defined to override the default detail form names
(which are "DmsDomain" and "DmsFolder")
Refs: TOCDEV-3458
> feat(docs-browser): Add input props to define detail form names

- packages/admin/src/routes/entities/components/DocsView/DocsView.js
- packages/admin/src/routes/entities/components/ListView/DocsViewAdapter.js
- packages/docs-browser/README.md
- packages/docs-browser/src/components/DocsBrowser/DocsBrowser.js
- packages/docs-browser/src/components/DocsBrowser/DocsBrowserContainer.js
- packages/docs-browser/src/components/DocsBrowser/StyledComponents.js
Refs: TOCDEV-3571
Changelog: Adjust left padding of Breadcrumbs in list view
> refactor(docs-browser): adjust breadcrumbs padding

- packages/app-extensions/src/actions/components/ReportSettings.js
- packages/app-extensions/src/actions/components/ReportSettings.spec.js
- packages/app-extensions/src/actions/utils/report.js
- packages/app-extensions/src/actions/utils/report.spec.js
- options are ignored by the client
- targetEntity is required for single-selects
Refs: TOCDEV-3637
> fix(app-extensions): fix report action form

- packages/docs-browser/src/components/Action/actions/Move.js
- packages/docs-browser/src/components/Action/actions/MoveContainer.js
- packages/docs-browser/src/main.js
forward domainTypes, rootNodes and businessUnit to docs-browser of move action as this docs-browser should be restricted similarly as the main docs-browser
Refs: TOCDEV-3620
> fix(docs-browser): forward input props to move action

- packages/app-extensions/src/form/FormBuilder.js
- packages/entity-detail/src/components/DetailForm/StyledComponents.js
- packages/tocco-ui/src/Layout/LayoutContainer.js
- packages/tocco-ui/src/Layout/StyledLayoutContainer.js
Refs: TOCDEV-3639
Changelog: Introduce new prop to determine if layout containers should occupy remaining height on screen
(cherry picked from commit 8ec531a9500081460529b6ecf55cbf3841fcec2b)
> refactor(tocco-ui): introduce new height prop

- packages/entity-detail/src/components/DetailForm/SaveButton.js
- if save button was clicked with "hasErros" = false, the rerender of the button
(due to hasErrors prop change) did prevent the submit button click from happening.
This adjustment makes sure, the Button itself does not get rerendered with this
prop change and therefore the click everytime is registrered.
Refs: TOCDEV-3761
> refactor(entity-detail): fix save click

- packages/docs-browser/src/components/Action/actions/Move.js
The `move` action is used for entity documents/folders as well which
cannot be sorted (because their label is generated dynamically in
ContentTreeNode#getLabel()). As sorting might not be the most important
feature in the `move` action, we simply disable it everywhere
(regardless of whether we're moving an entity doc/folder or not)
Refs: TOCDEV-3125
> fix(docs-browser): Disable sorting in `move` action

- packages/app-extensions/src/notifier/modules/modalComponents/StyledComponents.js
- We need to be able to show legacy ExtJS modals on top of our modals
(e.g. legacy action "Edit rights" on Folder/Domain edit form which
is shown in a modal)
- The mask of ExtJS modals has z-index 100, we have to remain below it
Refs: TOCDEV-3647
> fix(app-extensions): Lower modal z-index to make ExtJS modal visible

- scripts/helpers.sh
The bash command which sets the nice version to use for the tag
("2.29.0" -> "229", "3.0.0" -> "30") which was changed in rev
1bc2e29ab5b033640390fc6daa02b19075fed200 apparently doesn't work
on all machines (at least on my machine I get 'invalid option --r').
Using the `sed` command without the `-r` parameter might be a more
stable solution.
> chore: Fix setting correct nice version when releasing

- packages/entity-browser/src/routes/detail/components/EntityDetail/EntityDetail.js
- packages/entity-browser/src/routes/list/containers/ListViewContainer.js
- packages/entity-detail/src/components/SubGrid/SubGrid.js
- packages/entity-detail/src/main.js
due to naming conflicts the same store was loaded for different nice tabs.
With this change i made sure, that every tab gets its own id.
Refs: TOCDEV-3683
Changelog: Fix multi-tab problem
Cherry-pick:Up
> refactor(entity-browser): adjust store ids

- scripts/cherrypick.sh
- scripts/release-package.sh
- scripts/tagging.sh
if multiple auto cherrypicking ci jobs (on different release branches) are executed "git push --tags" fails because an auto-merge tag (of another nice-release) was moved. As the pushed tags with the prefix "_" are deleted by the tagging ci job now the tags are instant locally deleted after the creation.
> chore: scripts do not push temporary release tags

- packages/admin/src/routes/entities/utils/navigationStrategy.js
- otherwise additional parts like '/beta' may be lost
Refs: TOCDEV-3360
Changelog: New tabs opened through navigationStrategy now work with all base urls.
> fix(admin): use history to create url for new tab

- packages/tocco-ui/src/Preview/Preview.js
- packages/tocco-ui/src/Preview/Preview.spec.js
- packages/tocco-ui/src/Preview/Preview.stories.js
- packages/tocco-ui/src/Preview/StyledPreview.js
- simplify preview component and remove unused props
Refs: TOCDEV-2728
Changelog: Add preview for documents
> refactor(tocco-ui): wrap preview image in link

- packages/entity-list/src/components/EntityList/EntityList.js
- packages/entity-list/src/components/EntityList/EntityListContainer.js
- packages/entity-list/src/input.js
- packages/entity-list/src/modules/entityList/actions.js
- packages/entity-list/src/modules/entityList/reducer.js
- packages/entity-list/src/modules/entityList/reducer.spec.js
- packages/entity-list/src/modules/entityList/sagas.js
- packages/entity-list/src/modules/entityList/sagas.spec.js
- store search form collapsed property in store. Otherwise it would be ignored when a store is loaded since the state is only represented in a locale state of a component.
Refs: TOCDEV-3985
> refactor(entity-list): add collapsed bool to store

- packages/tocco-ui/src/Preview/StyledPreview.js
Refs: TOCDEV-3995
Changelog: Prevent preview image collapsing to 1px if preview cannot be generated
> refactor(tocco-ui): fix preview img dimensions

- packages/app-extensions/src/notifier/modules/modalComponents/StyledComponents.js
Refs: TOCDEV-3987
Changelog: Increase z-index of modal holder to properly display as widget
(cherry picked from commit e487fadc53e2c08a6b935001d2a1e14c7815f51b)
> refactor(app-extensions): fix modal holder z-index

- build/webpack.config.js
- with the update of webpack to version 5.x a hidden problem was introduced.
There is a problem with  multiple webpack-compiled files loaded on the same page. Like in nice2.
They would overwrite themself in an internal webpack caching util.
Therefore the library name is needed.
Refs: TOCDEV-3998
> chore: fix build

- .gitlab-ci.yml
Stop misusing the cache for passing build artifacts. For our
runners we use per-host caches. So, one can't assume a cache
from a previous job to be available.
> chore: properly pass artifacts between jobs

- packages/docs-browser/src/components/Action/actions/CreateDomain.js
- packages/docs-browser/src/components/Action/actions/CreateFolder.js
- packages/docs-browser/src/components/Action/actions/Edit.js
- to avoid two messages, the entity-detail success messages are shallowed by the action.
Changelog: Dms edit and create messages clean up
Refs: TOCDEV-4021
Cherry-pick: up
> refactor(docs-browser): shallow detail message

- packages/devcon/README.md
- packages/devcon/src/main.js
Necessary to serve the devcon app under a specific URL (not root path),
e.g. "/devcon". Otherwise the internal routing inside the app does not work.
Refs: TOCDEV-3951
> feat(devcon): Add new input param `baseRoute`

- packages/app-extensions/src/field/editableTypeConfigs/remote.js
- packages/app-extensions/src/formData/FormDataContainer.js
- packages/app-extensions/src/formData/formData.js
- packages/app-extensions/src/formData/remoteCreate/RemoteCreate.js
- packages/app-extensions/src/formData/remoteCreate/RemoteCreateContainer.js
- packages/app-extensions/src/formData/remoteCreate/actions.js
- packages/app-extensions/src/formData/remoteCreate/sagas.js
- packages/app-extensions/src/formData/remoteCreate/sagas.spec.js
- packages/entity-detail/src/main.js
- packages/tocco-ui/src/EditableValue/typeEditors/RemoteSelect.js
- packages/tocco-ui/src/Select/IndicatorsContainer.js
- packages/tocco-ui/src/Select/Select.js
- packages/tocco-ui/src/Select/Select.spec.js
Refs: TOCDEV-3016
Changelog: Add button to remote fields that opens a popup containing a create form
> feat(app-extensions): enable entity creation from remote fields

- packages/app-extensions/src/appFactory/ThemeWrapper.js
- packages/tocco-ui/src/Icon/FontAwesomeAdapter.js
- packages/tocco-ui/src/Icon/mapping.json
- Solid suqare icon is used fo a display expression in task list.
This icon should not be removed otherwise the icon is rendered as missing icon (question mark).
- add global legacy styling
- remove removed angle icons from mapping
Changelog: Fix suqare icon display expressions
Refs: TOCDEV-4101
> refactor(tocco-ui): add display-expression icon

- packages/devcon/src/routes/devcon/components/DevCon/DevCon.js
- packages/devcon/src/routes/devcon/components/DevCon/StyledDevCon.js
"Seamless" navigation enabled by using the `RouterLink` component
instead of the `Link` component (the latter renders a simple `<a>`
Link instead of a RouterLink).
This means, that the Redux store is kept and that we can navigate
around in the DevCon without losing application log or SQL log entries
etc.
Refs: TOCDEV-3951
> fix(devcon): Prevent complete reload of DevCon when changing page

- packages/devcon/src/routes/modelvalidation/modules/sagas.js
Requesting the SQL and changesets with the `selection` (which
is a Set) for some reason works in local dev environment (package
`devcon` started locally in tocco-client repository), but gets
serialized to `{}` when the app is included in the Nice repository,
which leads to an error because a List<String> is expected on the
server side.
We have to convert it to an array to fix the serialization.
Refs: TOCDEV-3951
Changelog: Fix generating SQL and changesets in prod env
> fix(devcon): Fix generating SQL and changesets in prod env

- packages/docs-browser/src/main.js
- packages/entity-list/src/main.js
Fixes an error when a prop changes during initialization phase. In that phase the
store prop has been changed from `undefined` to defined as well which triggers a re-initialization of the entity-list.
In this case the entity-list should not handle this update as store change and should
ignore the passed store. Therefore we distinguish between setting the store after being initalized with another store,
or when setting the store the first time because of an update from another prop.
Changelog: only reload on explicit store updates
Refs: TOCDEV-4465
> fix(entity-list): only reload on explicit store updates

- packages/tocco-ui/src/Menu/StyledComponents.js
Refs: TOCDEV-4479
Changelog: increase z-index of popper menu to prevent it slipping behind modal
> refactor(tocco-ui): fix z-index of popper menu

- packages/admin/src/components/Navigation/Navigation.js
Always set the focus back to the search input after changing the menu tab
so that the user can continue typing direktly.
Changelog: keep focus in search input on switching menu tabs
Refs: TOCDEV-3927
> feat(admin): keep focus in search input on switching menu tabs

- packages/tocco-ui/src/EditableValue/typeEditors/StyledDatePicker.js
- remove native margin from input to have same height
as non-initialized datepickers
Changelog: fix jumping datepicker on Safari
Refs: TOCDEV-4483
> fix(tocco-ui): fix jumping datepicker on Safari

- packages/docs-browser/src/components/Action/actions/CreateDomain.js
- packages/docs-browser/src/components/Action/actions/CreateFolder.js
- packages/docs-browser/src/components/Action/actions/Edit.js
No create form was shown in the folder create form when the user clicked
on the "+" of the remote fields for the mailbox senders and receivers.
The barrier that swallowed some propagated actions in the CreateDomain
and CreateFolder actions was too greedy and swallowed the modal notification
actions that should show the create form for the mailbox sender and receiver
roles.
The barrier should *only* swallow the action that shows the notification
with the title "client.entity-detail.createSuccessfulTitle".
Refs: TOCDEV-4410
Changelog: Show create form for remote fields again in the folder creation form
> fix(docs-browser): Show create form for remote fields again

- packages/tocco-ui/src/TextareaAutosize/TextareaAutosize.js
- packages/tocco-ui/src/TextareaAutosize/TextareaAutosize.spec.js
For better and smoother typing experience in Firefox the autosize does not get triggered on each
key stroke.
Changelog: debounce autosize on textarea
Refs: TOCDEV-4491
> feat(tocco-ui): debounce autosize on textarea

- packages/app-extensions/src/rest/helpers.js
- packages/app-extensions/src/rest/helpers.spec.js
Since TOCDEV-3421, the REST API doesn't return default values for forms
anymore unless requested explicitly (by query param `_display=true`).
Back then, the default values were requested for create forms.
However, we also need them for search forms (e.g. PublicInputEdit_search);
this is fixed now.
Refs: TOCDEV-4461, TOCDEV-3421
Changelog: Default values that are defined in search forms are taken into account again
> fix(app-extension): Load default values for search forms again

- packages/admin/src/modules/navigation/reducer.js
- packages/admin/src/shortcuts.js
Active menu tab is saved when navigating by clicking on the tab buttons. It was not saved when navigating by using
shortcuts.
Changelog: save active menu tab on shortcut navigation
Refs: TOCDEV-4550
> fix(admin): save active menu tab on shortcut navigation

- packages/admin/src/components/Admin/Admin.js
- packages/admin/src/modules/session/sagas.js
- packages/admin/src/modules/session/sagas.spec.js
if the login page is opened adminAllowed is set to false. after a successful login the session request is done to update the property. however during waiting on the server response the "no role message" was always shown. after a login the adminAllowed is set to undefined and the message only shown if adminAllowed is exact false
> fix(admin): don't show "no role message" while waiting on response

- packages/app-extensions/src/field/editableTypeConfigs/remote.js
- packages/app-extensions/src/formData/remoteCreate/actions.js
- packages/app-extensions/src/formData/remoteCreate/sagas.js
- packages/app-extensions/src/formData/remoteCreate/sagas.spec.js
- packages/tocco-ui/src/Select/IndicatorsContainer.js
After a new record was created directly in a remote field via the "+" button,
the new record was set as value.
This was the correct behavior for single-remote-fields. However, it led to
the error that is described in TOCDEV-4546 in multi-remote-fields.
In multi-remote-fields, we have to set an *array* value instead of a single object.
Furthermore, the new object should be *appended* to the entries that are already
set in the field (they shouldn't be overridden completely).
Refs: TOCDEV-4546
Changelog: Fix creating related entities in multi-remote-fields
> fix(app-extension): Set correct value after creation in remote field

- cypress/integration/entitybrowser_spec.js
flatpickr gets lazy initialized on focus for performance
improvements on Safari.
Refs: TOCDEV-4483
> test: fix failing cypress test

- README.md
• https://docs.tocco.ch has been the canonical URL for some time.
• Replace badge as documentation is now built via GitLab CI. Rather
than using the GitLab CI pipeline badge, I decided to go with a
static badge. Using the GitLab CI badge, we'd end up with two
badges labeled "pipeline" which would be more confusing than
helpful.
> chore: update references to documentation

- packages/admin/src/components/MenuTree/MenuTree.js
`name` is not a unique property and that's why React sometimes duplicated the entries in the list or did not remove them properly.
Changelog: fix duplicated search entries
Refs: TOCDEV-4555
> fix(admin): fix duplicated search entries

- packages/app-extensions/src/keyDown/Components/KeyDownWatcher/KeyDownWatcher.js
- packages/app-extensions/src/keyDown/Components/KeyDownWatcher/KeyDownWatcherContainer.js
- packages/app-extensions/src/keyDown/actionEmitter.js
- packages/app-extensions/src/keyDown/actions.js
- packages/app-extensions/src/keyDown/reducer.js
- packages/app-extensions/src/keyDown/sagas.js
- packages/app-extensions/src/keyDown/utils.js
- packages/app-extensions/src/keyDown/utils.spec.js
In Safari some registered shortcuts did print invisible characters
in the menu search field. This resulted in strange menu behaviour.
As soon as there is an registered shortcut the default
behaviour should be prevented.
Changelog: prevent default behaviour on shortcuts
Refs: TOCDEV-4486
> fix(app-extensions): prevent default behaviour on shortcuts

- packages/admin/src/routes/entities/modules/path/sagas.js
- without a relation selected it gets loaded from url or persist store
Refs: TOCDEV-4572
> fix(admin): reset selectedRelation in relationsView on initialization

- packages/tocco-ui/src/Select/IndicatorsContainer.js
- packages/tocco-ui/src/Select/Select.js
- packages/tocco-ui/src/Select/StyledComponents.js
Refs: TOCDEV-4390
Changelog: enable select dropdown indicators to be aligned at bottom of multiselect fields
> refactor(tocco-ui): align dropdown buttons in multiselect field

- packages/admin/src/routes/entities/components/RelationsView/RelationBox.js
- packages/admin/src/routes/entities/components/RelationsView/RelationsView.js
- move initial setting back out into RelationsView
-- no reason for this to happen in each RelationBox
- always reset relation when available relations change
Refs: TOCDEV-4572
> fix(admin): refactor selection of relation in RelationsView

- packages/tocco-ui/src/CodeEditor/AceEditor.js
- passing something other than a string to ACE crashes it
-- our string fields are never null after saving, but on create all fields are initialized with their default or undefined
> fix(tocco-ui): correctly initialize ace editor in create form

- packages/tocco-ui/src/TextareaAutosize/TextareaAutosize.js
- debounce was still firing the same amount of resizes
- throttle only triggers resize once per 500ms
- improve performance issues on Firefox
Changelog: throttle autosize to fix performance issues
Refs: TOCDEV-4491
> fix(tocco-ui): throttle autosize to fix performance issues

- packages/entity-detail/src/components/DetailForm/DetailForm.js
- packages/entity-list/src/components/AdminSearchForm/AdminSearchForm.js
- packages/tocco-util/src/react/index.js
- packages/tocco-util/src/react/useAutofocus.js
- filtering for inputs with type text does not only include our text fields, but pretty much anything that isn't a checkbox
-- this als works for things like selects and remote fields, since the search box is still a html text input
Refs: TOCDEV-4463
Changelog: the first search field in admin search forms now gets automatically focused on opening
> feat(entity-list): focus first search field in admin search form

- packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js
if a downloadable file (e.g. file linked to an output job) is opened in the same tab the beforeunload is triggered which calls abortController.abort() which results in a "broken" tab
Changelog: open downloadable file in new tab to avoid errors
Refs: TOCDEV-4674
> fix(app-extensions): open downloadable file in new tab to avoid errors

- packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/DocumentCompactFormatter.js
- packages/tocco-ui/src/Upload/View.js
if a downloadable file (e.g. file linked to an output job) is opened in the same tab the beforeunload is triggered which calls abortController.abort() which results in a "broken" tab
Changelog: open downloadable file in new tab to avoid errors
Refs: TOCDEV-4674
> fix: open downloadable file in new tab to avoid errors

- packages/login/README.md
- packages/login/src/LoginApp.js
- packages/login/src/PasswordUpdateApp.js
For widget the backend url needs to set via input parameters
since the widget will most probably run on a different domain
than nice2.
Changelog: add dynamic backend-url as input parameter
Refs: TOCDEV-4655
> feat(login): add dynamic backend-url as input parameter

- packages/widget-utils/.npmignore
- packages/widget-utils/.yarnrc
- packages/widget-utils/README.md
- packages/widget-utils/build/webpack.js
- packages/widget-utils/package.json
- packages/widget-utils/src/bootstrap/bootstrapWidgets.js
- packages/widget-utils/src/bootstrap/index.js
- packages/widget-utils/src/bootstrap/utils.js
- packages/widget-utils/src/bootstrap/utils.spec.js
- The new `bootstrap.js` script will be hosted on the Tocco instance
and can be fetched from there by including a script tag in the external
website:
`<script src="https://${customer}.tocco.ch/js/tocco-widget-utils/dist/bootstrap.js"/>`
- The script selects all widget containers in the website and renders
the corresponding React applications
- The React version that is installed on the Tocco instance is used
(same sources are loaded that are used in the apps that run on the
Tocco instance directly)
- By default, the bootstrap JS origin is used as backend URL for the
widgets (could be overriden by adding a `data-backend-url` attribute
to the widget container)
Refs: TOCDEV-4569
> feat(widget-utils): add new package with script to load widgets

- packages/widget-utils/README.md
- packages/widget-utils/src/bootstrap/bootstrapWidgets.js
By default, the package JS file is derived from the widget name
(which is declared in the `data-tocco-widget` attribute).
There are some cases, where the widget and package name do
not match (e.g. because a package exports multiple widgets,
like the `login` package does (provides `login` and
`update-password` widget)). In these cases, the package name
can be declared explicitly now.
Refs: TOCDEV-4569
Changelog: add widget attribute `data-tocco-package`
> feat(widget-utils): add widget attribute `data-tocco-package`

- packages/tocco-ui/src/EditableValue/typeEditors/HtmlEdit.js
- also editbale field should not execute injected js
- already worked for read-only field
- injected js only insertable by REST API
Changelog: do not execute injected JS in html field
Refs: TOCDEV-4626
> fix(tocco-ui): do not execute injected JS in html field

- packages/tocco-util/src/html/sanitizeHtml.js
- packages/tocco-util/src/html/sanitizeHtml.spec.js
Changelog: no styles allowed in rendered HTML
Refs: TOCDEV-4626
> fix(tocco-util): no styles allowed in rendered HTML

- packages/admin/src/components/Navigation/StyledComponents.js
- When user scrolled down, the expand/collapse all were positioned
behind the module menu items (the buttons were still visible, but
not clickable anymore)
- To fix the issue, `z-index` was increased to `1` (now, the
expand/collapse all buttons are on top of the menu items)
- Now in turn the expand/collapse buttons container covered the
menu items, which wasn't good either. To avoid that, the `width`
property was removed, so that the button container doesn't
take up the whole width of the menu items container anymore
(but rather only the space it actually needs). Instead, the `right`
property is used to position it correctly at the right border of
the menu items container.
Refs: TOCDEV-4731
Changelog: clickability fixed of expand/collapse all in module menu
> style(admin): fix clickability of expand/collapse all in module menu

- packages/app-extensions/src/field/editableTypeConfigs/location.js
- packages/app-extensions/src/field/editableTypeConfigs/location.spec.js
The string fields in the location mapping are non nullable. Therefore,
we need to set an empty string instead of `null` if the location object
contains `null` as value for them.
Refs: TOCDEV-4633
Changelog: validation errors fixed for location fields
> fix(app-extensions): fix (strange) validation error in location fields

- packages/widget-utils/src/bootstrap/bootstrapWidgets.js
- packages/widget-utils/src/bootstrap/utils.js
- packages/widget-utils/src/bootstrap/utils.spec.js
Similar to the theme, website builders can define the event
handlers in a map called `customerEventHandlers` on the global
window scope. If this map is defined, it is taken into account
automatically.
Example:
HTML:
`<div data-id="myWidgetId" data-tocco-widget="login"></div>`
JS:
```
window.customerEventHandlers = {
myWidgetId: {
loginSuccess: () => { console.log('login was successful!') }
}
}
```
Refs: TOCDEV-4739
Changelog: add support for ext. event handlers for widgets
> feat(widget-utils): add support for ext. event handlers for widgets

- packages/admin/package.json
- packages/app-extensions/package.json
- packages/copy/package.json
- packages/dashboard/package.json
- packages/delete/package.json
- packages/devcon/package.json
- packages/docs-browser/package.json
- packages/entity-browser/package.json
- packages/entity-detail/package.json
- packages/entity-list/package.json
- packages/input-edit/package.json
- packages/installation-delta-action/package.json
- packages/login/package.json
- packages/merge/package.json
- packages/resource-scheduler/package.json
- packages/scheduler/package.json
- packages/simple-form/package.json
- packages/sso-login/package.json
- packages/tocco-test-util/package.json
- packages/tocco-ui/package.json
- packages/two-factor-connector/package.json
- packages/user-qr-action/package.json
- plop/templates/package/package.json
- lerna (or tocco-*) packages has to be in `devDependencies`
- dependent tocco packages are already bundled inside package
- therefore tocco packages do not have to be installed as normal
dependencies
Changelog: fix tocco-* dependencies
Ref: TOCDEV-4640
> chore: fix tocco-* dependencies

- packages/tocco-ui/src/Select/Select.js
Refs: TOCDEV-4131
Changelog: use throttle for select instead of debounce to prevent flickering of dropdown
> refactor(tocco-ui): use throttle for select

- packages/tocco-ui/src/Select/Select.js
Refs: TOCDEV-4131
Changelog: use throttle for select instead of debounce to prevent flickering of dropdown
> refactor(tocco-ui): use throttle for settle

- packages/app-extensions/src/field/formattedTypeConfigs/document.js
If merge action was opened for 2 users with document fields, the action
crashed because of a null pointer in `getOptions`, because `formData`
is not available in the table (to compare the field values) in the merge
action (was caused by TOCDEV-4474, commit 1e4d02a).
Refs: TOCDEV-4646
Changelog: null pointer fixed in document field formatter (resp. merge action)
> fix(app-extensions): prevent null pointer in document field formatter

- packages/widget-utils/README.md
- packages/widget-utils/src/bootstrap/bootstrapWidgets.js
- packages/widget-utils/src/bootstrap/bootstrapWidgets.spec.js
- packages/widget-utils/src/bootstrap/constants.js
- packages/widget-utils/src/bootstrap/utils.js
- packages/widget-utils/src/bootstrap/utils.spec.js
- rename `customerEventHandlers` to `toccoEventHandlers`
- rename `customerTheme` to `toccoTheme`
- add theme handling to script
Changelog: prefix global objects with `tocco`
Refs: TOCDEV-4749
> refactor(widget-utils): prefix global objects with `tocco`

- babel.config.js
- styled-components babel plugin
removed css after page transition
- do not minify to have all css applied properly
Refs: TOCDEV-388, TOCDEV-4758
Changelog: do not remove css after page transition
> fix: do not remove css after page transition

- packages/tocco-util/src/html/sanitizeHtml.js
- packages/tocco-util/src/html/sanitizeHtml.spec.js
- css can be dangerous and were not allowed
- however some inline css is used for nice tooltips
- to still support those a defined set of inline css is valid
Changelog: allow whitelisted inline css for nice tooltips
Refs: TOCDEV-4767
> fix(tocco-util): allow whitelisted inline css for nice tooltips

- packages/widget-utils/src/bootstrap/bootstrapWidgets.js
- packages/widget-utils/src/bootstrap/bootstrapWidgets.spec.js
- packages/widget-utils/src/bootstrap/constants.js
- packages/widget-utils/src/bootstrap/index.js
- packages/widget-utils/src/bootstrap/utils.js
- it can happen that the bootstrap script gets added multiple
times on a page
- the widgets should get initialized only once to
prevent issues and strange behaviours
Changelog: run bootstrap script only once
Refs: TOCDEV-4804
> feat(widget-utils): run bootstrap script only once

- packages/tocco-ui/src/FormattedValue/typeFormatters/DurationFormatter.js
- packages/tocco-ui/src/FormattedValue/typeFormatters/DurationFormatter.spec.js
Refs: TOCDEV-4762
Changelog: Display durations as hh:mm:ss consistently instead of like a timestamp
> fix(tocco-ui): fix display of durations

- packages/entity-list/src/components/BasicSearchForm/BasicSearchForm.js
As soon as entity-list with search form is rendered
the focus should be moved to form input.
Has effect on:
- advanced remote search
- entity-browser widget
Changelog: auto focus basic search form
Refs: TOCDEV-4735
> feat(entity-list): auto focus basic search form

- packages/tocco-ui/src/Select/IndicatorsContainer.js
Refs: TOCDEV-4912
Changelog: Using the advanced search in multi-remote fields no longer ignores the current selection.
> fix(tocco-ui): use correct value for advanced search

- packages/tocco-ui/src/AdminLink/StyledLink.js
- `netural` prop is passed further down to react-router link
- the link component passes all props to the html tag underneath
- React expect string value instead of bool and prints error
- `neutral` should not be treated as html attribute in this case
- never forward `neutral` prop on AdminLink to html tag
> fix(tocco-ui): fix react attribute error

- .gitlab-ci.yml
- cypress.io dashboard is only free for a few test runs
- but we would like to run tests more frequently
- we already publish the video artifacts on gitlab
- no need to publish test runs on cypress.io dashboard anymore
> chore: stop recording runs on cypress.io dashboard

- .gitlab-ci.yml
- cypress.io only allows to run tests in parallel when record is active
- remove parallelization for now
- use correct binary version to not have a warning/conflicts
> chore: fix cypress run without recording

- .gitlab-ci.yml
These artifacts are only used to move data between jobs within
the same pipeline. There should be no need to keep them long-term.
> chore: CI: define expiry time for artifacts

- packages/docs-browser/src/components/Action/actions/CreateDomain.js
- packages/docs-browser/src/components/Action/actions/CreateFolder.js
- packages/docs-browser/src/components/Action/actions/Edit.js
- packages/docs-browser/src/components/Action/actions/Move.js
- packages/docs-browser/src/components/Action/actions/MoveContainer.js
- packages/docs-browser/src/components/DocsView/DocsView.js
- packages/docs-browser/src/components/DocsView/DocsViewContainer.js
- packages/docs-browser/src/components/DocumentView/DocumentView.js
- packages/docs-browser/src/components/DocumentView/DocumentViewContainer.js
Needed if the docs-browser is rendered as standalone widget in a website.
Refs: TOCDEV-4817
Changelog: support `locale` input
> feat(docs-browser): support `locale` input

- packages/docs-browser/src/modules/chooseDocument/StyledComponents.js
- packages/docs-browser/src/modules/chooseDocument/sagas.js
Refs: TCODEV-4547
Changelog: align choose document button to the right
> refactor(docs-browser): align choose document button

- packages/tocco-util/src/cache/cache.js
- packages/tocco-util/src/originId/originId.js
- origin id was originally stored in session storage
- since session storage was completely cleared
origin id was cleared as well
- websocket call and client-id header on rest requests were out of sync
- clearing cache should only consider cache keys
instead of whole session storage
- keeping origin id in session storage will hydrate notifications
instead of creating a new session
Refs: TOCDEV-4729
Changelog: fix cache clearance to keep notifications session
> fix(tocco-util): fix cache clearance to keep notifications session

- .gitlab-ci.yml
- husky requires npm exec to be existent
- use v16 node on gitlab as well
> chore: update node on gitlab

- packages/tocco-ui/src/FormattedValue/typeFormatters/MultiSelectFormatter.js
- do not prevent default, that is exactly what we do want
- same behaviour is already used in SingleSelectFormatter
Refs: TOCDEV-4991
Changelog: Navigating to detail pages through links in multi-select fields is now possible.
> fix(tocco-ui): enable navigating to multi-select details

- packages/admin/src/routes/entities/components/Action/actions/ResourceScheduler.js
Refs: TOCDEV-4999
Changelog: ResourceScheduler now always open the root entities route when clicking on events.
> fix(admin): always open root entity route from ResourceScheduler

- packages/tocco-util/src/date/utils.js
- packages/tocco-util/src/date/utils.spec.js
- parseInt has strange results when passing in tiny values (like 1/3600000)
Refs: TOCDEV-4986
Changelog: Tiny millisecond values (1 - 3) are now displayed correctly.
> fix(tocco-util): display tiny millisecond values correctly

- packages/tocco-ui/src/EditableValue/typeEditorFactory.js
- previous workaround must have stopped working sometime in the past, blurValue was always empty
Refs: TOCDEV-5036
Changelog: onBlur of date component is called with value from onChange again
> fix(tocco-ui): use useRef for date onBlur workaround

- packages/tocco-ui/src/CodeEditor/AceEditor.js
- previously we used 'value' as boolean directly, but this got removed when we needed to clear fields
- an empty string is a valid value, but null / undefined is not
Refs: TOCDEV-5103
Changelog: ace editor works again in create forms
> fix(tocco-ui): don't try to set null value in ace editor

- packages/docs-browser/src/components/DocsView/DocsView.js
Refs: TOCDEV-5119
Changelog: fix docs browser back navigation for search view
> fix(docs-browser): navigate back to search view

- packages/core/app-extensions/src/field/editableTypeConfigs/booleanSelect.js
- packages/core/app-extensions/src/field/editableTypeConfigs/booleanSelect.spec.js
- packages/core/app-extensions/src/field/editableTypeConfigs/location.js
- packages/core/app-extensions/src/formField/formField.js
- see only exactly true and false as values
- move hasValue handling to single spot and also pass value to the overwrite
Refs: TOCDEV-2442
> fix(app-extensions): customize hasValue for booleanSelect

- packages/core/tocco-ui/src/CodeEditor/TqlAutoCompleter.js
- packages/core/tocco-ui/src/CodeEditor/TqlAutoCompleter.spec.js
Refs: TOCDEV-4800
Changelog: tql autocompletion now displays localized labels in suggestions
> feat(tocco-ui): add labels to tql autocompletion

- packages/core/scheduler/src/components/FullCalendar/FullCalendar.js
- month view is too wide on small screens
- omit redundant value on each slot to have more space
Refs: TOCDEV-4917
Changelog: omit month in slot label for month view
> feat(scheduler): omit month in slot label for month view

- packages/app-extensions/src/notification/components/NotificationBody/NotificationBody.js
Changelog: do not reuse same tab for different reports
Refs: TOCDEV-5251
> fix(app-extensions): do not reuse same tab for different reports

- .gitlab-ci.yml
I think this options were all just added for debugging during
the migration from Travis to GitLab CI (e9abf0a844c8b6). From
the documentation:
--detectOpenHandles
Attempt to collect and print open handles preventing Jest from
exiting cleanly. Use this in cases where you need to use
--forceExit in order for Jest to exit to potentially track down
the reason. This implies --runInBand, making tests run serially.
Implemented using async_hooks. This option has a significant
performance penalty and should only be used for debugging.
--forceExit
Force Jest to exit after all tests have completed running. This
is useful when resources set up by test code cannot be adequately
cleaned up. Note: This feature is an escape-hatch. If Jest doesn't
exit at the end of a test run, it means external resources …
> chore: run tests in parallel / disable debugging features

- packages/app-extensions/src/notifier/modules/modalComponents/StyledComponents.js
- need to stay above load mask in old client
- behaviour is not present in 3.0, so no cherry-pick is necessary
Refs: BS-6936
> fix(app-extensions): increase z-index for modals

- packages/core/scheduler/src/components/FullCalendar/FullCalendar.js
Refs: TOCDEV-4139
Changelog: calendar is now always sorted by calendar type and title
> feat(scheduler): set sorting in calendar instead of the backend

- packages/apps/admin/src/routes/entities/components/DocsView/DocsView.js
- packages/apps/admin/src/routes/entities/components/ListView/DocsViewAdapter.js
- packages/apps/admin/src/routes/entities/components/ListView/ListView.js
Since TOCDEV-5060 and commit c49a167 navigating to a entity document
via the hash URL didn't work anymore, as the hash URL was ignored since
then ("routerless" docs-browser instance is used, as routers cannot be
nested anymore).
To fix navigating to the document, the hash URL is passed as
`initialLocation` to the <DocsBrowser> now.
Refs: TOCDEV-5343, TOCDEV-5060
Changelog: fixed navigating to entity document
> fix(admin): fix navigating to entity document

- packages/admin/src/modules/session/sagas.js
- packages/app-extensions/src/appFactory/App.js
- packages/app-extensions/src/appFactory/appFactory.js
- packages/app-extensions/src/cache/CacheInitLoadMask/CacheInitLoadMask.js
- packages/app-extensions/src/cache/CacheInitLoadMask/CacheInitLoadMaskContainer.js
- packages/app-extensions/src/cache/CacheInitLoadMask/index.js
- packages/app-extensions/src/cache/actions.js
- packages/app-extensions/src/cache/cache.js
- packages/app-extensions/src/cache/index.js
- packages/app-extensions/src/cache/reducer.js
- packages/app-extensions/src/cache/reducer.spec.js
- packages/app-extensions/src/cache/sagas.js
- packages/app-extensions/src/cache/sagas.spec.js
- packages/app-extensions/src/cache/utils.js
- packages/app-extensions/src/cache/utils.spec.js
- packages/app-extensions/src/intl/intl.js
- packages/app-extensions/src/intl/intl.spec.js
- packages/app-extensions/src/login/sagas.js
- packages/app-extensions/src/login/sagas.spec.js
- packages/app-extensions/src/rest/helpers.js
- packages/app-extensions/src/rest/helpers.spec.js
- packages/login/src/modules/sagas.js
- packages/login/src/modules/sagas.spec.js
- packages/sso-login/src/modules/sagas.js
- packages/sso-login/src/modules/sagas.spec.js
On login via support-tocco or when logged in on different tab
the success login sagas do not get executed. Without the sagas the
caches did not get invalidated properly.
On every page refresh the cache invalidates itself whenever
a cache-relevant data has been changed (locale, user, bu, ...).
Changelog: invalidate cache on page refresh properly
Refs: TOCDEV-5317
> fix(app-extensions): invalidate cache on page refresh properly

- .github/workflows/auto_pr.yml
Auto PR github action started to fail suddendly.
Seems to be a general problem:
https://github.com/repo-sync/pull-request/issues/84
> chore: fix auto pr github action

- packages/core/tocco-ui/src/Select/Select.js
Refs: TOCDEV-5206
Changelog: correct dimension calculation of select menu since in some situations it does not seem to calculate the correct width/height
> refactor(tocco-ui): correct dimension calculation

- plop/generators/package.js
- plop/templates/package/changelog.md
The release pipeline will break when a package gets
released and the changelog.md does not exist
> chore: add changelog to package template

- packages/entity-list/src/components/AdminSearchForm/QueryView.js
- packages/entity-list/src/components/AdminSearchForm/StyedComponents.js
Error message for TQL are already preformatted
in regards of line breaks and spacing. Using the same
format helps the user to find the error way faster.
Refs: TOCDEV-5040
Changelog: use preformatted error message for tql
> fix(entity-list): use preformatted error message for tql

- packages/app-extensions/src/field/editableTypeConfigs/duration.js
- packages/tocco-ui/src/EditableValue/typeEditors/DurationEdit.js
- packages/tocco-ui/src/EditableValue/typeEditors/DurationEdit.spec.js
- packages/tocco-ui/src/EditableValue/utils.js
- `options.allowNegative` will be set to true, if there is no number
range validation or if `fromIncluding` is less than 0
- if negative values are allowed, the minus sign "-" will be displayed
in the biggest unit that's not 0 (so, in the minutes field, if there are
no hours, and in the hours field, if there are hours)
- other improvements:
-- hours can be greater than 24 now
-- fixed automatic growing (unit "px" was missing in styling rule) and
added a padding of 5px
-- removed automatic rewriting of minutes to 0 or to 59 in certain
conditions as it was rather irritating than helpful
- needs to be cherry picked to newer branches by hand, as there
will be some merge conflicts
Changelog: allow duration values to be negative
Refs: TOCDEV-5338
> feat(tocco-ui): allow duration values to be negative

- packages/admin/src/modules/session/sagas.js
- packages/admin/src/modules/session/sagas.spec.js
The session heartbeat is setup after login but will not be setup again
on a page refresh with having still a valid session.
The nice2 session timeout is set to 30 minutes but the
frontend assumed to have a session timeout of 10s.
After 22min the session heartbeat is executed, but only
when tab hasn't been refreshed after login.
The admin got completely umounted and mounted on every heartbeat.
This caused unsaved changes to be lossed completely.
To not show "no-roles" error messages right after login but
before the session has beend fetched, the `adminAllowed` variable
has to be reset after login.
This prevents to render the admin with a value of `false` and showing
the error message for a short time.
Refs: TOCDEV-5100
Changlog: do not re-initalize admin on session heartbeat
Cherry-pick: …
> fix(admin): do not re-initialize admin on session heartbeat

- packages/tocco-ui/src/EditableValue/typeEditorFactory.js
- selecting values in advanced search does not trigger
onChange event
- therefore the value used for onBlur did not contain
the previous selected values and removed them
Refs: TOCDEV-5352
Changelog: keep all values on blur
> fix(tocco-ui): keep all values on blur

- packages/core/tocco-ui/src/EditableValue/typeEditorFactory.js
- needed to be able to set date manually and save
directly without clicking outside first
- with flatpickr dependency upgrade this workaround is
not needed anymore
Refs: TOCDEV-5352, TOCDEV-5036
> refactor(tocco-ui): remove unused flatpickr workaround

- packages/tocco-util/src/react/Debouncer.js
- packages/tocco-util/src/react/Debouncer.spec.js
- packages/tocco-util/src/react/useDebounce.js
- packages/tocco-util/src/react/useDebounce.spec.js
- somehow the search form did switch to `undefined` value shortly
before settings the correct search value right again
- the debounce component only accepted changed from outside every 200ms
- now the debounce component accpets all changes from outside right away
because the `debouncedValue` gets reset
Refs: TOCDEV-5350
Changelog: debouncer accepts value changes from outside
> fix(tocco-util): debouncer accepts value changes from outside

- packages/tocco-ui/src/EditableValue/typeEditors/DurationEdit.js
- packages/tocco-ui/src/EditableValue/typeEditors/StyledDurationEdit.js
- The value should be set as string, otherwise it's not updated for some
reason (e.g. if the current value is 1 hr and 0 min and you append "1"
in the minutes field, the value remains "01" if the value is given as
a number and it changes to "1" (desired) if the value is given as
string
- Also fixed the automatic growing of the fields as the user types. The
`useEffect` hook was never called, so it didn't work at all. Handling
those field widths in the state and width the additional shadow fields
is sort of complicated overkill (which didn't even work), just giving
every character a specific width (9 px for now) and deriving the field
width from the number of characters should be good enough for this
case (and more stable).
Refs: TOCDEV-5338
Cerry-pick: Up
Changelog: update of the values …
> fix(tocco-ui): fix update of the values and field widths in duration

- packages/core/app-extensions/src/form/reduxForm.js
- packages/core/app-extensions/src/form/reduxForm.spec.js
- packages/core/tocco-util/src/api/entities.js
- packages/core/tocco-util/src/api/entities.spec.js
- Selectors (relAddress[publication]) has not been fully supported yet
- apply workaround for redux form to handle [,] in field names
- fix entity mapping for not nesting names containing [,]
Refs: TOCDEV-5365
Changelog: support selectors in forms
> feat(app-extensions,tocco-util): support selectors in forms

- packages/core/tocco-ui/src/FormattedValue/typeFormatters/PhoneFormatter.js
- 3CX Click2Call chrome plugin was interacting with the html node
of the phone number.
- React Suspense componentent wasn't able to render
lazy loaded `LibPhoneFormatter` anymore.
- Therefore render phone number only once.
Refs: TOCDEV-5427
Changelog: support browser plugins for phone numbers
> fix(tocco-ui): support browser plugins for phone numbers

- packages/tocco-ui/src/EditableValue/typeEditorFactory.js
- packages/tocco-util/src/react/Debouncer.js
- inline functions would always technically be different on re-renders and triggered dependencies in Debouncer
Refs: TOCDEV-5412
Changelog: fix too many field callbacks being called
> fix(tocco-ui): fix too many debounced callbacks being called

- packages/core/tocco-ui/src/Select/Menu.js
- packages/core/tocco-ui/src/Select/StyledComponents.js
Refs: TOCDEV-5424
Changelog: fixate menu on multiremote select fields at bottom to improve ux
(cherry picked from commit 86e34f01bfebf7427ab07c74c1cf67228dc86a94)
> refactor(tocco-ui): fixate menu at bottom

- packages/app-extensions/src/actions/components/ReportSettings.js
- settingsRef was not updated when `setSettings` has
been called right after each other (withour render in between)
- using `setState` as function to be able to access latest state
should be the safest option
Refs: TOCDEV-5423
Changelog: fix state handling for report settings
> fix(app-extensions): fix state handlig for report settings

- packages/core/app-extensions/src/form/reduxForm.js
- packages/core/app-extensions/src/form/reduxForm.spec.js
- would not notice that previous parts in path need to be included
- this would lead to a request that created a new entity along the path instead of updating
Refs: TOCDEV-5451
> fix(app-extensions): check correctly for included key in paths

- packages/tocco-ui/src/Breadcrumbs/BreadcrumbSeparator.js
- packages/tocco-ui/src/Breadcrumbs/Breadcrumbs.js
- packages/tocco-ui/src/Breadcrumbs/StyledBreadcrumbs.js
Changelog: render html escape characters in breadcrumbs
Refs: TOCDEV-5492
> fix(tocco-ui): render html escape characters in breadcrumbs

- packages/widgets/address-update/package.json
- packages/widgets/wage-view/package.json
- we use `widget-bundle` as package for now
- can be set back to public anytime
Refs: TOCDEV-5379
> chore: do not publish new widget packages

- packages/tocco-ui/src/EditableValue/typeEditors/NumberEdit.js
Changelog: show from and to placeholders on number ranges
Refs: TOCDEV-5189, TOCDEV-5511
> feat(tocco-ui): show from and to placeholders on number ranges

- packages/tocco-ui/src/Table/selection/useSelection.js
- table without selection feature passed undefined selection as prop
- useSelection default value triggered infinite re-render loop
Refs: TOCDEV-5453
> fix(tocco-ui): prevent infinite re-render loop on table

- packages/tocco-ui/src/Breadcrumbs/Breadcrumbs.js
Refs: TOCDEV-5561
Changelog: reverse title order to first display entity name and then default display
> refactor(tocco-ui): reverse title tag

- packages/widget-utils/package.json
widgets are currently only developed in the master so we won't bugfix anything
> chore: set widget packages to private

- packages/core/tocco-ui/src/ColumnPicker/ColumnPicker.js
- packages/core/tocco-ui/src/ColumnPicker/StyledColumnPicker.js
Refs: TOCDEV-5534
Changelog: add initial sorting to column-picker and fix long list entries wrapping
> refactor(toccu-ui): add initial sorting

- packages/core/entity-detail/src/main.js
- the entity-detail did not listen to input param changes
- once rendered the detail could not re-render for any other form
- when using the subtable inside a detail the navigation to other details
did not work properly
- it worked by accident when the target entity name had to be fetched
- this is causing a complete unmount and remount of the entity-detail
- therefore the problem only occured on the back button so far
Changelog: listen to input param changes
Refs: TOCDEV-5677
> fix(entity-detail): listen to input param changes

- packages/entity-list/src/modules/list/sagas.js
- packages/entity-list/src/modules/list/sagas.spec.js
with the commit 555e5b9c8c472cd761e434565af212b88cb02f8d (TOCDEV-5604) the formDefinition passed via input properties there correcly handled. however the dms was now broken as the if condition only checks if the form was already loaded and not of the correct form definition exists (the dms has different forms such as Root_docs_list_item_list and Docs_list_item_list)
Changelog: fix loading form definition for dms
Refs: TOCDEV-5009
> fix(entity-list): fix loading form definition for dms

- packages/core/tocco-util/src/tqlBuilder/utils.js
- packages/core/tocco-util/src/tqlBuilder/utils.spec.js
Refs: TOCDEV-5625
Changelog: fix datetime in searchforms after using date-fns
> fix(tocco-util): fix datetime in searchforms after using date-fns

- packages/core/tocco-ui/src/ColumnPicker/ColumnPicker.js
Refs: TOCDEV-5665
Changelog: column labels in ColumnPicker no longer display escaped html elements
> feat(tocco-ui): interpret html in ColumnPicker labels

- packages/core/entity-list/src/components/AdminSearchForm/SearchView.js
- packages/core/entity-list/src/components/BasicSearchForm/BasicSearchForm.js
- packages/core/tocco-util/src/react/useAutofocus.js
Refs: TOCDEV-5502
Changelog: fulltext search fields are now prioritized to be autofocused
> feat(tocco-util): useAutofocus can prioritize fulltext search fields

- packages/apps/admin/src/routes/entities/components/DocsView/DocsView.js
- packages/apps/admin/src/routes/entities/components/RelationsView/DocsViewAdapter.js
- packages/apps/admin/src/routes/entities/components/RelationsView/RelationsView.js
Refs: TOCDEV-5429
Changelog: entity docs can now be sorted
> feat(admin): make entity docs sortable

- packages/core/tocco-ui/src/EditableValue/editors/DateEdit.js
- packages/core/tocco-ui/src/EditableValue/editors/DatePicker.js
- packages/core/tocco-ui/src/EditableValue/editors/DatePicker.spec.js
- packages/core/tocco-ui/src/EditableValue/editors/DateTimeEdit.js
- packages/core/tocco-util/src/date/index.js
- packages/core/tocco-util/src/date/utils.js
- packages/core/tocco-util/src/date/utils.spec.js
Refs: TOCDEV-5679
Changelog: allow date inputs without punctuation
> feat(tocco-ui): allow date inputs without punctuation

- packages/app-extensions/src/formData/relationEntities/sagas.js
- packages/app-extensions/src/formData/relationEntities/sagas.spec.js
Refs: TOCDEV-5753
Changelog: remotefields now sort the same way in select box and advanced search (form sorting first, then last updated)
> feat(app-extensions): add default sorting to remotefields

- packages/widgets/docs-browser/src/components/DocsView/DocsView.js
- external event `onRowClick` is only attached inititally
- `handleRowClick` is dependent on props that will change over time
- e.g. searchMode or path
- to be able to access latest value we need to use refs
Refs: TOCDEV-5350
Changelog: fix navigation to subfolder inside search results
> fix(docs-browser): fix navigation to subfolder inside search results

- scripts/helpers.sh
currently only dependencies in the package.json be taken into account for the changelog generation. Finding the dependencies improved that transitive dependencies are now also considered
Refs: TOCDEV-5746
> chore: fix changelog generation

- packages/admin/src/routes/entities/components/RelationsView/ListView.js
- same relation can be rendered on different navigation levels
- e.g. Veranstaltung - Verrechnungsposition
and Veranstaltung - Anmeldung  - Verrechnungsposition
- when navigating between the details the relations tab did not update itself correclty
- saved store need to be aware of parent
- therefore prefix store key with parent to not reuse wron store from upper relation
Changelog: load correct store for relations view
Refs: TOCDEV-5682
> fix(admin): load correct store for relations view

- .gitlab-ci.yml
- package.json
- scripts/nice2/helpers.sh
- scripts/widgets/server.js
- scripts/widgets/wait-for-readyness.sh
- replace removed CYPRESS_BACKEND_URL with BACKEND_URL
- ensure widget-server is ready before starting cypress on gitlab
> chore: fix widget-server setup in cypress

- packages/core/tocco-ui/src/StatedValue/StyledStatedValue.js
Refs: TOCDEV-5734
Changelog: fix input label being cut in widgets
> refactor(tocco-ui): fix label being cut

- packages/core/tocco-ui/src/Panel/Panel.js
- packages/core/tocco-ui/src/Panel/StyledPanelHeaderFooter.js
Refs: TOCDEV-5866
Changelog: show collapse/expand icon on touch devices in panel header/footer
> refactor(tocco-ui): show collapse icon on mobile

- packages/core/tocco-ui/src/EditableValue/EditorProvider.js
Refs: TOCDEV-5881, TOCDEV-5926
Changelog: quick fix that onChange is not infinite often triggered
> fix(tocco-ui): quick fix that onChange is not infinite often triggered

- packages/actions/subscribe-calendar/src/modules/subscribeCalendar/sagas.js
- packages/actions/subscribe-calendar/src/modules/subscribeCalendar/sagas.spec.js
Refs: TOCDEV-5849
Changelog: use more generic error message when no Calendar_export_conf could be found
> feat(subscribe-calendar): use more generic error message

- packages/core/app-extensions/src/field/editableValueFactory.js
- packages/core/app-extensions/src/field/editableValueFactory.spec.js
- packages/core/tocco-ui/src/Range/Range.js
- packages/core/tocco-ui/src/Range/Range.spec.js
- New `expanded` prop to display the range field initially expanded
with a *single* value (before, the expanded mode was only used if
the value was a range value)
- If a single value is given and expanded mode required, the single
value will be used as `from` value. This is the same behavior as
in the legacy client (as of today there is no actual use case
where we're required to set a `to` value instead of the `from`)
- Example where this is useful: there are a few widgets with a date
range field in the search form to show records with a date field
with values starting from today
Refs: TOCDEV-5497
Changelog: default values in initially expanded Range fields handled correctly
> fix: handle default values in expanded Range fields correctly

- scripts/helpers.sh
in version 3.1 and earlier the path to the package is different
Refs: TOCDEV-5746
>  chore: fix changelog generation

- packages/widgets/sso-login/src/components/LoginBox/LoginBox.js
On initial render, the `providers` prop might be undefined. We need to check for that.
Refs: TOCDEV-6006
Changelog: fix null pointer in login box
> fix(sso-login): fix null pointer in login box

- packages/core/tocco-util/src/react/useAutofocus.js
Refs: TOCDEV-5923
Changelog: ignore any text and textarea fields of a datepicker when autofocusing
> fix(tocco-util): do not autofocus date fields

- packages/core/entity-list/src/main.js
- changedProps.store is undefined when store has not changed
- nevertheless it could be that store is defined on props
- to figure out if store has been removed from props it's needed to check if store is set on props and not on changedProps
Refs: TOCDEV-5912
Changelog: do not refresh list multiple times
> fix(entity-list): do not refresh list multiple times

- packages/core/entity-list/src/components/EntityList/EntityListContainer.js
- packages/core/entity-list/src/input.js
- packages/core/entity-list/src/modules/entityList/actions.js
- packages/core/entity-list/src/modules/entityList/reducer.js
- packages/core/entity-list/src/modules/searchForm/sagas.js
- packages/core/entity-list/src/modules/searchForm/sagas.spec.js
- searchFormType is set from `simple_advanced` to `fulltext` when no form definition exists
- this was only executed initially
- also re-initalize searchFormType whenever is has been change from outside
Refs: TOCDEV-5891
Changelog: show correct search form in subgrid
> fix(entity-list): show correct search form in subgrid

- packages/core/app-extensions/src/rest/helpers.js
- packages/core/app-extensions/src/rest/helpers.spec.js
Caution: depends on https://git.tocco.ch/c/nice2/+/45699 (new POST REST
endpoint must be merged first)
Details:
- When fetching an entity, the field and relation values needed to be specified in the `_paths` query param
- If there are many paths to request, the URL can become very long (longer than 2000 characters which is the de facto limit for the URL length) which causes requests to fail (see TOCDEV-6081).
- To get around the problem, the entity can be fetched via POST request now (send `paths` array in body instead of comma separated `_paths` query param) -> this is also the new default
- If you still want to use GET as the method, you can specify it in the request options for `rest.fetchEntity`
Refs: TOCDEV-6081
Changelog: change HTTP method of `rest.fetchEntity` to POST
Cherry-pick: …
> feat(app-extension): change HTTP method of `rest.fetchEntity` to POST

- packages/core/simple-form/src/containers/FormContainer.js
- form values were not passed in to form component
- without form values no default values have been loaded
Refs: TOCDEV-6087
Changelog: load defalut values on action forms
> fix(simple-form): load default values on action forms

- packages/core/tocco-ui/src/DatePicker/GlobalDatePickerStyles.js
- packages/core/tocco-ui/src/EditableValue/editors/DatePicker.js
- packages/core/tocco-ui/src/EditableValue/editors/DatePicker.spec.js
- packages/core/tocco-ui/src/EditableValue/editors/StyledTimeEdit.js
- packages/core/tocco-ui/src/EditableValue/editors/TimeEdit.js
- packages/core/tocco-ui/src/EditableValue/editors/useTimeEdit.js
- packages/core/tocco-ui/src/EditableValue/editors/useTimeEdit.spec.js
- always 24h format, independent of browser settings
- easy to type time
- no double clear-button in ffox
Refs: TOCDEV-5949, TOCDEV-5958
Changelog: time input component
> feat(tocco-ui): time input component

- packages/core/tocco-util/src/tqlBuilder/tqlBuilder.js
- packages/core/tocco-util/src/tqlBuilder/tqlBuilder.spec.js
just using one fulltext keyword instead of two has a better performance. in the old client the search term "term1 term2 term3" is converted to the TQL "term1 term2 (term3 OR term3*)" which is the equivalent of the TQL  "(term1 term2 term3) OR (term1 term2 term3*)" now implemented in the new client.
Refs: TOCDEV-6080
Changelog: fix performance of fulltext search
> fix(tocco-util): fix performance of fulltext search

- packages/widgets/sso-login/src/utils/loginWindow.js
- nice_auth cookie should be applied on the customers extranet domain
- the backend does not know this domain
- therefore the widget passes the redirectUri as query parameter with the correct domain
Refs: TOCDEV-6061
Changelog: pass redirectUri for sso logins in widgets
> feat(sso-login): pass redirectUri for sso in widgets

- packages/app-extensions/src/notifier/modules/modalComponents/StyledComponents.js
- packages/tocco-ui/src/Select/Menu.js
the fix for issue BS-7483 broken BS-6936 again, so the change is reverted. The issue of BS-6936 and BS-8043 is now fixed. BS-7483 was now fixed by changing the z-index of the select dropdown (and not the modal)
Refs: BS-6936, BS-7483, BS-8043
Changelog: increase z-index for selects in modals
Cherry-pick: No
> fix(app-extensions, tocco-ui): increase z-index for selects in modals

- packages/actions/widget-code-copy/src/utils/widgetCode.js
- packages/actions/widget-code-copy/src/utils/widgetCode.spec.js
- having an extranet with tocco subdomain for cookie authentication will not be the main usecase anymore
- instead the cms (mainly wordpress) will have a tocco-proxy (via a plugin) and the widgets will communicate via this proxy to nice2 backend
- therefore tocco subdomain does not exist and asset url has to be tocco backend url directly
Changelog: remove tocco subdomain
> fix(widget-code-copy): remove tocco subdomain

- packages/core/entity-list/src/util/StyledComponents.js
- action wrapper took full cell width
- therefore no space left for row-click event handler
Refs: TOCDEV-6190
Changelog: be able to click on row in action cell
> fix(entity-list): be able to click on row in action cell

- packages/core/app-extensions/src/notification/modules/toaster/ToasterDisplay/StyledComponents.js
Refs: TOCDEV-5874
Changelog: move toasters on mobile to bottom for better ux as most of the interaction elements (e.g actions) are on top and should not be covered
> refactor(app-extensions): move toaster to bottom on mobile

- packages/core/tocco-ui/src/Sidepanel/SidepanelContext.js
- sidepanel collapse on mobile automatically
- do not collapse (hide) sidepanel when positioned on top
Changelog: do not collapse sidepanel on top
Refs: TOCDEV-5985
> fix(tocco-ui): do not collapse sidepanel on top

- packages/core/tocco-ui/src/Ball/StyledBall.js
Refs: TOCDEV-6196
Changelog: reintroduce min-width for Ball component, since normal width caused rendering issues in the main menu
> refactor(tocco-ui): reintroduce min-width

- packages/widgets/entity-browser/src/main.js
Refs: TOCDEV-6197
Changelog: remove div wrapper of entity-browser as it was preventing it from filling the full available height when embedded in the old client
> refactor(widgets): remove div wrapper

- packages/core/app-extensions/src/actions/modules/actionHandlers/report.js
- packages/core/tocco-util/src/mockData/reports.js
- packages/core/tocco-util/src/mockData/reports.spec.js
Refs: TOCDEV-6247
Changelog: send selection to adjusted POST endpoint when loading report settings
> feat(app-extensions): use selection when loading report settings

- packages/core/app-extensions/src/formData/tooltips/sagas.js
- packages/core/app-extensions/src/rest/helpers.js
- packages/core/app-extensions/src/rest/helpers.spec.js
- ignore fallback when loading tooltips
Refs: TOCDEV-5562
Changelog: do not use default display for tooltips again
> feat(app-extensions): allow displays to be loaded without fallback

- packages/core/tocco-util/src/html/sanitizeHtml.js
- packages/core/tocco-util/src/html/sanitizeHtml.spec.js
- links in freemarker can have target attributes which whould be kept
Refs: TOCDEV-5169
Changelog: allow target attribute in html
> fix(tocco-util): allow target attribute in html

- packages/core/scheduler/src/components/FullCalendar/FullCalendar.js
While the start date is inclusive, the end date is exclusive (https://fullcalendar.io/docs/event-parsing). If the same timestamp is passed for start and end of the event, the eventInfo.event.end of the eventContent method is null. Use the start date as fallback if the end date is null
Changelog: fix null as end date
Refs: TOCDEV-6246
> fix(scheduler): fix null as end date

- packages/apps/admin/src/components/Admin/StyledComponents.js
- packages/core/tocco-ui/src/Range/Range.js
- packages/core/tocco-ui/src/Range/StyledRange.js
- packages/core/tocco-ui/src/Sidepanel/StyledComponents.js
Refs: TOCDEV-6064
Changelog: order range values on top instead of side by side to improve ux
> refactor(tocco-ui): change range value

- packages/core/app-extensions/src/actions/modules/actionHandlers/legacyAction.js
- packages/core/app-extensions/src/actions/modules/actionHandlers/legacyAction.spec.js
- dms entites should handled as entity_docs selection for legacy actions
Refs: TOCDEV-6314
Changelog: create ENTITY_DOCS selection for legacy actions
> fix(app-extensions): create ENTITY_DOCS selection for legacy actions

- packages/apps/admin/src/components/Navigation/menuType/StyledComponents.js
- packages/core/app-extensions/src/notification/modules/modal/ModalDisplay/StyledComponents.js
- packages/core/entity-list/src/components/SearchFilterList/StyledComponents.js
Refs: TOCDEV-6252
Changelog: show fullscreen modal based on screen width instead of generally switching to fullscreen on touch devices
> refactor(app-extenions): show fullscreen modal

- scripts/helpers.sh
- lern upgrade caused to change to yarn workspaces
- npm ls to list all dependencies has changed its behaviour
> chore: fix changelog and release script

- packages/core/entity-list/src/util/StyledComponents.js
Refs: TOCDEV-6324
Changelog: prevent action buttons within table of being missaligned in widgets
> refactor(entity-list): prevent button being pushed down

- packages/tocco-util/src/intl/intl.js
- packages/tocco-util/src/intl/intl.spec.js
cherrypick part of commit cf4e60af79da7ce3f274bb1bb4a006fd1746992b
Changelog: add locale to text resource caching key
Refs: TOCDEV-6435
> fix(tocco-util): add locale to text resource caching key

- packages/core/tocco-util/src/cache/cache.js
- packages/core/tocco-util/src/cache/cache.spec.js
- getter / setter from lodash will set nested objects when path includes `.`
- we do want to have a flat object with key names like `tocco.cache.display.Entity.1`
- therefore cannot use getters / setters from lodash
- however unset from loadash is working properly for our usecase
Refs: TOCDEV-6442
Changelog: fix object cache
> fix(tocco-util): fix object cache
